src/main/default/objects/WebCart/fields/Buyer_Email__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Email__c</fullName>
    <description>Used to capture buyer email on checkout flow.</description>
    <label>Buyer Email</label>
    <type>Email</type>
</CustomField>

src/main/default/objects/WebCart/fields/Buyer_Name__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Name__c</fullName>
    <description>Used to capture buyer name on checkout flow.</description>
    <label>Buyer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/WebCart/fields/Buyer_Phone__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Phone__c</fullName>
    <description>Used to capture buyer phone on checkout flow.</description>
    <label>Buyer Phone</label>
    <type>Phone</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Amount_Contributed__c.field-meta.xml
<CustomField>
    <fullName>DR_Amount_Contributed__c</fullName>
    <description>Amount contributed by store credit.</description>
    <inlineHelpText>Amount contributed by store credit.</inlineHelpText>
    <label>DR Amount Contributed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Amount_Remaining_to_be_Contributed__c.field-meta.xml
<CustomField>
    <fullName>DR_Amount_Remaining_to_be_Contributed__c</fullName>
    <description>Remaining amount after store credit contribution.</description>
    <inlineHelpText>Remaining amount after store credit contribution.</inlineHelpText>
    <label>DR Amount Remaining to be Contributed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Checkout_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_Checkout_Id__c</fullName>
    <description>The Digital River Checkout Identifier</description>
    <inlineHelpText>The Digital River Checkout Identifier</inlineHelpText>
    <label>DR Checkout Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>DR_Customer_Type__c</fullName>
    <description>Indicates the Customer Type stamped on the Cart.</description>
    <inlineHelpText>Indicates the Customer Type stamped on the Cart.</inlineHelpText>
    <label>DR Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>individual</fullName>
                <default>true</default>
                <label>individual</label>
            </value>
            <value>
                <fullName>business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Payment_Session_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_Payment_Session_Id__c</fullName>
    <description>The Digital River Payment Session Identifier</description>
    <inlineHelpText>The Digital River Payment Session Identifier</inlineHelpText>
    <label>DR Payment Session Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Source_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_Source_Id__c</fullName>
    <description>Stores a source Id attached to a checkout record</description>
    <inlineHelpText>Stores a source Id attached to a checkout record</inlineHelpText>
    <label>DR Source Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Total_Duty__c.field-meta.xml
<CustomField>
    <fullName>DR_Total_Duty__c</fullName>
    <description>Indicates the total amount of duty levied by the importing country.</description>
    <inlineHelpText>Indicates the total amount of duty levied by the importing country.</inlineHelpText>
    <label>DR Total Duty</label>
    <summarizedField>CartItem.DR_Duty__c</summarizedField>
    <summaryForeignKey>CartItem.CartId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Total_Fees__c.field-meta.xml
<CustomField>
    <fullName>DR_Total_Fees__c</fullName>
    <description>Regulatory Fees collected to address the manufacture, use, recovery, and recycling of Consumer Electronics products throughout the world.</description>
    <inlineHelpText>Regulatory Fees collected to address the manufacture, use, recovery, and recycling of Consumer Electronics products throughout the world.</inlineHelpText>
    <label>DR Total Fees</label>
    <summarizedField>CartItem.DR_Regulatory_Fee__c</summarizedField>
    <summaryForeignKey>CartItem.CartId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Total_IOR_Tax__c.field-meta.xml
<CustomField>
    <fullName>DR_Total_IOR_Tax__c</fullName>
    <description>Represents how much taxes the importer of record remits to the government.</description>
    <inlineHelpText>Represents how much taxes the importer of record remits to the government.</inlineHelpText>
    <label>DR Total IOR Tax</label>
    <summarizedField>CartItem.DR_IOR_Tax__c</summarizedField>
    <summaryForeignKey>CartItem.CartId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/objects/WebCart/fields/Has_Landed_Cost__c.field-meta.xml
<CustomField>
    <fullName>Has_Landed_Cost__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When true, indicates the Cart has Landed Costs associated with it. When false, indicates that the Cart does not have Landed Costs.</description>
    <inlineHelpText>When true, indicates the Cart has Landed Costs associated with it. When false, indicates that the Cart does not have Landed Costs.</inlineHelpText>
    <label>Has Landed Cost</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/WebCart/fields/Recurring_Line_Item_Count__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Line_Item_Count__c</fullName>
    <description>Indicates the Number of Recurring Line Items in this Cart</description>
    <inlineHelpText>Indicates the Number of Recurring Line Items in this Cart</inlineHelpText>
    <label>Recurring Line Item Count</label>
    <summaryFilterItems>
        <field>CartItem.Recurring_Line_Item__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>CartItem.CartId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/classes/model/DRB2B_CartModel.cls
public with sharing class DRB2B_CartModel implements Collection.Wrapper {
    public DRB2B_CartModel(List<DRB2B_RegulatoryFeeModal> fee) {
        this.regulatoryFee = new List<DRB2B_RegulatoryFeeModal>();
        this.regulatoryFee = fee;
    }

    public DRB2B_CartModel() {
    }
    public void wrap(Object item) {
        this.cart = (Webcart) item;
        this.id = containField('Id') ? this.cart.Id : null;
        this.IOR = containField('DR_Total_IOR_Tax__c') ? this.cart.DR_Total_IOR_Tax__c : null;
        this.hasLandedCost = containField('Has_Landed_Cost__c') ? this.cart.Has_Landed_Cost__c : null;
        this.totaFee = containField('DR_Total_Fees__c') ? this.cart.DR_Total_Fees__c : null;
        this.totalDuty = containField('DR_Total_Duty__c') ? this.cart.DR_Total_Duty__c : null;
        this.grandTotalAmount = containField('GrandTotalAmount') ? this.cart.GrandTotalAmount : null;
        this.totalAmount = containField('TotalProductAmount') ? this.cart.TotalProductAmount : null;
        this.shipping = containField('TotalChargeAmount') ? this.cart.TotalChargeAmount : null;
        this.totalTax = containField('TotalTaxAmount') ? this.cart.TotalTaxAmount : null;
        this.buyerName = containField('Buyer_Name__c') ? this.cart.Buyer_Name__c : null;
        this.buyerPhone = containField('Buyer_Phone__c') ? this.cart.Buyer_Phone__c : null;
        this.billingAddress = containField('BillingAddress') ? this.cart.BillingAddress : null;
        this.buyerEmail = containField('Buyer_Email__c') ? this.cart.Buyer_Email__c : null;
        this.paymentSession = containField('DR_Payment_Session_Id__c') ? this.cart.DR_Payment_Session_Id__c : null;
        this.drcheckoutId = containField('DR_Checkout_Id__c') ? this.cart.DR_Checkout_Id__c : null;
        this.sourceId = containField('DR_Source_Id__c') ? this.cart.DR_Source_Id__c : null;
        this.customerType = containField('DR_Customer_Type__c') ? this.cart.DR_Customer_Type__c : null;
        this.isRecurring = containField('Recurring_Line_Item_Count__c') ? this.cart.Recurring_Line_Item_Count__c > 0 : false;
        this.amountContributed = containField('DR_Amount_Contributed__c') ? this.cart.DR_Amount_Contributed__c : null;
        this.remainingAmount = containField('DR_Amount_Remaining_to_be_Contributed__c') ? this.cart.DR_Amount_Remaining_to_be_Contributed__c : null;
        this.totalAdjustmentAmount = containField('TotalAdjustmentAmount') ? this.cart.TotalAdjustmentAmount : null;
    }

    private String NAMESPACE = DRB2B_Utility.nameSpacePrefix();

    private boolean containField(string fieldName) {
        Set<String> fields = this.cart.getPopulatedFieldsAsMap().keySet();
        if (fieldName.endsWith('__c')) {
            return fields.contains(NAMESPACE + fieldName);
        }
        return fields.contains(fieldName);
    }

    public Webcart cart;

    @AuraEnabled
    public Decimal IOR { get; set; }

    @AuraEnabled
    public String id { get; set; }

    @AuraEnabled
    public Boolean hasLandedCost { get; set; }

    @AuraEnabled
    public Decimal totalAdjustmentAmount { get; set; }

    @AuraEnabled
    public Decimal totaFee { get; set; }

    @AuraEnabled
    public Decimal totalDuty { get; set; }

    @AuraEnabled
    public Decimal grandTotalAmount { get; set; }

    @AuraEnabled
    public Decimal totalAmount { get; set; }

    @AuraEnabled
    public Decimal shipping { get; set; }

    @AuraEnabled
    public Decimal amountContributed { get; set; }

    @AuraEnabled
    public Decimal remainingAmount { get; set; }

    @AuraEnabled
    public Decimal totalTax { get; set; }

    @AuraEnabled
    public String buyerName { get; set; }

    @AuraEnabled
    public String buyerPhone { get; set; }

    @AuraEnabled
    public String buyerEmail { get; set; }

    @AuraEnabled
    public Address billingAddress { get; set; }

    @AuraEnabled
    public String paymentSession { get; set; }

    @AuraEnabled
    public String drcheckoutId { get; set; }

    @AuraEnabled
    public String sourceId { get; set; }

    @AuraEnabled
    public String shipCountry { get; set; }

    @AuraEnabled
    public String customerType { get; set; }

    @AuraEnabled
    public Boolean isRecurring { get; set; }

    @AuraEnabled
    public List<DRB2B_RegulatoryFeeModal> regulatoryFee { get; set; }
}