src/main/default/objects/WebCart/fields/DR_Checkout_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_Checkout_Id__c</fullName>
    <description>The Digital River Checkout Identifier</description>
    <inlineHelpText>The Digital River Checkout Identifier</inlineHelpText>
    <label>DR Checkout Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Total_Duty__c.field-meta.xml
<CustomField>
    <fullName>DR_Total_Duty__c</fullName>
    <description>Indicates the total amount of duty levied by the importing country.</description>
    <inlineHelpText>Indicates the total amount of duty levied by the importing country.</inlineHelpText>
    <label>DR Total Duty</label>
    <summarizedField>CartItem.DR_Duty__c</summarizedField>
    <summaryForeignKey>CartItem.CartId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Total_Fees__c.field-meta.xml
<CustomField>
    <fullName>DR_Total_Fees__c</fullName>
    <description>Regulatory Fees collected to address the manufacture, use, recovery, and recycling of Consumer Electronics products throughout the world.</description>
    <inlineHelpText>Regulatory Fees collected to address the manufacture, use, recovery, and recycling of Consumer Electronics products throughout the world.</inlineHelpText>
    <label>DR Total Fees</label>
    <summarizedField>CartItem.DR_Regulatory_Fee__c</summarizedField>
    <summaryForeignKey>CartItem.CartId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Total_IOR_Tax__c.field-meta.xml
<CustomField>
    <fullName>DR_Total_IOR_Tax__c</fullName>
    <description>Represents how much taxes the importer of record remits to the government.</description>
    <inlineHelpText>Represents how much taxes the importer of record remits to the government.</inlineHelpText>
    <label>DR Total IOR Tax</label>
    <summarizedField>CartItem.DR_IOR_Tax__c</summarizedField>
    <summaryForeignKey>CartItem.CartId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/classes/selector/DRB2B_CartSelector.cls
public without sharing class DRB2B_CartSelector {
    public WebCart getById(Id cartId, Set<String> fields) {
        return (WebCart) new DCM_Query('WebCart')
            .selectFields(new List<String>(fields))
            .addConditionEq('Id', cartId)
            .run()[0];
    }

    public list<WebCart> getByForeignKey(String foreignKey, Set<String> fields, String foreignValue) {
        return (list<WebCart>) new DCM_Query('WebCart')
            .selectFields(new List<String>(fields))
            .addConditionEq(foreignKey, foreignValue)
            .run();
    }

    public WebCart getCartWithItemsById(String cartId, List<String> cartFields, List<String> cartItemFields) {
        return getCartWithItemsByIds(new Set<String>{ cartId }, cartFields, cartItemFields).get(0);
    }

    public List<WebCart> getCartWithItemsByIds(
        Set<String> cartId,
        List<String> cartFields,
        List<String> cartItemFields
    ) {
        return (List<WebCart>) new DCM_Query('WebCart')
            .selectFields(cartFields)
            .addSubquery('CartItems', cartItemFields)
            .addConditionEq('Id', cartId)
            .debug()
            .setLimit(2000)
            .run();
    }

    public List<WebCart> getCartItemWithDefaultFieldsById(String cartId) {
        return getCartWithItemsByIds(
            new Set<String>{ cartId },
            new List<String>{
                'DR_Total_IOR_Tax__c',
                'DR_Total_Duty__c',
                'DR_Total_Fees__c',
                'GrandTotalAmount',
                'TotalAmount'
            },
            new List<String>{ 'Sku', 'TotalAmount' }
        );
    }

    public WebCart getByCheckoutId(String checkoutId) {
        return (WebCart) new DCM_Query('WebCart')
            .selectField(WebCart.BillingStreet)
            .selectField(WebCart.BillingCity)
            .selectField(WebCart.BillingPostalCode)
            .selectField(WebCart.BillingCountry)
            .selectField(WebCart.BillingState)
            .addConditionEq(WebCart.DR_Checkout_Id__c, checkoutId)
            .run()[0];
    }

    public WebCart getByOrderSummaryId(Id orderSummaryId, Set<String> fields) {
        OrderSummary orderSummary = [
            SELECT Id, OriginalOrderId
            FROM OrderSummary
            WHERE Id = :orderSummaryId
            WITH SECURITY_ENFORCED
        ];

        CartCheckoutSession cartCheckoutSession = [
            SELECT Id, WebCartId
            FROM CartCheckoutSession
            WHERE OrderId = :orderSummary.OriginalOrderId AND IsArchived = FALSE
            WITH SECURITY_ENFORCED
        ];

        return (WebCart) new DCM_Query('WebCart')
            .selectFields(fields)
            .addConditionEq('Id', cartCheckoutSession.WebCartId)
            .run()
            .get(0);
    }
    public String getBySfOrderId(String sfOrderId) {
        String webCartId = [SELECT WebCartId FROM CartCheckoutSession WHERE OrderId = :sfOrderId AND IsArchived = FALSE]
        .WebCartId;

        return webCartId;
    }
}