src/main/default/objects/Digital_River_Tax_Mapping__c/Digital_River_Tax_Mapping__c.object-meta.xml
<CustomObject>
    <description>It will Store Digital River Tax Group, Tax Type, Tax Code and Product Type information</description>
    <label>Digital River Tax Mapping</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>DR Tax Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital River Tax Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Digital_River_Tax_Mapping__c/fields/DR_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>DR_Product_Type__c</fullName>
    <description>Indicates if the Product is Physical or Digital</description>
    <label>DR Product Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Digital_River_Tax_Mapping__c/fields/DR_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>DR_Tax_Code__c</fullName>
    <description>Stores Tax Code</description>
    <label>DR Tax Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Digital_River_Tax_Mapping__c/fields/DR_Tax_Group__c.field-meta.xml
<CustomField>
    <fullName>DR_Tax_Group__c</fullName>
    <description>Stores Tax Group</description>
    <label>DR Tax Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Digital_River_Tax_Mapping__c/fields/DR_Tax_Type__c.field-meta.xml
<CustomField>
    <fullName>DR_Tax_Type__c</fullName>
    <description>Stores Tax Type</description>
    <label>DR Tax Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/selector/DRB2B_DigitalRiverTaxMappingSelector.cls
// False-positive: the system should return read-only mapping - configurations
// to perform back-end calculations in context of the running Experience User
public without sharing class DRB2B_DigitalRiverTaxMappingSelector {

     // TODO: We should cache this query
    public List<Digital_River_Tax_Mapping__c> getAll() {
        return new DCM_Query(Digital_River_Tax_Mapping__c.sObjectType)
            .selectField(Digital_River_Tax_Mapping__c.DR_Tax_Type__c)
            .selectField(Digital_River_Tax_Mapping__c.DR_Tax_Group__c)
            .selectField(Digital_River_Tax_Mapping__c.DR_Tax_Code__c)
            .selectField(Digital_River_Tax_Mapping__c.DR_Product_Type__c)
            .setLimit(2000)
            .run();
    }
}