src/main/default/objects/Digital_River_Tax_Mapping__c/Digital_River_Tax_Mapping__c.object-meta.xml
<CustomObject>
    <description>It will Store Digital River Tax Group, Tax Type, Tax Code and Product Type information</description>
    <label>Digital River Tax Mapping</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>DR Tax Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital River Tax Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Digital_River_Tax_Mapping__c/fields/DR_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>DR_Tax_Code__c</fullName>
    <description>Stores Tax Code</description>
    <label>DR Tax Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Digital_River_Tax_Mapping__c/fields/DR_Tax_Group__c.field-meta.xml
<CustomField>
    <fullName>DR_Tax_Group__c</fullName>
    <description>Stores Tax Group</description>
    <label>DR Tax Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Digital_River_Tax_Mapping__c/fields/DR_Tax_Type__c.field-meta.xml
<CustomField>
    <fullName>DR_Tax_Type__c</fullName>
    <description>Stores Tax Type</description>
    <label>DR Tax Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_ECCN_Lookup__c/DR_ECCN_Lookup__c.object-meta.xml
<CustomObject>
    <label>Digital River ECCN Lookup</label>
    <nameField>
        <label>DR Classification Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Digital River ECCN Lookups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Product2/fields/Date_Last_Synced_to_DR__c.field-meta.xml
<CustomField>
    <fullName>Date_Last_Synced_to_DR__c</fullName>
    <label>Date Last Synced to DR</label>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/Product2/fields/DR_ECCN__c.field-meta.xml
<CustomField>
    <fullName>DR_ECCN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DR ECCN *</label>
    <referenceTo>DR_ECCN_Lookup__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Product2/fields/DR_HS_Code__c.field-meta.xml
<CustomField>
    <fullName>DR_HS_Code__c</fullName>
    <label>DR HS Code</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Product2/fields/DR_Managed_Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>DR_Managed_Fulfillment__c</fullName>
    <description>Signifies the product is physically fulfilled by Digital River</description>
    <inlineHelpText>Signifies the product is physically fulfilled by Digital River</inlineHelpText>
    <label>DR Managed Fulfillment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DRGlobalFulfillment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Product2/fields/DR_Manufacturer_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_Manufacturer_Id__c</fullName>
    <label>DR Manufacturer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Product2/fields/DR_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>DR_Part_Number__c</fullName>
    <description>The manufacturer’s part number</description>
    <label>DR Part Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Product2/fields/DR_Product_Country_Origin__c.field-meta.xml
<CustomField>
    <fullName>DR_Product_Country_Origin__c</fullName>
    <label>DR Product Country Origin *</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AX</fullName>
                <label>Åland Islands</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>DZ</fullName>
                <label>Algeria</label>
            </value>
            <value>
                <fullName>AS</fullName>
                <label>American Samoa</label>
            </value>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua And Barbuda</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BS</fullName>
                <label>Bahamas</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BZ</fullName>
                <label>Belize</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BT</fullName>
                <label>Bhutan</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia, Plurinational State Of</label>
            </value>
            <value>
                <fullName>BQ</fullName>
                <label>Bonaire, Sint Eustatius And Saba</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia And Herzegovina</label>
            </value>
            <value>
                <fullName>BW</fullName>
                <label>Botswana</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Product2/fields/DR_Product_Weight__c.field-meta.xml
<CustomField>
    <fullName>DR_Product_Weight__c</fullName>
    <description>The weight of the product measured in the unit specified by DR Unit of weight.</description>
    <inlineHelpText>The weight of the product measured in the unit specified by DR Unit of weight.</inlineHelpText>
    <label>DR Product Weight</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Product2/fields/DR_SKU_Group__c.field-meta.xml
<CustomField>
    <fullName>DR_SKU_Group__c</fullName>
    <label>DR SKU Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Product2/fields/DR_TAXGROUP__c.field-meta.xml
<CustomField>
    <fullName>DR_TAXGROUP__c</fullName>
    <label>DR TAXGROUP *</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Downloadable Goods (Non-Software)</fullName>
            </value>
            <value>
                <fullName>Food, Beverage &amp; Household</fullName>
            </value>
            <value>
                <fullName>Physical Goods</fullName>
            </value>
            <value>
                <fullName>Services &amp; Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Software (Downloadable &amp; Physical)</fullName>
            </value>
            <value>
                <fullName>Warranties</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Product2/fields/DR_TAXTYPE__c.field-meta.xml
<CustomField>
    <fullName>DR_TAXTYPE__c</fullName>
    <label>DR TAXTYPE *</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DR_TAXGROUP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>DR_TAXTYPES</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Product2/fields/DR_Unit_of_Weight__c.field-meta.xml
<CustomField>
    <fullName>DR_Unit_of_Weight__c</fullName>
    <description>Unit of measurement applied to DR</description>
    <inlineHelpText>Unit of measurement applied to DR</inlineHelpText>
    <label>DR Unit of Weight</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>oz</fullName>
            </value>
            <value>
                <fullName>lb</fullName>
            </value>
            <value>
                <fullName>g</fullName>
            </value>
            <value>
                <fullName>Kg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Product2/fields/Sync_Product_to_DR__c.field-meta.xml
<CustomField>
    <fullName>Sync_Product_to_DR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync Product to DR</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/globalValueSets/DR_TAXTYPES.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Digital Image</fullName>
    </customValue>
    <customValue>
        <fullName>Virtual Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Music</fullName>
    </customValue>
    <customValue>
        <fullName>Electronic Newspapers (Includes Subscriptions)</fullName>
    </customValue>
    <customValue>
        <fullName>Electronic Magazines (Includes Subscriptions)</fullName>
    </customValue>
    <customValue>
        <fullName>Educational / Vocational Texts</fullName>
    </customValue>
    <customValue>
        <fullName>eBooks</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Prescription Vitamins</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Prescription Drugs</fullName>
    </customValue>
    <customValue>
        <fullName>Miscellaneous Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Food - General</fullName>
    </customValue>
    <customValue>
        <fullName>Automatic Blood Pressure Monitors</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Stove</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Dehumidifier</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Air Conditioner</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Ceiling Fan</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Light Bulbs</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Freezer</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Refrigerator</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Washer</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Dryer</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Dishwasher</fullName>
    </customValue>
    <customValue>
        <fullName>Computer Supplies - Subscription</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile Devices</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Electronics (Photographic Filming or Video Equipment)</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Electronics (T.V. Monitor Display) - Size (&gt;4&quot;&lt;15&quot;)</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Electronics (T.V. Monitor Display) - Size (= or &gt;35&quot;)</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Electronics (T.V. Monitor Display) - Size (= or &gt;15&quot;&lt;35&quot;)</fullName>
    </customValue>
    <customValue>
        <fullName>Video Game Consoles and Accessories</fullName>
    </customValue>
    <masterLabel>DR TAXTYPES</masterLabel>
</GlobalValueSet>

src/main/default/classes/DRB2B_ProductsSyncBatch.cls
global with sharing class DRB2B_ProductsSyncBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {
    private static final DCM_Logger logger = DCM_Logger.getInstance(DRB2B_Constants.Module.PRODUCT_SYNC);
    private static final Stringifier stringifier = new Stringifier();
    @TestVisible
    private static DRB2B_ConnectorConfigurationSelector configurationSelector = new DRB2B_ConnectorConfigurationSelector();

    public static final String WITH_SECURITY_ENFORCED = ' WITH SECURITY_ENFORCED ';

    public List<Product2> allProcessedProducts = new List<Product2>();
    Map<String, String> taxCodeMap = new Map<String, String>();
    List<Digital_River_Tax_Mapping__c> taxCodesList = new List<Digital_River_Tax_Mapping__c>();

    Map<String, String> upadtedSKUMap = new Map<String, String>();
    public Set<String> failureProductIds = new Set<String>();
    Boolean isErrorExistsInJob = false; //To check if something failed in Job

    @TestVisible
    private DRB2B_DigitalRiverTaxMappingSelector taxMappingSelector = new DRB2B_DigitalRiverTaxMappingSelector();

    global DRB2B_ProductsSyncBatch() {
        try {
            this.taxCodesList = taxMappingSelector.getAll();
            if (taxCodesList.size() > 0) {
                for (Digital_River_Tax_Mapping__c taxCodes : taxCodesList) {
                    taxCodeMap.put(taxCodes.DR_Tax_Group__c + '#' + taxCodes.DR_Tax_Type__c, taxCodes.DR_Tax_Code__c);
                }
            }
        } catch (Exception e) {
            isErrorExistsInJob = true;
            logger.error(e);
        } finally {
            logger.flush();
        }
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        Database.QueryLocator queryLocator;
        try {
            String queryString = 'Select Id, IsActive, DR_SKU_Group__c,DR_Part_Number__c, Date_Last_Synced_to_DR__c, DR_ECCN__c, DR_HS_Code__c, DR_Product_Country_Origin__c, DR_TAXGROUP__c, DR_TAXTYPE__c, ProductCode, Name, Type, StockKeepingUnit, Sync_Product_to_DR__c,DR_Product_Weight__c,DR_Unit_of_Weight__c,DR_Managed_Fulfillment__c,DR_Manufacturer_Id__c,DR_ECCN__r.Name from Product2 ';
            String whereClause = ' where IsActive = true AND Sync_Product_to_DR__c = true AND ((DR_SKU_Group__c!=null) OR(DR_ECCN__c != null AND DR_TAXTYPE__c != null AND DR_TAXGROUP__c != null AND DR_Product_Country_Origin__c != null))';
            DRB2B_ConnectorConfigurationSelector configurationSelector = new DRB2B_ConnectorConfigurationSelector();
            String orderAndLimitString;
            if (Test.isRunningTest()) {
                orderAndLimitString = ' LIMIT 1 ';
            } else {
                //orderAndLimitString = ' LIMIT 100 ';
                orderAndLimitString = 'LIMIT ' + configurationSelector.getProductSyncJobQueryLimit();
            }

            String finalQuery = queryString + whereClause + WITH_SECURITY_ENFORCED + orderAndLimitString;
            logger.info('FinalQuery: ' + finalQuery);
            queryLocator = Database.getQueryLocator(finalQuery);
            logger.debug('Query from query locator: ' + queryLocator.getQuery());
        } catch (Exception e) {
            isErrorExistsInJob = true;
            logger.error(e);
        } finally {
            logger.flush();
        }
        return queryLocator;
    }

    global void execute(Database.BatchableContext bc, List<sObject> scope) {
        allProcessedProducts.addAll((List<Product2>) scope);
        logger.info('All products: ' + String.valueOf(allProcessedProducts));

        HttpResponse drproductSyncResponse;
        String httpBody;

        try {
            for (Product2 products : allProcessedProducts) {
                String taxCode = '';
                if (taxCodeMap.containsKey(products.DR_TAXGROUP__c + '#' + products.DR_TAXTYPE__c)) {
                    taxCode = taxCodeMap.get(products.DR_TAXGROUP__c + '#' + products.DR_TAXTYPE__c);
                }

                DRB2B_ProductService productService = new DRB2B_ProductService();
                DRB2B_ProductSyncUpsertSkuResponse drProductSyncResponseObj = productService.upsertProduct(
                    products.Id,
                    taxCode
                );

                logger.debug(httpBody);
                if (!drProductSyncResponseObj.isSuccess) {
                    isErrorExistsInJob = true;
                    failureProductIds.add(products.Id);
                }
            }
        } catch (Exception e) {
            isErrorExistsInJob = true;
            logger.error(e);
        } finally {
            logger.flush();
        }
    }

    global void finish(Database.BatchableContext bc) {
        try {
            if (allProcessedProducts.size() > 0) {
                List<Product2> productListForUpdating = new List<Product2>();
                for (Product2 products : allProcessedProducts) {
                    if (failureProductIds.size() > 0 && failureProductIds.contains(products.Id)) {
                        continue;
                    }
                    products.Date_Last_Synced_to_DR__c = DateTime.now();
                    products.Sync_Product_to_DR__c = false;
                    productListForUpdating.add(products);
                }
                DmlManager.updateAsUser(productListForUpdating);
            }
            Integer scheduleTime = configurationSelector.getBatchScheduleTime();
            String jobName = 'DR Product Sync Batch';
            Set<String> jobStatusSet = new Set<String>{ 'COMPLETE', 'DEBUG', 'DELETED', 'BLOCKED' };
            List<CronTrigger> crnTriggerObjList = [
                SELECT
                    Id,
                    CronJobDetailId,
                    CronJobDetail.Name,
                    NextFireTime,
                    PreviousFireTime,
                    State,
                    StartTime,
                    EndTime,
                    CronExpression,
                    TimeZoneSidKey,
                    OwnerId,
                    TimesTriggered
                FROM CronTrigger
                WHERE CronJobDetail.Name = :jobName
                LIMIT 1
            ];
            if (crnTriggerObjList != null && crnTriggerObjList.size() > 0) {
                CronTrigger crnTriggerObj = crnTriggerObjList.get(0);
                if (jobStatusSet.contains(crnTriggerObj.State.toUpperCase())) {
                    System.scheduleBatch(new DRB2B_ProductsSyncBatch(), 'DR Product Sync Batch', scheduleTime);
                }
            } else {
                System.scheduleBatch(new DRB2B_ProductsSyncBatch(), 'DR Product Sync Batch', scheduleTime);
            }
            //Send Email if Anything get Failed
            if (isErrorExistsInJob) {
                String emailToSend = configurationSelector.getConnectorNotificationEmail();
                DCM_EmailUtil.sendMail(
                    'Product Sync Job Failed',
                    'Product Sync Job Failed. Please check DCM Application logs for more information.',
                    emailToSend,
                    ''
                );
            }
        } catch (Exception e) {
            isErrorExistsInJob = true;
            logger.error(e);
        } finally {
            logger.flush();
        }
    }
}