src/main/default/objects/CartItem/fields/DR_Duty__c.field-meta.xml
<CustomField>
    <fullName>DR_Duty__c</fullName>
    <description>Indicates the total amount of duty levied by the importing country for this Line Item.</description>
    <inlineHelpText>Indicates the total amount of duty levied by the importing country for this Line Item.</inlineHelpText>
    <label>DR Duty</label>
    <summarizedField>CartTax.DR_Duty__c</summarizedField>
    <summaryForeignKey>CartTax.CartItemId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/objects/CartItem/fields/DR_IOR_Tax__c.field-meta.xml
<CustomField>
    <fullName>DR_IOR_Tax__c</fullName>
    <description>Represents how much taxes the importer of record remits to the government for this Line Item.</description>
    <inlineHelpText>Represents how much taxes the importer of record remits to the government for this Line Item.</inlineHelpText>
    <label>DR IOR Tax</label>
    <summarizedField>CartTax.DR_IOR_Tax__c</summarizedField>
    <summaryForeignKey>CartTax.CartItemId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/objects/CartItem/fields/DR_Regulatory_Fee__c.field-meta.xml
<CustomField>
    <fullName>DR_Regulatory_Fee__c</fullName>
    <description>Regulatory Fees collected to address the manufacture, use, recovery, and recycling of Consumer Electronics products throughout the world.</description>
    <inlineHelpText>Regulatory Fees collected to address the manufacture, use, recovery, and recycling of Consumer Electronics products throughout the world.</inlineHelpText>
    <label>DR Regulatory Fee</label>
    <summarizedField>CartTax.DR_Regulatory_Fee__c</summarizedField>
    <summaryForeignKey>CartTax.CartItemId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/objects/CartTax/fields/DR_Duty__c.field-meta.xml
<CustomField>
    <fullName>DR_Duty__c</fullName>
    <description>Indicates the amount of duty levied by the importing country for this Line Item.</description>
    <inlineHelpText>Indicates the amount of duty levied by the importing country for this Line Item.</inlineHelpText>
    <label>DR Duty</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/CartTax/fields/DR_IOR_Tax__c.field-meta.xml
<CustomField>
    <fullName>DR_IOR_Tax__c</fullName>
    <description>Represents how much taxes the importer of record remits to the government for this Line Item.</description>
    <inlineHelpText>Represents how much taxes the importer of record remits to the government for this Line Item.</inlineHelpText>
    <label>DR IOR Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/CartTax/fields/DR_Regulatory_Fee__c.field-meta.xml
<CustomField>
    <fullName>DR_Regulatory_Fee__c</fullName>
    <description>Regulatory Fees collected to address the manufacture, use, recovery, and recycling of Consumer Electronics products throughout the world.</description>
    <inlineHelpText>Regulatory Fees collected to address the manufacture, use, recovery, and recycling of Consumer Electronics products throughout the world.</inlineHelpText>
    <label>DR Regulatory Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/DR_Regulatory_Fee__c/DR_Regulatory_Fee__c.object-meta.xml
<CustomObject>
    <description>This object is used to capture Line Level Regulatory Fee information</description>
    <label>Digital River Regulatory Fee</label>
    <nameField>
        <displayFormat>DR-Reg-Fee-{000000}</displayFormat>
        <label>DR Regulatory Fee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital River Regulatory Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/checkout/classes/DRB2B_CartTaxService.cls
public without sharing class DRB2B_CartTaxService {
    @TestVisible
    private DCM_Logger logger = DCM_Logger.getInstance(DRB2B_Constants.Module.APP_CONFIG); //TODO:UPDATE MODULE

    @TestVisible
    private static final String ITEM_TYPE = 'CHARGE';

    public static Boolean isGuestUser = Auth.CommunitiesUtil.isGuestUser();

    public DRB2B_CartTaxService() {
    }

    public void updateCartTax(DRB2B_CreateCheckoutResponseModel response) {
        
        Map<String, DRB2B_CreateCheckoutResponseModel.Item> itemMap = new Map<String, DRB2B_CreateCheckoutResponseModel.Item>();
        for (DRB2B_CreateCheckoutResponseModel.Item item : response.items) {
            itemMap.put(item.skuId, item);
        }
        List<CartTax> cartTaxList = new List<CartTax>();
        for (cartTax tax : [
            SELECT Id, Amount, DR_Duty__c, DR_IOR_Tax__c, DR_Regulatory_Fee__c, CartItem.product2Id, CartItem.Type
            FROM CartTax
            WHERE CartId = :response.upstreamId
        ]) {
            if (!tax.CartItem.Type.equalsIgnoreCase(ITEM_TYPE)) {
                logger.debug('DRB2B_CartTaxService In updateCartTax' + tax.CartItem.Type);
                tax.Amount =
                    itemMap.get(tax.CartItem.product2Id).tax.amount +
                    itemMap.get(tax.CartItem.product2Id).fees.taxAmount;
                tax.DR_Duty__c = itemMap.get(tax.CartItem.product2Id).duties.amount;
                tax.DR_IOR_Tax__c = itemMap.get(tax.CartItem.product2Id).importerTax.amount;
                tax.DR_Regulatory_Fee__c = itemMap.get(tax.CartItem.product2Id).fees.amount;
                cartTaxList.add(tax);
            } else {
                logger.debug('DRB2B_CartTaxService In updateCartTax' + tax.CartItem.Type);
                if (response.shippingChoice != null) {
                    tax.Amount = response.shippingChoice.taxAmount;
                    cartTaxList.add(tax);
                }
            }
        }
        logger.info('DRB2B_CartTaxService updated cartItems with new tax ' + JSON.serialize(cartTaxList));
        if (!isGuestUser) {
            DMLManager.updateAsUser(cartTaxList);
        } else {
            DmlManager.updateAsSystem(cartTaxList);
        }
    }
}