src/main/default/objects/CartItem/fields/DR_Regulatory_Fee__c.field-meta.xml
<CustomField>
    <fullName>DR_Regulatory_Fee__c</fullName>
    <description>Regulatory Fees collected to address the manufacture, use, recovery, and recycling of Consumer Electronics products throughout the world.</description>
    <inlineHelpText>Regulatory Fees collected to address the manufacture, use, recovery, and recycling of Consumer Electronics products throughout the world.</inlineHelpText>
    <label>DR Regulatory Fee</label>
    <summarizedField>CartTax.DR_Regulatory_Fee__c</summarizedField>
    <summaryForeignKey>CartTax.CartItemId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/objects/Digital_River_Tax_Mapping__c/Digital_River_Tax_Mapping__c.object-meta.xml
<CustomObject>
    <description>It will Store Digital River Tax Group, Tax Type, Tax Code and Product Type information</description>
    <label>Digital River Tax Mapping</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>DR Tax Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital River Tax Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Digital_River_Tax_Mapping__c/fields/DR_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>DR_Product_Type__c</fullName>
    <description>Indicates if the Product is Physical or Digital</description>
    <label>DR Product Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Digital_River_Tax_Mapping__c/fields/DR_Tax_Group__c.field-meta.xml
<CustomField>
    <fullName>DR_Tax_Group__c</fullName>
    <description>Stores Tax Group</description>
    <label>DR Tax Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Digital_River_Tax_Mapping__c/fields/DR_Tax_Type__c.field-meta.xml
<CustomField>
    <fullName>DR_Tax_Type__c</fullName>
    <description>Stores Tax Type</description>
    <label>DR Tax Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Regulatory_Fee__c/DR_Regulatory_Fee__c.object-meta.xml
<CustomObject>
    <description>This object is used to capture Line Level Regulatory Fee information</description>
    <label>Digital River Regulatory Fee</label>
    <nameField>
        <displayFormat>DR-Reg-Fee-{000000}</displayFormat>
        <label>DR Regulatory Fee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital River Regulatory Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/DR_Regulatory_Fee__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>PerUnitAmount multiplied by the quantity of the line item. This does not include Tax</description>
    <inlineHelpText>PerUnitAmount multiplied by the quantity of the line item. This does not include Tax</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/DR_Regulatory_Fee__c/fields/Cart_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>Cart_Item_Id__c</fullName>
    <description>SF Cart Item Id to which Regulatory Fee Record is associated</description>
    <inlineHelpText>SF Cart Item Id to which Regulatory Fee Record is associated</inlineHelpText>
    <label>Cart Item Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Regulatory_Fee__c/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <description>The type of Fee. Valid values are battery, weee, copyright, e_waste and packaging</description>
    <inlineHelpText>The type of Fee. Valid values are battery, weee, copyright, e_waste and packaging</inlineHelpText>
    <label>Fee Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/InvoiceCreditMemo/objects/Order/fields/DR_Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>DR_Customer_Type__c</fullName>
    <description>Indicates the Customer Type stamped on the Order</description>
    <inlineHelpText>Indicates the Customer Type stamped on the Order</inlineHelpText>
    <label>Digital River Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>individual</fullName>
            </value>
            <value>
                <fullName>business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/InvoiceCreditMemo/objects/Order/fields/DR_Tax_Identifiers__c.field-meta.xml
<CustomField>
    <fullName>DR_Tax_Identifiers__c</fullName>
    <description>Comma-separated list of Global Tax Identifiers that are applied to this Order</description>
    <inlineHelpText>Comma-separated list of Global Tax Identifiers that are applied to this Order</inlineHelpText>
    <label>Digital River Tax Identifiers</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

src/main/InvoiceCreditMemo/objects/Order/fields/DR_Total_Duty__c.field-meta.xml
<CustomField>
    <fullName>DR_Total_Duty__c</fullName>
    <label>DR Total Duty</label>
    <summarizedField>OrderItem.DR_Duty__c</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/InvoiceCreditMemo/objects/Order/fields/DR_Total_IOR_Tax__c.field-meta.xml
<CustomField>
    <fullName>DR_Total_IOR_Tax__c</fullName>
    <label>DR Total IOR Tax</label>
    <summarizedField>OrderItem.DR_IOR_Tax__c</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/InvoiceCreditMemo/objects/Order/fields/Has_Landed_Cost__c.field-meta.xml
<CustomField>
    <fullName>Has_Landed_Cost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Landed Cost</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Product2/fields/DR_IS_DIGITAL_PRODUCT__c.field-meta.xml
<CustomField>
        <fullName>DR_IS_DIGITAL_PRODUCT__c</fullName>
        <defaultValue>true</defaultValue>
        <label>DR Digital Product</label>
        <type>Checkbox</type>
</CustomField>

src/main/default/objects/Product2/fields/DR_TAXGROUP__c.field-meta.xml
<CustomField>
    <fullName>DR_TAXGROUP__c</fullName>
    <label>DR TAXGROUP *</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Downloadable Goods (Non-Software)</fullName>
            </value>
            <value>
                <fullName>Food, Beverage &amp; Household</fullName>
            </value>
            <value>
                <fullName>Physical Goods</fullName>
            </value>
            <value>
                <fullName>Services &amp; Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Software (Downloadable &amp; Physical)</fullName>
            </value>
            <value>
                <fullName>Warranties</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Product2/fields/DR_TAXTYPE__c.field-meta.xml
<CustomField>
    <fullName>DR_TAXTYPE__c</fullName>
    <label>DR TAXTYPE *</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DR_TAXGROUP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>DR_TAXTYPES</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Amount_Contributed__c.field-meta.xml
<CustomField>
    <fullName>DR_Amount_Contributed__c</fullName>
    <description>Amount contributed by store credit.</description>
    <inlineHelpText>Amount contributed by store credit.</inlineHelpText>
    <label>DR Amount Contributed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Amount_Remaining_to_be_Contributed__c.field-meta.xml
<CustomField>
    <fullName>DR_Amount_Remaining_to_be_Contributed__c</fullName>
    <description>Remaining amount after store credit contribution.</description>
    <inlineHelpText>Remaining amount after store credit contribution.</inlineHelpText>
    <label>DR Amount Remaining to be Contributed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_CartItemStructure__c.field-meta.xml
<CustomField>
    <fullName>DR_CartItemStructure__c</fullName>
        <label>CartItemStructure</label>
        <length>32768</length>
        <type>Html</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Checkout_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_Checkout_Id__c</fullName>
    <description>The Digital River Checkout Identifier</description>
    <inlineHelpText>The Digital River Checkout Identifier</inlineHelpText>
    <label>DR Checkout Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Checkout_Type__c.field-meta.xml
<CustomField>
    <fullName>DR_Checkout_Type__c</fullName>
    <description>The type of products stored in the Cart: Non-Digital, Digital</description>
    <inlineHelpText>The type of products stored in the Cart: Non-Digital, Digital</inlineHelpText>
    <label>DR Checkout Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Non-Digital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>DR_Customer_Type__c</fullName>
    <description>Indicates the Customer Type stamped on the Cart.</description>
    <inlineHelpText>Indicates the Customer Type stamped on the Cart.</inlineHelpText>
    <label>DR Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>individual</fullName>
                <default>true</default>
                <label>individual</label>
            </value>
            <value>
                <fullName>business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Guest_IpAddress__c.field-meta.xml
<CustomField>
    <fullName>DR_Guest_IpAddress__c</fullName>
        <label>DR Guest IpAddress</label>
        <length>50</length>
        <type>Text</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Payment_Session_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_Payment_Session_Id__c</fullName>
    <description>The Digital River Payment Session Identifier</description>
    <inlineHelpText>The Digital River Payment Session Identifier</inlineHelpText>
    <label>DR Payment Session Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Selling_Entity__c.field-meta.xml
<CustomField>
    <fullName>DR_Selling_Entity__c</fullName>
    <description>The Digital River Business Selling Entity</description>
    <inlineHelpText>The Digital River Business Selling Entity</inlineHelpText>
    <label>DR Selling Entity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Source_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_Source_Id__c</fullName>
    <description>Stores a source Id attached to a checkout record</description>
    <inlineHelpText>Stores a source Id attached to a checkout record</inlineHelpText>
    <label>DR Source Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Tax_Identifiers__c.field-meta.xml
<CustomField>
    <fullName>DR_Tax_Identifiers__c</fullName>
    <description>Comma-separated list of Global Tax Identifiers that are applied to this Cart. This captures the Unique Id generated by DR for each Tax identifier and does not store the actual Tax identifier value entered by the Customer.</description>
    <inlineHelpText>Comma-separated list of Global Tax Identifiers that are applied to this Cart. This captures the Unique Id generated by DR for each Tax identifier and does not store the actual Tax identifier value entered by the Customer.</inlineHelpText>
    <label>DR Tax Identifiers</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Total_Duty__c.field-meta.xml
<CustomField>
    <fullName>DR_Total_Duty__c</fullName>
    <description>Indicates the total amount of duty levied by the importing country.</description>
    <inlineHelpText>Indicates the total amount of duty levied by the importing country.</inlineHelpText>
    <label>DR Total Duty</label>
    <summarizedField>CartItem.DR_Duty__c</summarizedField>
    <summaryForeignKey>CartItem.CartId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Total_Fees__c.field-meta.xml
<CustomField>
    <fullName>DR_Total_Fees__c</fullName>
    <description>Regulatory Fees collected to address the manufacture, use, recovery, and recycling of Consumer Electronics products throughout the world.</description>
    <inlineHelpText>Regulatory Fees collected to address the manufacture, use, recovery, and recycling of Consumer Electronics products throughout the world.</inlineHelpText>
    <label>DR Total Fees</label>
    <summarizedField>CartItem.DR_Regulatory_Fee__c</summarizedField>
    <summaryForeignKey>CartItem.CartId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Total_IOR_Tax__c.field-meta.xml
<CustomField>
    <fullName>DR_Total_IOR_Tax__c</fullName>
    <description>Represents how much taxes the importer of record remits to the government.</description>
    <inlineHelpText>Represents how much taxes the importer of record remits to the government.</inlineHelpText>
    <label>DR Total IOR Tax</label>
    <summarizedField>CartItem.DR_IOR_Tax__c</summarizedField>
    <summaryForeignKey>CartItem.CartId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/objects/WebCart/fields/Has_Landed_Cost__c.field-meta.xml
<CustomField>
    <fullName>Has_Landed_Cost__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When true, indicates the Cart has Landed Costs associated with it. When false, indicates that the Cart does not have Landed Costs.</description>
    <inlineHelpText>When true, indicates the Cart has Landed Costs associated with it. When false, indicates that the Cart does not have Landed Costs.</inlineHelpText>
    <label>Has Landed Cost</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/globalValueSets/DR_TAXTYPES.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Digital Image</fullName>
    </customValue>
    <customValue>
        <fullName>Virtual Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Music</fullName>
    </customValue>
    <customValue>
        <fullName>Electronic Newspapers (Includes Subscriptions)</fullName>
    </customValue>
    <customValue>
        <fullName>Electronic Magazines (Includes Subscriptions)</fullName>
    </customValue>
    <customValue>
        <fullName>Educational / Vocational Texts</fullName>
    </customValue>
    <customValue>
        <fullName>eBooks</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Prescription Vitamins</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Prescription Drugs</fullName>
    </customValue>
    <customValue>
        <fullName>Miscellaneous Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Food - General</fullName>
    </customValue>
    <customValue>
        <fullName>Automatic Blood Pressure Monitors</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Stove</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Dehumidifier</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Air Conditioner</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Ceiling Fan</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Light Bulbs</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Freezer</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Refrigerator</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Washer</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Dryer</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Dishwasher</fullName>
    </customValue>
    <customValue>
        <fullName>Computer Supplies - Subscription</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile Devices</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Electronics (Photographic Filming or Video Equipment)</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Electronics (T.V. Monitor Display) - Size (&gt;4&quot;&lt;15&quot;)</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Electronics (T.V. Monitor Display) - Size (= or &gt;35&quot;)</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Electronics (T.V. Monitor Display) - Size (= or &gt;15&quot;&lt;35&quot;)</fullName>
    </customValue>
    <customValue>
        <fullName>Video Game Consoles and Accessories</fullName>
    </customValue>
    <masterLabel>DR TAXTYPES</masterLabel>
</GlobalValueSet>

src/main/checkout/classes/DRB2B_CartService.cls
public without sharing class DRB2B_CartService {
    @TestVisible
    private static DCM_Logger logger = DCM_Logger.getInstance();

    @TestVisible
    private DRB2B_DigitalRiverTaxMappingSelector taxMappingSelector = new DRB2B_DigitalRiverTaxMappingSelector();

    @TestVisible
    private DRB2B_CartItemSelector cartItemSelector = new DRB2B_CartItemSelector();

    @TestVisible
    private static final String FOREIGN_KEY = 'CartId';

    @TestVisible
    private static final String PHYSICAL = 'Physical';

    @TestVisible
    private static final String PHYSICAL_VAL = 'Non-Digital';

    @TestVisible
    private static final String DIGITAL = 'Digital';

    @TestVisible
    private static final Set<String> FIELDSET = new Set<String>{
        'Product2.DR_TAXGROUP__c',
        'Product2.DR_TAXTYPE__c',
        'Product2.DR_IS_DIGITAL_PRODUCT__c',
        'CartId',
        'Cart.DR_Checkout_Type__c',
        'Type'
    };

    @TestVisible
    private DRB2B_CartSelector cartSelector = new DRB2B_CartSelector();

    @TestVisible
    private DRB2B_RegulatoryFeeSelector feeSelector = new DRB2B_RegulatoryFeeSelector();

    @TestVisible
    public static Boolean isGuestUser = Auth.CommunitiesUtil.isGuestUser();

    @AuraEnabled
    public static void setIpAddress(String ipaddress, String cartId) {
        WebCart wcart = [SELECT id, DR_Guest_IpAddress__c FROM WebCart WHERE id = :cartId];
        wCart.DR_Guest_IpAddress__c = ipaddress;
        Boolean isGuestUser = Auth.CommunitiesUtil.isGuestUser();
        if (isGuestUser) {
            DmlManager.updateAsSystem(wCart);
        }
    }

    /**
     * Used to identify cart Type based on Cart Items
     *
     * @param cartId - Cart Id to determine a type
     *
     * @return A type of the cart PHYSICAL and DIGITAL
     */
    public String getCheckoutType(Id cartId) {
        return this.getCheckoutType(new Set<Id>{ cartId }).get(cartId);
    }

    /**
     * Used to identify cart Type based on carts Items
     *
     * @param cartIds - Cart Ids to determine a type of each
     *
     * @return Map where key is cart Id and possible value is PHYSICAL and DIGITAL
     */
    public Map<String, String> getCheckoutType(Set<Id> cartIds) {
        Map<String, String> response = new Map<String, String>();
        Map<String, String> taxTypeMap = getTaxTypeMap();

        logger.info('Tax Type Map ' + JSON.serialize(taxTypeMap));

        List<CartItem> cartItems = cartItemSelector.getByForeignKey(FOREIGN_KEY, FIELDSET, cartIds);
        for (CartItem item : cartItems) {
            if (!isChargeType(item)) {
                /*if (isCheckoutTypeResolved(response, item)) {
                    continue;
                } else if (isCheckoutTypePhysical(taxTypeMap, item)) {
                    response.put(item.CartId, PHYSICAL_VAL);
                } else if (isCheckoutTypeDigital(response, item)) {
                    response.put(item.CartId, DIGITAL);
                }*/
                if(item.Product2.DR_IS_DIGITAL_PRODUCT__c==true){
                    response.put(item.CartId,DIGITAL);
                }
                else
                {
                    response.put(item.CartId,PHYSICAL_VAL);
                }
            }
        }
        return response;
    }

    private Boolean isCheckoutTypeDigital(Map<String, String> response, CartItem item) {
        return !response.containsKey(item.CartId);
    }

    private Boolean isCheckoutTypePhysical(Map<String, String> taxTypeMap, CartItem item) {
        return PHYSICAL.equalsIgnoreCase(
            taxTypeMap.get(item.Product2.DR_TAXGROUP__c + '#' + item.Product2.DR_TAXTYPE__c)
        );
    }

    private Boolean isChargeType(CartItem cartItem) {
        return cartItem.Type == 'Charge';
    }

    private Boolean isCheckoutTypeResolved(Map<String, String> response, CartItem item) {
        return response.containsKey(item.CartId) && PHYSICAL.equalsIgnoreCase(response.get(item.CartId));
    }

    public Map<String, String> getTaxTypeMap() {
        Map<String, String> taxTypeMap = new Map<String, String>();
        List<Digital_River_Tax_Mapping__c> taxCodesList = taxMappingSelector.getAll();
        for (Digital_River_Tax_Mapping__c taxCodes : taxCodesList) {
            taxTypeMap.put(taxCodes.DR_Tax_Group__c + '#' + taxCodes.DR_Tax_Type__c, taxCodes.DR_Product_Type__c);
        }
        return taxTypeMap;
    }

    public DRB2B_CartModel getCartTaxAndFee(Id cartId) {
        Webcart cart = cartSelector.getById(
            cartId,
            new Set<String>{
                'Has_Landed_Cost__c',
                'DR_Total_IOR_Tax__c',
                'DR_Total_Fees__c',
                'DR_Total_Duty__c',
                'TotalProductAmount',
                'GrandTotalAmount',
                'TotalChargeTaxAmount',
                'TotalChargeAmount',
                'TotalTaxAmount',
                'DR_Source_Id__c',
                'DR_Amount_Contributed__c',
                'DR_Amount_Remaining_to_be_Contributed__c',
                'TotalAdjustmentAmount',
                'DR_Checkout_Id__c'
            }
        );
        DRB2B_CartModel cartModel = new DRB2B_CartModel(getRegulatoryFeeByCarId(cartId));
        cartModel.wrap(cart);
        return cartModel;
    }

    public List<DRB2B_RegulatoryFeeModal> getRegulatoryFeeByCarId(Id cartId) {
        List<CartItem> cartItems = cartItemSelector.getByForeignKey(
            FOREIGN_KEY,
            new Set<String>{ 'CartId', 'Name' },
            new Set<Id>{ cartId }
        );
        Set<Id> cartitemsIds = (new Map<Id, SObject>(cartItems)).keySet();
        list<DR_Regulatory_Fee__c> feeList = feeSelector.getByCartItemId(
            new Set<String>{ 'Fee_Type__c', 'Name', 'Amount__c', 'Id', 'Cart_Item_Id__c' },
            cartitemsIds
        );
        return (List<DRB2B_RegulatoryFeeModal>) Collection.of(feeList).wrap(DRB2B_RegulatoryFeeModal.class).get();
    }

    public DRB2B_CartModel getCartAsWrapper(Webcart cart) {
        DRB2B_CartModel cartModel = new DRB2B_CartModel();
        cartModel.wrap(cart);
        return cartModel;
    }

    public void clearAddress(Set<string> cartIds) {
        List<SObject> payload = new List<SObject>();
        for (string id : cartIds) {
            webcart cart = new webcart();
            cart.Id = id;
            cart.BillingState = '';
            cart.BillingCountry = '';
            cart.BillingPostalCode = '';
            cart.BillingCity = '';
            cart.BillingStreet = '';
            cart.DR_Selling_Entity__c = '';
            payload.add(cart);
        }

        for (CartDeliveryGroup deliveryGroup : [
            SELECT DeliverToCity, DeliverToState, DeliverToStreet, DeliverToCountry, DeliverToPostalCode
            FROM CartDeliveryGroup
            WHERE CartId IN :cartIds
            WITH SECURITY_ENFORCED
        ]) {
            deliveryGroup.DeliverToCity = '';
            deliveryGroup.DeliverToState = '';
            deliveryGroup.DeliverToStreet = '';
            deliveryGroup.DeliverToCountry = '';
            deliveryGroup.DeliverToPostalCode = '';
            payload.add(deliveryGroup);
        }

        if (!isGuestUser) {
            DMLManager.updateAsUser(payload);
        } else {
            DMLManager.updateAsSystem(payload);
        }
    }

    public void clearDataRelatedToDr(Set<string> cartIds) {
        List<Sobject> payload = new List<Sobject>();
        for (String id : cartIds) {
            webcart cart = new webcart();
            cart.Id = id;
            cart.DR_Source_Id__c = '';
            cart.DR_Tax_Identifiers__c = '';
            cart.DR_Payment_Session_Id__c = '';
            cart.Has_Landed_Cost__c = false;
            cart.DR_Customer_Type__c = 'individual';
            cart.DR_Amount_Contributed__c = null;
            cart.DR_Amount_Remaining_to_be_Contributed__c = null;
            cart.DR_CartItemStructure__c = '';
            payload.add(cart);
        }

        if (!isGuestUser) {
            DMLManager.updateAsUser(payload);
        } else {
            DMLManager.updateAsSystem(payload);
        }
    }

    /**
     * Cancel Checkout if DR order failed
     */
    public void cancelCartSession(String cartId) {
        DRB2B_CartCheckoutSessionSelector cartCheckoutSessionSelector = new DRB2B_CartCheckoutSessionSelector();
        CartCheckoutSession session = cartCheckoutSessionSelector.getActiveSessionForCart(
            cartId,
            new Set<String>{ 'Id', 'IsArchived' }
        );
        session.IsArchived = true;
        DmlManager.updateAssystem(session);
    }

    /**
     * Cancel Checkout if Promotion Is added/removed
     */

    public void cancelActiveCartSession(List<String> cartIds) {
        DRB2B_CartCheckoutSessionSelector cartCheckoutSessionSelector = new DRB2B_CartCheckoutSessionSelector();
        List<CartCheckoutSession> session = cartCheckoutSessionSelector.getListOfActiveSessionForCart(
            cartIds,
            new Set<String>{ 'Id', 'IsArchived' }
        );
        if (session.size() != 0) {
            session[0].IsArchived = true;
            DmlManager.updateAssystem(session);
        }
    }

    @AuraEnabled
    public static void clearAllDataLWR(String cartId) {
        try {
            if (cartId != null) {
                List<Id> cartIdList = new List<Id>();
                cartIdList.add(Id.valueOf(cartId));
                DRB2B_ClearData.clearDataLWR(cartIdList);
            }
        } catch (Exception e) {
            logger.error(e);
            throw new AuraHandledException(e.getMessage());
        } finally {
            logger.flush();
        }
    }

    @AuraEnabled
    public static void clearCartItemStructure(String cartId) {
        try{
            logger.info('drb2b_cartService clearCartItemStructure cartId' + cartId);
            if (cartId != null) {
            List<Sobject> payload = new List<Sobject>();
            webcart cart = new webcart();
            cart.Id = cartId;
            cart.DR_CartItemStructure__c = '';
            payload.add(cart);
            logger.info('drb2b_cartService clearCartItemStructure payload' + payload);
        if (!isGuestUser) {
            DMLManager.updateAsUser(payload);
        } else {
            DMLManager.updateAsSystem(payload);
        }
    }
    }
    catch(Exception e) {
        logger.error('drb2b_cartService clearCartItemStructure failure for the cart' + cartId);
    } 
}

}