src/main/default/objects/Product2/fields/Date_Last_Synced_to_DR__c.field-meta.xml
<CustomField>
    <fullName>Date_Last_Synced_to_DR__c</fullName>
    <label>Date Last Synced to DR</label>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/Product2/fields/DR_ECCN__c.field-meta.xml
<CustomField>
    <fullName>DR_ECCN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DR ECCN *</label>
    <referenceTo>DR_ECCN_Lookup__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Product2/fields/DR_Product_Country_Origin__c.field-meta.xml
<CustomField>
    <fullName>DR_Product_Country_Origin__c</fullName>
    <label>DR Product Country Origin *</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AX</fullName>
                <label>Åland Islands</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>DZ</fullName>
                <label>Algeria</label>
            </value>
            <value>
                <fullName>AS</fullName>
                <label>American Samoa</label>
            </value>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua And Barbuda</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BS</fullName>
                <label>Bahamas</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BZ</fullName>
                <label>Belize</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BT</fullName>
                <label>Bhutan</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia, Plurinational State Of</label>
            </value>
            <value>
                <fullName>BQ</fullName>
                <label>Bonaire, Sint Eustatius And Saba</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia And Herzegovina</label>
            </value>
            <value>
                <fullName>BW</fullName>
                <label>Botswana</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Product2/fields/DR_TAXGROUP__c.field-meta.xml
<CustomField>
    <fullName>DR_TAXGROUP__c</fullName>
    <label>DR TAXGROUP *</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Downloadable Goods (Non-Software)</fullName>
            </value>
            <value>
                <fullName>Food, Beverage &amp; Household</fullName>
            </value>
            <value>
                <fullName>Physical Goods</fullName>
            </value>
            <value>
                <fullName>Services &amp; Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Software (Downloadable &amp; Physical)</fullName>
            </value>
            <value>
                <fullName>Warranties</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Product2/fields/Sync_Product_to_DR__c.field-meta.xml
<CustomField>
    <fullName>Sync_Product_to_DR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync Product to DR</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/classes/DRB2B_ProductSyncUtil.cls
public with sharing class DRB2B_ProductSyncUtil {
    private static final DCM_Logger logger = DCM_Logger.getInstance(DRB2B_Constants.Module.PRODUCT_SYNC);

    public static Map<String, String> drapplicationConfigMap = DRB2B_Utility.getDRapplicationConfigMap();
    public static Map<String, String> drConnectorConfigMap = DRB2B_Utility.getDRConnectorConfigMap();

    public static String syncProducts(String jsonString) {
        Integer defaultBatchSize = 100; // Cannot make more than 100 Callouts in Execute Method
        Map<String, Object> returnedMap = new Map<String, Object>();
        Map<String, Object> requestMap = (Map<String, Object>) JSON.deserializeUntyped(jsonString);

        Boolean isSyncAllProduct = Boolean.valueOf(requestMap.get('isSyncAll'));
        Boolean isSyncProduct = Boolean.valueOf(requestMap.get('isSyncProduct'));
        List<Product2> productList = new List<Product2>();

        try {
            // TODO: Move all SOQL to Selectors!
            if (isSyncAllProduct) {
                productList = new DCM_Query(Product2.sObjectType)
                    .selectField(Product2.DR_ECCN__c)
                    .selectField(Product2.DR_TAXGROUP__c)
                    .selectField(Product2.DR_Product_Country_Origin__c)
                    .addConditionEq(Product2.IsActive, true)
                    .setLimit(2000)
                    .run();
            } else {
                productList = new DCM_Query(Product2.sObjectType)
                    .selectField(Product2.DR_ECCN__c)
                    .selectField(Product2.DR_TAXGROUP__c)
                    .selectField(Product2.DR_Product_Country_Origin__c)
                    .addConditionEq(Product2.IsActive, true)
                    .addConditionEq(Product2.Sync_Product_to_DR__c, true)
                    .setLimit(2000)
                    .run();
            }
            if (productList.size() > 0) {
                String jobName = 'DR Product Sync Batch';
                List<CronTrigger> crnTriggerObjList = [
                    SELECT
                        Id,
                        CronJobDetailId,
                        CronJobDetail.Name,
                        NextFireTime,
                        PreviousFireTime,
                        State,
                        StartTime,
                        EndTime,
                        CronExpression,
                        TimeZoneSidKey,
                        OwnerId,
                        TimesTriggered
                    FROM CronTrigger
                    WHERE CronJobDetail.Name = :jobName
                    WITH SECURITY_ENFORCED
                    LIMIT 1
                ];
                if (crnTriggerObjList != null && crnTriggerObjList.size() > 0) {
                    System.abortJob(crnTriggerObjList.get(0).Id);
                }

                if (isSyncAllProduct) {
                    for (Product2 product : productList) {
                        product.Date_Last_Synced_to_DR__c = null;
                    }

                    try {
                        logger.debug('Product Update Cleaned Records List: ' + String.valueOf(productList));

                        DmlManager.updateAsUser(productList);
                        returnedMap.put('isSuccess', true);
                        returnedMap.put('msg', 'All products will be re-synchronized.');

                        DRB2B_ProductsSyncBatch batchContext = new DRB2B_ProductsSyncBatch();
                        // Batch Size cannot be more than 100 as we Cannot make more than 100 Callouts in Execute Method.
                        Integer batchSize = defaultBatchSize;
                        Integer configuredBatchSize = Integer.valueOf(drConnectorConfigMap.get('Product_Batch_Size'));
                        if (configuredBatchSize > 0 && configuredBatchSize < defaultBatchSize) {
                            batchSize = configuredBatchSize;
                        }

                        if (!Test.isRunningTest()) {
                            Database.executeBatch(batchContext, batchSize);
                        }
                    } catch (Exception e) {
                        returnedMap.put('isSuccess', false);
                        returnedMap.put('msg', 'Please Add user in permission set.');
                    }
                } else {
                    if (isSyncProduct) {
                        DRB2B_ProductsSyncBatch batchContext = new DRB2B_ProductsSyncBatch();
                        Integer batchSize = String.isNotBlank(drapplicationConfigMap.get('Product_Batch_Size'))
                            ? Integer.valueOf(drapplicationConfigMap.get('Product_Batch_Size'))
                            : defaultBatchSize;
                        if (!Test.isRunningTest()) {
                            Database.executeBatch(batchContext, batchSize);
                        }
                        returnedMap.put('isSuccess', true);
                        returnedMap.put('msg', 'Batch Job has been submitted.');
                    }
                }
            } else {
                returnedMap.put('isSuccess', true);
                returnedMap.put('isWarning', true);
                returnedMap.put('msg', 'No product to Sync.');
            }
        } catch (Exception e) {
            logger.error(e);
            returnedMap.put('isSuccess', false);
            returnedMap.put('msg', 'Product Sync Batch processing failed ');
        } finally {
            logger.flush();
        }

        return JSON.serialize(returnedMap);
    }
    public Map<String, String> getCountryISOCodeAndCountryMap() {
        Picklist p = new Picklist(Product2.DR_Product_Country_Origin__c);
        return p.getEntriesMap();
    }

    public Map<String, String> getCountryAndCountryISOCodeMap() {
        Picklist p = new Picklist(Product2.DR_Product_Country_Origin__c);
        return p.getLabelToValueMap();
    }
}