src/main/default/objects/DR_Transaction_Payment__c/DR_Transaction_Payment__c.object-meta.xml
<CustomObject>
    <description>Store transaction-related information</description>
    <label>Digital River Transaction Payment</label>
    <nameField>
        <displayFormat>DRTP-{0000}</displayFormat>
        <label>DR Transaction Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital River Transaction Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/DR_Transaction_Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account of the user that created this transaction payment.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Digital River Transaction Payments</relationshipLabel>
    <relationshipName>Digital_River_Transaction_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Actual transaction amount.</description>
    <inlineHelpText>Actual transaction amount.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <description>Last four digit of card.</description>
    <label>Card Number</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <description>Type of card like Visa, Master</description>
    <label>Card Type</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Cart__c.field-meta.xml
<CustomField>
    <fullName>Cart__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>References the cart this payment was applied to.</description>
    <label>Cart</label>
    <referenceTo>WebCart</referenceTo>
    <relationshipLabel>Digital River Transaction Payments</relationshipLabel>
    <relationshipName>Digital_River_Transaction_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact of the user that created this transaction payment.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Digital River Transaction Payments</relationshipLabel>
    <relationshipName>Digital_River_Transaction_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/CurrencyISOCode__c.field-meta.xml
<CustomField>
    <fullName>CurrencyISOCode__c</fullName>
    <description>Currency Code for this transaction like USD, GBP</description>
    <label>CurrencyISOCode</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <description>Display name for payment.</description>
    <inlineHelpText>Display name for payment.</inlineHelpText>
    <label>Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>References the order this payment was applied to.</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Digital River Transaction Payments</relationshipLabel>
    <relationshipName>Digital_River_Transaction_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Payment_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Payment_Instructions__c</fullName>
    <description>Payment instructions eg in case or wire transfer it can we bank information</description>
    <label>Payment Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <description>The Payment type of the payment, e.g.  Credit Card,PayPal etc.</description>
    <label>Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Tokenized form of the payment</description>
    <label>Token</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>Type of the transaction, e.g. for a credit card this might be AUTH, CAPTURE, or AUTH+CAPTURE. This is provider specific.</description>
    <label>Transaction Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User that created this transaction payment.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Digital_River_Transaction_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/classes/service/DRB2B_TransactionPaymentService.cls
public without sharing class DRB2B_TransactionPaymentService {
    private static final DCM_Logger logger = DCM_Logger.getInstance(
        DRB2B_Constants.Module.DigitalRiver_TRANSACTION_PAYMENTS
    );

    @TestVisible
    private static DRB2B_TransactionPaymentSelector transactionPaymentSelector = new DRB2B_TransactionPaymentSelector();

    public static Boolean isGuestUser = Auth.CommunitiesUtil.isGuestUser();

    public static string responseBody = '';

    public String getSourceInfo(String sourceType) {
        String paymentInstruction = '';
        if (sourceType == 'wireTransfer') {
            paymentInstruction = responseBody.substringBetween('"wireTransfer":', '"session"');
        } else if (sourceType == 'konbini') {
            paymentInstruction = responseBody.substringBetween('"konbini":', '"session"');
        }
        if (paymentInstruction != null) {
            paymentInstruction = paymentInstruction.removeEnd('}],');
        }
        return paymentInstruction;
    }

    public Boolean deleteDRTransactionPayment(String sourceId) {
        Boolean finalResult = false;
        try {
            List<DR_Transaction_Payment__c> transactionPaymentList = transactionPaymentSelector.getBySourceId(sourceId);
            if (transactionPaymentList.size() > 0) {
                DmlManager.deleteAsUser(transactionPaymentList);
                finalResult = true;
            } else {
                logger.Info('Did not found any DR Transaction Payments record with this source Id.');
            }
        } catch (Exception e) {
            logger.error(e);
        } finally {
            logger.flush();
        }
        return finalResult;
    }

    public DR_Transaction_Payment__c createTrasactionPaymentRecord(
        Order sfOrder,
        DRB2B_CreateCheckoutResponseModel.Source sourceInfo,
        String cartId
    ) {
        logger.debug('Inside createTrasactionPaymentRecord input');
        DR_Transaction_Payment__c transactionPaymentObj = new DR_Transaction_Payment__c();
        transactionPaymentObj.Amount__c = sourceInfo.amount;
        if (sourceInfo.type != 'customerCredit') {
            String label = System.label.DR_PaymentMethod + sourceInfo.type;
            String value = DRB2B_StoredPayments.getLabel(label);
            logger.debug('value in transaction creation record ' + value);
            Map<String, Object> mapOfCustomData = (Map<String, Object>) JSON.deserializeUntyped(value);
            if (mapOfCustomData.containsKey('value')) {
                if (String.isNotBlank(String.valueOf(mapOfCustomData.get('value')))) {
                    transactionPaymentObj.Display_Name__c = String.valueOf(mapOfCustomData.get('value'));
                }
            }
        }

        if (sourceInfo.type == 'creditCard') {
            transactionPaymentObj.Card_Number__c = 'xxxx-xxxx-xxxx-' + sourceInfo.creditCard.lastFourDigits;
            transactionPaymentObj.Card_Type__c = sourceInfo.creditCard.brand;
        } else if (sourceInfo.type == 'wireTransfer' || sourceInfo.type == 'konbini') {
            transactionPaymentObj.Payment_Instructions__c = getSourceInfo(sourceInfo.type);
        }
        transactionPaymentObj.Payment_Method__c = sourceInfo.type;
        transactionPaymentObj.Token__c = sourceInfo.id;
        transactionPaymentObj.CurrencyISOCode__c = sourceInfo.drCurrency;
        transactionPaymentObj.Cart__c = cartId;
        transactionPaymentObj.Transaction_Type__c = 'AUTH'; // this will be AUTH and after funds are captured it will be CAPTURE
        if (sfOrder != null) {
            transactionPaymentObj.Contact__c = sfOrder.CreatedBy.ContactId;
            transactionPaymentObj.User__c = sfOrder.CreatedById;
            transactionPaymentObj.Order__c = sfOrder.Id;
            transactionPaymentObj.Account__c = sfOrder.AccountId;
        }
        return transactionPaymentObj;
    }
}