src/main/default/objects/DR_Transaction_Payment__c/DR_Transaction_Payment__c.object-meta.xml
<CustomObject>
    <description>Store transaction-related information</description>
    <label>Digital River Transaction Payment</label>
    <nameField>
        <displayFormat>DRTP-{0000}</displayFormat>
        <label>DR Transaction Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital River Transaction Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/DR_Transaction_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Actual transaction amount.</description>
    <inlineHelpText>Actual transaction amount.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <description>Last four digit of card.</description>
    <label>Card Number</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <description>Type of card like Visa, Master</description>
    <label>Card Type</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Cart__c.field-meta.xml
<CustomField>
    <fullName>Cart__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>References the cart this payment was applied to.</description>
    <label>Cart</label>
    <referenceTo>WebCart</referenceTo>
    <relationshipLabel>Digital River Transaction Payments</relationshipLabel>
    <relationshipName>Digital_River_Transaction_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <description>Display name for payment.</description>
    <inlineHelpText>Display name for payment.</inlineHelpText>
    <label>Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>References the order this payment was applied to.</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Digital River Transaction Payments</relationshipLabel>
    <relationshipName>Digital_River_Transaction_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Payment_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Payment_Instructions__c</fullName>
    <description>Payment instructions eg in case or wire transfer it can we bank information</description>
    <label>Payment Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <description>The Payment type of the payment, e.g.  Credit Card,PayPal etc.</description>
    <label>Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Tokenized form of the payment</description>
    <label>Token</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>Type of the transaction, e.g. for a credit card this might be AUTH, CAPTURE, or AUTH+CAPTURE. This is provider specific.</description>
    <label>Transaction Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/selector/DRB2B_TransactionPaymentSelector.cls
public without sharing class DRB2B_TransactionPaymentSelector {
    public List<DR_Transaction_Payment__c> getByOrderId(String orderId) {
        return (List<DR_Transaction_Payment__c>) new DCM_Query(DR_Transaction_Payment__c.sObjectType)
            .selectField(DR_Transaction_Payment__c.Id)
            .selectField(DR_Transaction_Payment__c.Card_Number__c)
            .selectField(DR_Transaction_Payment__c.Card_Type__c)
            .selectField(DR_Transaction_Payment__c.Order__c)
            .selectField(DR_Transaction_Payment__c.Payment_Instructions__c)
            .selectField(DR_Transaction_Payment__c.Payment_Method__c)
            .selectField(DR_Transaction_Payment__c.Transaction_Type__c)
            .selectField(DR_Transaction_Payment__c.Token__c)
            .selectField(DR_Transaction_Payment__c.Amount__c)
            .selectField(DR_Transaction_Payment__c.Display_Name__c)
            .addConditionEq('Order__c', orderId)
            .orderBy('DR_Transaction_Payment__c.Name', 'ASC')
            .run();
    }

    public List<DR_Transaction_Payment__c> getByCartId(String cartId) {
        return (List<DR_Transaction_Payment__c>) new DCM_Query(DR_Transaction_Payment__c.sObjectType)
            .selectField(DR_Transaction_Payment__c.Id)
            .selectField(DR_Transaction_Payment__c.Card_Number__c)
            .selectField(DR_Transaction_Payment__c.Card_Type__c)
            .selectField(DR_Transaction_Payment__c.Order__c)
            .selectField(DR_Transaction_Payment__c.Payment_Instructions__c)
            .selectField(DR_Transaction_Payment__c.Payment_Method__c)
            .selectField(DR_Transaction_Payment__c.Transaction_Type__c)
            .selectField(DR_Transaction_Payment__c.Token__c)
            .selectField(DR_Transaction_Payment__c.Amount__c)
            .selectField(DR_Transaction_Payment__c.Display_Name__c)
            .addConditionEq('Cart__c', cartId)
            .orderBy('DR_Transaction_Payment__c.Name', 'ASC')
            .run();
    }

    public List<DR_Transaction_Payment__c> getBySourceId(String sourceId) {
        return (List<DR_Transaction_Payment__c>) new DCM_Query(DR_Transaction_Payment__c.sObjectType)
            .selectField(DR_Transaction_Payment__c.Id)
            .selectField(DR_Transaction_Payment__c.Card_Number__c)
            .selectField(DR_Transaction_Payment__c.Card_Type__c)
            .selectField(DR_Transaction_Payment__c.Order__c)
            .selectField(DR_Transaction_Payment__c.Payment_Instructions__c)
            .selectField(DR_Transaction_Payment__c.Payment_Method__c)
            .selectField(DR_Transaction_Payment__c.Transaction_Type__c)
            .selectField(DR_Transaction_Payment__c.Token__c)
            .addConditionEq('Token__c', sourceId)
            .run();
    }

    public List<DR_Transaction_Payment__c> getBycartId(String cartId, List<String> fields) {
        return (List<DR_Transaction_Payment__c>) new DCM_Query(DR_Transaction_Payment__c.sObjectType)
            .selectFields(new List<String>(fields))
            .addConditionEq('Cart__c', cartId)
            .run();
    }
}