src/main/default/objects/DR_Transaction_Payment__c/DR_Transaction_Payment__c.object-meta.xml
<CustomObject>
    <description>Store transaction-related information</description>
    <label>Digital River Transaction Payment</label>
    <nameField>
        <displayFormat>DRTP-{0000}</displayFormat>
        <label>DR Transaction Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital River Transaction Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/DR_Transaction_Payment__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Tokenized form of the payment</description>
    <label>Token</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/WebCart/fields/Buyer_Email__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Email__c</fullName>
    <description>Used to capture buyer email on checkout flow.</description>
    <label>Buyer Email</label>
    <type>Email</type>
</CustomField>

src/main/default/objects/WebCart/fields/Buyer_Name__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Name__c</fullName>
    <description>Used to capture buyer name on checkout flow.</description>
    <label>Buyer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/WebCart/fields/Buyer_Phone__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Phone__c</fullName>
    <description>Used to capture buyer phone on checkout flow.</description>
    <label>Buyer Phone</label>
    <type>Phone</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Amount_Remaining_to_be_Contributed__c.field-meta.xml
<CustomField>
    <fullName>DR_Amount_Remaining_to_be_Contributed__c</fullName>
    <description>Remaining amount after store credit contribution.</description>
    <inlineHelpText>Remaining amount after store credit contribution.</inlineHelpText>
    <label>DR Amount Remaining to be Contributed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Checkout_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_Checkout_Id__c</fullName>
    <description>The Digital River Checkout Identifier</description>
    <inlineHelpText>The Digital River Checkout Identifier</inlineHelpText>
    <label>DR Checkout Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Checkout_Type__c.field-meta.xml
<CustomField>
    <fullName>DR_Checkout_Type__c</fullName>
    <description>The type of products stored in the Cart: Non-Digital, Digital</description>
    <inlineHelpText>The type of products stored in the Cart: Non-Digital, Digital</inlineHelpText>
    <label>DR Checkout Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Non-Digital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Payment_Session_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_Payment_Session_Id__c</fullName>
    <description>The Digital River Payment Session Identifier</description>
    <inlineHelpText>The Digital River Payment Session Identifier</inlineHelpText>
    <label>DR Payment Session Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/WebCart/fields/DR_Source_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_Source_Id__c</fullName>
    <description>Stores a source Id attached to a checkout record</description>
    <inlineHelpText>Stores a source Id attached to a checkout record</inlineHelpText>
    <label>DR Source Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/WebCart/fields/Recurring_Line_Item_Count__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Line_Item_Count__c</fullName>
    <description>Indicates the Number of Recurring Line Items in this Cart</description>
    <inlineHelpText>Indicates the Number of Recurring Line Items in this Cart</inlineHelpText>
    <label>Recurring Line Item Count</label>
    <summaryFilterItems>
        <field>CartItem.Recurring_Line_Item__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>CartItem.CartId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/classes/DRB2B_DropinController.cls
public without sharing class DRB2B_DropinController {
    @TestVisible
    private static final DRB2B_CartSelector cartSelector = new DRB2B_CartSelector();

    @TestVisible
    private static final DRB2B_CartService cartService = new DRB2B_CartService();

    @TestVisible
    private static final DCM_Logger logger = DCM_Logger.getInstance(DRB2B_Constants.Module.CHECKOUT_FLOW);

    private static final Set<String> CART_FIELDS = new Set<String>{
        'digitalriverv3__DR_Payment_Session_Id__c',
        'digitalriverv3__DR_Checkout_Id__c',
        'digitalriverv3__DR_Amount_Contributed__c',
        'digitalriverv3__DR_Amount_Remaining_to_be_Contributed__c',
        'digitalriverv3__Recurring_Line_Item_Count__c'
    };

    @TestVisible
    private static DRB2B_RequestService requestService = new DRB2B_RequestService();

    public static Boolean isGuestUser = Auth.CommunitiesUtil.isGuestUser();

    @AuraEnabled
    public static Map<String, object> getCart(Id cartId) {
        Map<String, object> result = new Map<String, object>();
        try {
            Webcart cart = cartSelector.getById(
                cartId,
                new Set<String>{
                    'DR_Payment_Session_Id__c',
                    'Buyer_Email__c',
                    'BillingAddress',
                    'Buyer_Phone__c',
                    'Buyer_Name__c',
                    'DR_Checkout_Id__c',
                    'DR_Checkout_Type__c',
                    'GrandTotalAmount',
                    'Recurring_Line_Item_Count__c',
                    'DR_Amount_Remaining_to_be_Contributed__c',
                    'DR_Source_Id__c'
                }
            );
            result.put('cart', cartService.getCartAsWrapper(cart));
            result.put('isCountryStateEnabled', DRB2B_Utility.isCountryStateEnabled());
            logger.debug('dropin controller get cart method call' + result);
        } catch (Exception e) {
            logger.error(e);
            throw new AuraHandledException(e.getMessage());
        } finally {
            logger.flush();
        }
        return result;
    }

    @AuraEnabled
    public static Boolean deattachAllSourcesFromCheckout(String inputData) {
        Boolean isSuccess = false;
        try {
            Map<String, Object> data = (Map<String, Object>) json.deserializeUntyped(inputData);
            Id cartId = (Id) data.get('cartId');
            DRB2B_CartSelector cartSelector = new DRB2B_CartSelector();
            WebCart cart = cartSelector.getById(cartId, CART_FIELDS);
            String checkoutId = cart.digitalriverv3__DR_Checkout_Id__c;
            DRB2B_TransactionPaymentSelector paymentSelector = new DRB2B_TransactionPaymentSelector();
            List<DR_Transaction_Payment__c> paymentList = paymentSelector.getBycartId(
                cartId,
                new List<String>{ 'Token__c', 'Id' }
            );
            list<DR_Transaction_Payment__c> deletePayamentRecList = new List<DR_Transaction_Payment__c>();
            logger.info('drb2b dropin controller paymentList' + JSON.serialize(paymentList));
            logger.info('drb2b dropin controller deletePayamentRecList' + JSON.serialize(deletePayamentRecList));
            if (!paymentList.isEmpty()) {
                for (DR_Transaction_Payment__c payment : paymentList) {
                    DCM_HttpClient.Response response = requestService.deletePaymentSourceFromCheckout(
                            checkoutId,
                            payment.Token__c,
                            cartId
                        )
                        .fetch();
                    if (response.getStatusCode() == 204) {
                        deletePayamentRecList.add(payment);
                        isSuccess = true;
                    } else {
                        isSuccess = false;
                    }
                }
                if(!Test.isRunningTest()){
                    DRB2B_CustomerCreditService.getAmountRemainingforCheckout(inputData);
                }
                logger.info('Delete DR payment transaction record' + JSON.serialize(deletePayamentRecList));
                if (!deletePayamentRecList.isEmpty()) {
                    if (!isGuestUser) {
                        DmlManager.deleteAsUser(deletePayamentRecList);
                    } else {
                        DmlManager.deleteAsSystem(deletePayamentRecList);
                    }
                }
            } else {
                isSuccess = true;
            }
        } catch (exception e) {
            logger.error(e);
            throw new AuraHandledException(e.getMessage());
        } finally {
            logger.flush();
        }

        return isSuccess;
    }
}