src/main/default/objects/OrderItem/fields/DR_Cancelled_Quantity__c.field-meta.xml
<CustomField>
    <fullName>DR_Cancelled_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Cancelled Line Item Quantity</description>
    <inlineHelpText>Cancelled Line Item Quantity</inlineHelpText>
    <label>DR Cancelled Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/OrderItem/fields/DR_Fulfilled_Quantity__c.field-meta.xml
<CustomField>
    <fullName>DR_Fulfilled_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Fulfilled Line Item Quantity</description>
    <inlineHelpText>Fulfilled Line Item Quantity</inlineHelpText>
    <label>DR Fulfilled Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/OrderItem/fields/DR_Open_Quantity__c.field-meta.xml
<CustomField>
    <fullName>DR_Open_Quantity__c</fullName>
    <description>Line Item Quantity Available for Fulfillment or Cancellation</description>
    <inlineHelpText>Line Item Quantity Available for Fulfillment or Cancellation</inlineHelpText>
    <label>DR Open Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/OrderItem/fields/DR_Order_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_Order_Item_Id__c</fullName>
    <label>DR Order Item Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/OrderItem/fields/DR_Order_Item_State__c.field-meta.xml
<CustomField>
    <fullName>DR_Order_Item_State__c</fullName>
    <description>Order item State at DR end</description>
    <inlineHelpText>Order item State at DR end</inlineHelpText>
    <label>Digital River Order Item State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>created</fullName>
            </value>
            <value>
                <fullName>fulfilled</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>partially_fulfilled</fullName>
            </value>
            <value>
                <fullName>partially_cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/classes/selector/DRB2B_OrderItemSelector.cls
public with sharing class DRB2B_OrderItemSelector {

    public List<OrderItem> getByOrderIdsAndOrderItemType(List<Id> orderIds, String orderItemType) {
        return (List<OrderItem>) new DCM_Query(OrderItem.sObjectType)
            .selectField(OrderItem.Id)
            .selectField(OrderItem.DR_Order_Item_State__c)
            .selectField(OrderItem.DR_Order_Item_Id__c)
            .selectField(OrderItem.Quantity)
            .selectField(OrderItem.DR_Open_Quantity__c)
            .selectField(OrderItem.DR_Fulfilled_Quantity__c)
            .selectField(OrderItem.DR_Cancelled_Quantity__c)
            .selectField(OrderItem.OrderId)
            .addConditionIn('OrderId', orderIds)
            .addConditionEq('Type', orderItemType)
            .run();
    }

    public List<OrderItem> getByOrderIdAndType(String orderId, String orderItemType, Set<String> fields) {
        return (List<OrderItem>) new DCM_Query(OrderItem.sObjectType)
            .selectFields(new List<String>(fields))
            .addConditionEq('OrderId', orderId)
            .addConditionEq('Type', orderItemType)
            .switchToConjunction()
            .run();
    }

    public List<OrderItem> getQuantityFieldsByIds(Set<Id> orderItemIds) {
        return (List<OrderItem>) new DCM_Query(OrderItem.sObjectType)
            .selectField(OrderItem.Id)
            .selectField(OrderItem.Quantity)
            .selectField(OrderItem.DR_Open_Quantity__c)
            .selectField(OrderItem.DR_Fulfilled_Quantity__c)
            .selectField(OrderItem.DR_Cancelled_Quantity__c)
            .addConditionEq('Type', 'Order Product')
            .addConditionIn('Id', orderItemIds)
            .debug()
            .run();
    }

    public List<OrderItem> getQuantityFieldsByIds(Set<String> orderItemIds) {
        // Convert Set<String> to Set<Id>
        return getQuantityFieldsByIds(new Set<Id>((List<Id>) new List<String>(orderItemIds)));
    }

    public List<OrderItem> getDRFieldsByOrderItemIds(Set<Id> orderItemIds) {
        return (List<OrderItem>) new DCM_Query(OrderItem.sObjectType)
            .selectField(OrderItem.Id)
            .selectField(OrderItem.DR_Order_Item_Id__c)
            .selectField(OrderItem.Quantity)
            .selectField(OrderItem.OrderId)
            .selectField(OrderItem.DR_Open_Quantity__c)
            .selectField(OrderItem.DR_Fulfilled_Quantity__c)
            .selectField(OrderItem.DR_Cancelled_Quantity__c)
            .addConditionEq('Type', 'Order Product')
            .addConditionIn('Id', orderItemIds)
            .debug()
            .run();
    }

    public List<OrderItem> getDRFieldsByOrderItemIds(Set<String> orderItemIds) {
        return getDRFieldsByOrderItemIds(new Set<Id>((List<Id>) new List<String>(orderItemIds)));
    }

    public List<OrderItem> getQuantityFieldsByOrderIds(Set<Id> orderIds) {
        return (List<OrderItem>) new DCM_Query(OrderItem.sObjectType)
            .selectField(OrderItem.Id)
            .selectField(OrderItem.OrderId)
            .selectField(OrderItem.Quantity)
            .selectField(OrderItem.DR_Open_Quantity__c)
            .selectField(OrderItem.DR_Fulfilled_Quantity__c)
            .selectField(OrderItem.DR_Cancelled_Quantity__c)
            .addConditionEq('Type', 'Order Product')
            .addConditionIn('OrderId', orderIds)
            .debug()
            .run();
    }

}