src/main/InvoiceCreditMemo/objects/Order/fields/DR_Fraud_State__c.field-meta.xml
<CustomField>
    <fullName>DR_Fraud_State__c</fullName>
    <label>Digital River Fraud State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>blocked</fullName>
            </value>
            <value>
                <fullName>in_review</fullName>
            </value>
            <value>
                <fullName>passed</fullName>
            </value>
            <value>
                <fullName>review_opened</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/InvoiceCreditMemo/objects/Order/fields/DR_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_Order_Id__c</fullName>
    <description>DR order Id</description>
    <externalId>true</externalId>
    <label>Digital River Order Id</label>
    <length>128</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/InvoiceCreditMemo/objects/Order/fields/DR_Order_State__c.field-meta.xml
<CustomField>
    <fullName>DR_Order_State__c</fullName>
    <description>Digital River order states</description>
    <inlineHelpText>Digital River order states</inlineHelpText>
    <label>Digital River Order State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>pending_payment</fullName>
            </value>
            <value>
                <fullName>in_review</fullName>
            </value>
            <value>
                <fullName>accepted</fullName>
            </value>
            <value>
                <fullName>blocked</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>fulfilled</fullName>
            </value>
            <value>
                <fullName>complete</fullName>
            </value>
            <value>
                <fullName>returned</fullName>
            </value>
            <value>
                <fullName>salesforce_failure</fullName>
            </value> <value>
                <fullName>cancelled_by_sf</fullName>
            </value>
            <value>
                <fullName>cancelled_by_dr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/InvoiceCreditMemo/objects/Order/fields/SF_Order_Failure_Reason__c.field-meta.xml
<CustomField>
    <fullName>SF_Order_Failure_Reason__c</fullName>
    <label>SF Order Failure Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/classes/selector/DRB2B_OrderSelector.cls
public with sharing class DRB2B_OrderSelector {
    public List<Order> getByDROrderId(String drOrderId) {
        return (List<Order>) new DCM_Query(Order.sObjectType)
            .selectField(Order.Id)
            .selectField(Order.DR_Order_Id__c)
            .selectField(Order.DR_Order_State__c)
            .selectField(Order.DR_Fraud_State__c)
            .addConditionEq('DR_Order_Id__c', drOrderId)
            .run();
    }

    public List<Order> getDrOrderInfoBySfOrderId(String orderId) {
        return (List<Order>) new DCM_Query(Order.sObjectType)
            .selectField(Order.Id)
            .selectField(Order.DR_Order_Id__c)
            .selectField(Order.DR_Order_State__c)
            .selectField(Order.DR_Fraud_State__c)
            .addConditionEq('Id', orderId)
            .run();
    }

    public List<Order> getDrOrderInfoBySfOrderIds(Set<Id> orderIds) {
        return (List<Order>) new DCM_Query(Order.sObjectType)
            .selectField(Order.Id)
            .selectField(Order.DR_Order_Id__c)
            .selectField(Order.DR_Order_State__c)
            .selectField(Order.DR_Fraud_State__c)
            .addConditionIn('Id', orderIds)
            .debug()
            .run();
    }

    public List<Order> getByDrOrderIds(List<String> drOrderIds) {
        return (List<Order>) new DCM_Query(Order.sObjectType)
            .selectField(Order.Id)
            .selectField(Order.DR_Order_Id__c)
            .addConditionIn('DR_Order_Id__c', drOrderIds)
            .debug()
            .run();
    }

    public List<Order> getBySfOrderNumber(List<String> sfOrderNumbers) {
        return (List<Order>) new DCM_Query(Order.sObjectType)
            .selectField(Order.Id)
            .selectField(Order.DR_Order_Id__c)
            .selectField(Order.OrderNumber)
            .selectField(Order.DR_Order_State__c)
            .selectField(Order.DR_Fraud_State__c)
            .selectField(Order.SF_Order_Failure_Reason__c)
            .addConditionIn('OrderNumber', sfOrderNumbers)
            .debug()
            .run();
    }

}