src/main/default/objects/CartTax/fields/DR_Regulatory_Fee__c.field-meta.xml
<CustomField>
    <fullName>DR_Regulatory_Fee__c</fullName>
    <description>Regulatory Fees collected to address the manufacture, use, recovery, and recycling of Consumer Electronics products throughout the world.</description>
    <inlineHelpText>Regulatory Fees collected to address the manufacture, use, recovery, and recycling of Consumer Electronics products throughout the world.</inlineHelpText>
    <label>DR Regulatory Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/DR_Regulatory_Fee__c/DR_Regulatory_Fee__c.object-meta.xml
<CustomObject>
    <description>This object is used to capture Line Level Regulatory Fee information</description>
    <label>Digital River Regulatory Fee</label>
    <nameField>
        <displayFormat>DR-Reg-Fee-{000000}</displayFormat>
        <label>DR Regulatory Fee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital River Regulatory Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/DR_Transaction_Payment__c/DR_Transaction_Payment__c.object-meta.xml
<CustomObject>
    <description>Store transaction-related information</description>
    <label>Digital River Transaction Payment</label>
    <nameField>
        <displayFormat>DRTP-{0000}</displayFormat>
        <label>DR Transaction Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital River Transaction Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/DR_Transaction_Payment__c/fields/Cart__c.field-meta.xml
<CustomField>
    <fullName>Cart__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>References the cart this payment was applied to.</description>
    <label>Cart</label>
    <referenceTo>WebCart</referenceTo>
    <relationshipLabel>Digital River Transaction Payments</relationshipLabel>
    <relationshipName>Digital_River_Transaction_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/checkout/classes/triggerHandler/DRB2B_CancelCheckoutSessionTrigHdlr.cls
public with sharing class DRB2B_CancelCheckoutSessionTrigHdlr implements TriggerHandler.Logic {
    private static final DCM_Logger LOGGER = DCM_Logger.getInstance(DRB2B_Constants.Module.CHECKOUT_FLOW);

    @TestVisible
    private DRB2B_CartItemService cartItemService = new DRB2B_CartItemService();

    @TestVisible
    private DRB2B_RegulatoryFeeSelector feeSelector = new DRB2B_RegulatoryFeeSelector();

    @TestVisible
    private static DRB2B_CartService cartService = new DRB2B_CartService();

    public void execute(List<SObject> records, TriggerContext ctx) {
        LOGGER.info('DRB2B_CancelCheckoutSessionTrigHdlr Cancel Trigger');
        try {
            Set<Id> checkoutCancelledCartIds = new Set<Id>();
            for (CartCheckoutSession cartCheckoutSess : (List<CartCheckoutSession>) records) {
                if (
                    cartCheckoutSess.IsArchived &&
                    ctx.isChangedTo(cartCheckoutSess, CartCheckoutSession.IsArchived, true)
                ) {
                    checkoutCancelledCartIds.add(cartCheckoutSess.WebCartId);
                }
            }

            if (!checkoutCancelledCartIds.isEmpty()) {
                //Update Total Price on Cart Items to remove Landed Costs and Regulatory Fees
                cartItemService.removeLandedCostsAndRegulatoryFeesFromTotalPrice(checkoutCancelledCartIds);
                Set<String> cartIds = (Set<String>) JSON.deserialize(
                    JSON.serialize(checkoutCancelledCartIds),
                    Set<String>.class
                );
                cartService.clearAddress(cartIds);
                /**
                 * Whenever a Shopper cancels an existing checkout, then we need to remove data related to DR from cart
                 */
                cartService.clearDataRelatedToDr(cartIds);
                //Delete transaction payment details
                List<DR_Transaction_Payment__c> transactionDetails = [
                    SELECT Id
                    FROM DR_Transaction_Payment__c
                    WHERE Cart__c IN :cartIds
                ];
                if (!transactionDetails.isEmpty()) {
                    DmlManager.deleteAsUser(transactionDetails);
                }
            }
            Set<Id> cartItemIds = cartItemService.getCartItemIdByCart(checkoutCancelledCartIds);
            // Delete Taxes and fee
            List<CartTax> taxes = [SELECT Id FROM CartTax WHERE CartItemId IN :cartItemIds];
            if (!taxes.isEmpty()) {
                DmlManager.deleteAsUser(taxes);
            }
            list<DR_Regulatory_Fee__c> fee = feeSelector.getByCartItemId(new Set<String>{ 'Id' }, cartItemIds);

            if (!fee.isEmpty()) {
                LOGGER.info('DRB2B_CancelCheckoutSessionTrigHdlr Delete Fee' + JSON.serialize(fee));
                DmlManager.deleteAsUser(fee);
            }
        } catch (exception e) {
            LOGGER.error(e);
        } finally {
            LOGGER.flush();
        }
    }
}