src/main/default/objects/DR_Fulfillment__c/DR_Fulfillment__c.object-meta.xml
<CustomObject>
    <description>Store information regarding fulfillment</description>
    <label>Digital River Fulfillment</label>
    <nameField>
        <displayFormat>Fulfillment-{000000}</displayFormat>
        <label>DR Fulfillment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital River Fulfillments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/DR_Fulfillment__c/fields/DR_Fulfillment_Status__c.field-meta.xml
<CustomField>
    <fullName>DR_Fulfillment_Status__c</fullName>
    <description>Open - Fulfillment request has to be sent for Order Item(s)
Reprocess - Previous Attempt to send Fulfillment Request to DR failed. Will be reprocessed in next run
Completed - Fulfillment process is completed for this Order.
Failed - Failed Processing this Order after multiple attempts.</description>
    <label>Digital River Fulfillment Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Reprocess</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/DR_Fulfillment__c/fields/DR_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_Order_Id__c</fullName>
    <description>Digital River Order ID</description>
    <externalId>true</externalId>
    <label>Digital River Order Id</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Fulfillment__c/fields/DR_Order_State__c.field-meta.xml
<CustomField>
    <fullName>DR_Order_State__c</fullName>
    <description>Digital River Order State</description>
    <label>Digital River Order State</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Fulfillment__c/fields/Eligible_For_Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>Eligible_For_Fulfillment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is fulfillment record eligible for fulfillment</description>
    <label>Eligible For Fulfillment</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/DR_Fulfillment__c/fields/Is_Fulfillment_Completed__c.field-meta.xml
<CustomField>
    <fullName>Is_Fulfillment_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is fulfillment is completed</description>
    <label>Is Fulfillment Completed</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/DR_Fulfillment__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Information about the Success or Failure of Posting fulfillment to DR</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/DR_Fulfillment__c/fields/Order_Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Order_Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the Order is cancelled at DR. This will be set to true when order.cancelled event is received by SF</description>
    <inlineHelpText>Indicates if the Order is cancelled at DR. This will be set to true when order.cancelled event is received by SF</inlineHelpText>
    <label>Order Cancelled</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/DR_Fulfillment__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <description>Salesforce order Id</description>
    <label>Order Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/selector/DRB2B_FulfillmentSelector.cls
public with sharing class DRB2B_FulfillmentSelector {
    public List<DR_Fulfillment__c> getByDROrderId(String drOrderId) {
        return (List<DR_Fulfillment__c>) new DCM_Query(DR_Fulfillment__c.sObjectType)
            .selectField(DR_Fulfillment__c.Id)
            .selectField(DR_Fulfillment__c.DR_Order_Id__c)
            .selectField(DR_Fulfillment__c.DR_Order_State__c)
            .selectField(DR_Fulfillment__c.Order_Id__c)
            .selectField(DR_Fulfillment__c.DR_Fulfillment_Status__c)
            .selectField(DR_Fulfillment__c.Is_Fulfillment_Completed__c)
            .selectField(DR_Fulfillment__c.Message__c)
            .selectField(DR_Fulfillment__c.Eligible_For_Fulfillment__c)
            .selectField(DR_Fulfillment__c.Order_Cancelled__c)
            .addConditionEq('DR_Order_Id__c', drOrderId)
            .run();
    }

    public List<DR_Fulfillment__c> getByDROrderIds(List<String> drOrderIds) {
        return (List<DR_Fulfillment__c>) new DCM_Query(DR_Fulfillment__c.sObjectType)
            .selectField(DR_Fulfillment__c.Id)
            .selectField(DR_Fulfillment__c.DR_Order_Id__c)
            .selectField(DR_Fulfillment__c.DR_Order_State__c)
            .selectField(DR_Fulfillment__c.Order_Id__c)
            .selectField(DR_Fulfillment__c.DR_Fulfillment_Status__c)
            .selectField(DR_Fulfillment__c.Is_Fulfillment_Completed__c)
            .selectField(DR_Fulfillment__c.Message__c)
            .selectField(DR_Fulfillment__c.Eligible_For_Fulfillment__c)
            .selectField(DR_Fulfillment__c.Order_Cancelled__c)
            .addConditionIn('DR_Order_Id__c', drOrderIds)
            .setLimit(2000)
            .run();
    }

    public List<DR_Fulfillment__c> getByDROrderIds(Set<String> drOrderIds) {
        return getByDROrderIds(new List<String>(drOrderIds));
    }

}