src/main/default/objects/DR_Fulfillment__c/DR_Fulfillment__c.object-meta.xml
<CustomObject>
    <description>Store information regarding fulfillment</description>
    <label>Digital River Fulfillment</label>
    <nameField>
        <displayFormat>Fulfillment-{000000}</displayFormat>
        <label>DR Fulfillment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital River Fulfillments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/DR_Fulfillment__c/fields/DR_Fulfillment_Status__c.field-meta.xml
<CustomField>
    <fullName>DR_Fulfillment_Status__c</fullName>
    <description>Open - Fulfillment request has to be sent for Order Item(s)
Reprocess - Previous Attempt to send Fulfillment Request to DR failed. Will be reprocessed in next run
Completed - Fulfillment process is completed for this Order.
Failed - Failed Processing this Order after multiple attempts.</description>
    <label>Digital River Fulfillment Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Reprocess</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/DR_Fulfillment__c/fields/DR_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_Order_Id__c</fullName>
    <description>Digital River Order ID</description>
    <externalId>true</externalId>
    <label>Digital River Order Id</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Fulfillment__c/fields/DR_Order_State__c.field-meta.xml
<CustomField>
    <fullName>DR_Order_State__c</fullName>
    <description>Digital River Order State</description>
    <label>Digital River Order State</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Fulfillment__c/fields/Eligible_For_Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>Eligible_For_Fulfillment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is fulfillment record eligible for fulfillment</description>
    <label>Eligible For Fulfillment</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/DR_Fulfillment__c/fields/Is_Fulfillment_Completed__c.field-meta.xml
<CustomField>
    <fullName>Is_Fulfillment_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is fulfillment is completed</description>
    <label>Is Fulfillment Completed</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/DR_Fulfillment__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Information about the Success or Failure of Posting fulfillment to DR</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/DR_Fulfillment__c/fields/Order_Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Order_Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the Order is cancelled at DR. This will be set to true when order.cancelled event is received by SF</description>
    <inlineHelpText>Indicates if the Order is cancelled at DR. This will be set to true when order.cancelled event is received by SF</inlineHelpText>
    <label>Order Cancelled</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/DR_Fulfillment__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <description>Salesforce order Id</description>
    <label>Order Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Fulfillment__c/fields/Retry_Attempts_Made__c.field-meta.xml
<CustomField>
    <fullName>Retry_Attempts_Made__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of Retry Attempts made for sending Fulfillment</description>
    <inlineHelpText>Number of Retry Attempts made for sending Fulfillment</inlineHelpText>
    <label>Retry Attempts Made</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/DR_Fulfillment_Request_Log__c/DR_Fulfillment_Request_Log__c.object-meta.xml
<CustomObject>
    <description>Capture Fulfillment requests sent from Client application</description>
    <label>DR Fulfillment Request Log</label>
    <nameField>
        <displayFormat>DR-Fulfillment-Req-{000000}</displayFormat>
        <label>DR Fulfillment Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DR Fulfillment Request Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/DR_Fulfillment_Request_Log__c/fields/Cancel_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Specifies Order Item Quantity to Cancel</description>
    <inlineHelpText>Specifies Order Item Quantity to Cancel</inlineHelpText>
    <label>Cancel Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/DR_Fulfillment_Request_Log__c/fields/DR_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_Order_Id__c</fullName>
    <description>The Digital River Order Identifier</description>
    <inlineHelpText>The Digital River Order Identifier</inlineHelpText>
    <label>DR Order Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Fulfillment_Request_Log__c/fields/DR_Order_State__c.field-meta.xml
<CustomField>
    <fullName>DR_Order_State__c</fullName>
    <description>The state of the Digital River order.</description>
    <inlineHelpText>The state of the Digital River order.</inlineHelpText>
    <label>DR Order State</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Fulfillment_Request_Log__c/fields/DR_OrderItem_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_OrderItem_Id__c</fullName>
    <description>The Digital River Order Item Identifier</description>
    <inlineHelpText>The Digital River Order Item Identifier</inlineHelpText>
    <label>DR OrderItem Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Fulfillment_Request_Log__c/fields/Fulfill_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Fulfill_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Specifies Order Item Quantity to Fulfill</description>
    <inlineHelpText>Specifies Order Item Quantity to Fulfill</inlineHelpText>
    <label>Fulfill Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/DR_Fulfillment_Request_Log__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Salesforce Order Id</description>
    <inlineHelpText>Salesforce Order Id</inlineHelpText>
    <label>Order Id</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>DR Fulfillment Request Logs</relationshipLabel>
    <relationshipName>DR_Fulfillment_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/DR_Fulfillment_Request_Log__c/fields/OrderItem_Id__c.field-meta.xml
<CustomField>
    <fullName>OrderItem_Id__c</fullName>
    <description>Salesforce Order Product Id (SF Order Item Id)</description>
    <inlineHelpText>Salesforce Order Product Id (SF Order Item Id)</inlineHelpText>
    <label>OrderItem Id</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Line_Item_Fulfillment__c/DR_Line_Item_Fulfillment__c.object-meta.xml
<CustomObject>
    <label>Digital River Line Item Fulfillment</label>
    <nameField>
        <displayFormat>FLI-{000000}</displayFormat>
        <label>DR Line Item Fulfillment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital River Line Item Fulfillments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/DR_Line_Item_Fulfillment__c/fields/Cancel_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Quantity__c</fullName>
    <description>Specifies Order Item Quantity to Cancel</description>
    <inlineHelpText>Specifies Order Item Quantity to Cancel</inlineHelpText>
    <label>Cancel Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/DR_Line_Item_Fulfillment__c/fields/Digital_River_OrderItem_Id__c.field-meta.xml
<CustomField>
    <fullName>Digital_River_OrderItem_Id__c</fullName>
    <description>The Digital River order item identifier</description>
    <inlineHelpText>The Digital River order item identifier</inlineHelpText>
    <label>Digital River OrderItem Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Line_Item_Fulfillment__c/fields/DR_Fulfillment_Request_Log__c.field-meta.xml
<CustomField>
    <fullName>DR_Fulfillment_Request_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DR Fulfillment Request Log Record</description>
    <inlineHelpText>DR Fulfillment Request Log Record</inlineHelpText>
    <label>DR Fulfillment Request Log</label>
    <referenceTo>DR_Fulfillment_Request_Log__c</referenceTo>
    <relationshipLabel>Digital River Line Item Fulfillments</relationshipLabel>
    <relationshipName>Digital_River_Line_Item_Fulfillments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/DR_Line_Item_Fulfillment__c/fields/DR_Order_Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>DR_Order_Fulfillment__c</fullName>
    <description>Order Level Fulfillment Record</description>
    <inlineHelpText>Order Level Fulfillment Record</inlineHelpText>
    <label>Digital River Order Fulfillment</label>
    <referenceTo>DR_Fulfillment__c</referenceTo>
    <relationshipLabel>Digital River Line Item Fulfillments</relationshipLabel>
    <relationshipName>DR_Line_Item_Fulfillments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/DR_Line_Item_Fulfillment__c/fields/Fulfill_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Fulfill_Quantity__c</fullName>
    <description>Specifies Order Item Quantity to Fulfill</description>
    <inlineHelpText>Specifies Order Item Quantity to Fulfill</inlineHelpText>
    <label>Fulfill Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/DR_Line_Item_Fulfillment__c/fields/Fulfillment_OrderItem_Status__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_OrderItem_Status__c</fullName>
    <description>Open - Line Item Fulfillment request has to be sent to DR
        Reprocess - Previous Attempt to send Fulfillment Request to DR failed. Will be reprocessed in next run.
        Completed - Line Item fulfillment/cancellation request processed successfully
        Failed - Failed Processing this Line Item Fulfillment record after multiple attempts.</description>
    <inlineHelpText>Order Item Fulfillment Notification Status</inlineHelpText>
    <label>Fulfillment OrderItem Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Reprocess</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/DR_Line_Item_Fulfillment__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Used to Stored Information about Order Line Item fulfillment</description>
    <inlineHelpText>Used to Stored Information about Order Line Item fulfillment</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/DR_Line_Item_Fulfillment__c/fields/Retry_Attempts_Made__c.field-meta.xml
<CustomField>
    <fullName>Retry_Attempts_Made__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Retry Attempts Made</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/DR_Line_Item_Fulfillment__c/fields/SF_OrderItem_Id__c.field-meta.xml
<CustomField>
    <fullName>SF_OrderItem_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SF Order Item Id</description>
    <inlineHelpText>SF Order Item Id</inlineHelpText>
    <label>SF OrderItem</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Digital River Line Item Fulfillments</relationshipLabel>
    <relationshipName>Digital_River_Line_Item_Fulfillments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/InvoiceCreditMemo/objects/Order/fields/DR_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_Order_Id__c</fullName>
    <description>DR order Id</description>
    <externalId>true</externalId>
    <label>Digital River Order Id</label>
    <length>128</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/InvoiceCreditMemo/objects/Order/fields/DR_Order_State__c.field-meta.xml
<CustomField>
    <fullName>DR_Order_State__c</fullName>
    <description>Digital River order states</description>
    <inlineHelpText>Digital River order states</inlineHelpText>
    <label>Digital River Order State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>pending_payment</fullName>
            </value>
            <value>
                <fullName>in_review</fullName>
            </value>
            <value>
                <fullName>accepted</fullName>
            </value>
            <value>
                <fullName>blocked</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>fulfilled</fullName>
            </value>
            <value>
                <fullName>complete</fullName>
            </value>
            <value>
                <fullName>returned</fullName>
            </value>
            <value>
                <fullName>salesforce_failure</fullName>
            </value> <value>
                <fullName>cancelled_by_sf</fullName>
            </value>
            <value>
                <fullName>cancelled_by_dr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/classes/service/DRB2B_FulfillmentService.cls
public with sharing class DRB2B_FulfillmentService {
    private static final DCM_Logger LOGGER = DCM_Logger.getInstance(DRB2B_Constants.Module.FULFILLMENT);

    @TestVisible
    DRB2B_FulfillmentSelector fulfillmentSelector = new DRB2B_FulfillmentSelector();
    @TestVisible
    private static DRB2B_OrderItemSelector orderItemSelector = new DRB2B_OrderItemSelector();
    @TestVisible
    private DRB2B_ConnectorConfigurationSelector configurationSelector = new DRB2B_ConnectorConfigurationSelector();
    @TestVisible
    private static DRB2B_RequestService requestService = new DRB2B_RequestService();

    public Boolean createDRFulfillmentObject(Map<String, Map<String, String>>  fulfillmentToCreateMap) {
        Boolean isDRFulfillmentObjectCreated = false;
        try {
            List<DR_Fulfillment__c> fulfillmentList = new List<DR_Fulfillment__c>();
            for( Map<String, String> orderDataMap: fulfillmentToCreateMap.values() ){
                DR_Fulfillment__c drFulfillment = new DR_Fulfillment__c(
                    DR_Order_Id__c = orderDataMap.get('drOrderId'),
                    DR_Order_State__c = String.isNotBlank(orderDataMap.get('drOrderState'))
                        ? orderDataMap.get('drOrderState')
                        : '',
                    Order_Id__c = String.isNotBlank(orderDataMap.get('orderId')) ? orderDataMap.get('orderId') : '',
                    DR_Fulfillment_Status__c = String.isNotBlank(orderDataMap.get('fulfillmentStatus'))
                        ? orderDataMap.get('fulfillmentStatus')
                        : 'Open',
                    Is_Fulfillment_Completed__c = String.isNotBlank(orderDataMap.get('isOrderCompleteEventReceived'))
                        ? Boolean.valueOf(orderDataMap.get('isOrderCompleteEventReceived'))
                        : false,
                    Eligible_For_Fulfillment__c = String.isNotBlank(orderDataMap.get('isOrderAcceptedEventRecieved'))
                        ? Boolean.valueOf(orderDataMap.get('isOrderAcceptedEventRecieved'))
                        : false,
                    Order_Cancelled__c = String.isNotBlank(orderDataMap.get('orderCancelled'))
                        ? Boolean.valueOf(orderDataMap.get('orderCancelled'))
                        : false,
                    Message__c = String.isNotBlank(orderDataMap.get('message')) ? orderDataMap.get('message') : ''
                );
                //collect all fulfillment records
                fulfillmentList.add(drFulfillment);
            }
            //Create fulfillment records
            DmlManager.insertAsUser(fulfillmentList);
            isDRFulfillmentObjectCreated = true;
        } catch (Exception e) {
            LOGGER.error(e);
        } finally {
            LOGGER.flush();
        }

        return isDRFulfillmentObjectCreated;
    }

     /**
     * Create or Update DR Fulfillment record for a specific DR Order Id
     */
    public Boolean createOrUpdateDrFulfillmentRecord(Map<String, Map<String, String>> orderInfoMap) {

        Boolean drFulfillmentCreatedOrUpdated = false;
        List<String> orderIds =  new List<String>(orderInfoMap.keySet());
        Map<String, Map<String, String>> fulfillmentToCreate = new  Map<String, Map<String, String>> ();
        fulfillmentToCreate.putAll(orderInfoMap);
        //getByDROrderIds
        List<DR_Fulfillment__c> drFulfillmentRecList = fulfillmentSelector.getByDROrderIds(orderIds);
       
        Map<DR_Fulfillment__c, Map<String, String>>  fulfillmentToUpdate = new Map<DR_Fulfillment__c, Map<String, String>>();

        for(DR_Fulfillment__c orderfulfillment: drFulfillmentRecList){
            //remove existing DR Oders from create list
            fulfillmentToCreate.remove(orderfulfillment.DR_Order_Id__c);
            fulfillmentToUpdate.put(orderfulfillment,orderInfoMap.get(orderfulfillment.DR_Order_Id__c)); 
        }
        
        //Update DR Fulfillment records
        if(null != fulfillmentToUpdate && fulfillmentToUpdate.size()>0) {
           // DR_Fulfillment__c drFulfillmentRec = drFulfillmentRecList.get(0);
            drFulfillmentCreatedOrUpdated = updateDrFulfillmentRecord(fulfillmentToUpdate);
        }
       // Create a New DR Fulfillment Record
       if(fulfillmentToCreate.size()>0) {
            drFulfillmentCreatedOrUpdated = createDRFulfillmentObject(fulfillmentToCreate);
        }
        return drFulfillmentCreatedOrUpdated;
    }


    public Boolean updateDrFulfillmentRecord( Map<DR_Fulfillment__c , Map<String, String>> fulfillmentToUpdate) {
        Boolean drFulfillmentRecUpdated = false;
        List<DR_Fulfillment__c> fulfillmentList = new List<DR_Fulfillment__c>();
        for(DR_Fulfillment__c drFulfillmentRec:fulfillmentToUpdate.keySet()){
            Map<String, String> orderDataMap = fulfillmentToUpdate.get(drFulfillmentRec);
            drFulfillmentRec.Order_Id__c = String.isNotBlank(orderDataMap.get('orderId')) ? orderDataMap.get('orderId') : drFulfillmentRec.Order_Id__c;
            drFulfillmentRec.DR_Order_State__c = String.isNotBlank(orderDataMap.get('drOrderState')) ? orderDataMap.get('drOrderState') : drFulfillmentRec.DR_Order_State__c;
            drFulfillmentRec.Eligible_For_Fulfillment__c = String.isNotBlank(orderDataMap.get('isOrderAcceptedEventRecieved')) ? Boolean.valueOf(orderDataMap.get('isOrderAcceptedEventRecieved')) : drFulfillmentRec.Eligible_For_Fulfillment__c;
            drFulfillmentRec.Is_Fulfillment_Completed__c = String.isNotBlank(orderDataMap.get('orderCompleteEventReceived')) ? Boolean.valueOf(orderDataMap.get('orderCompleteEventReceived')) : drFulfillmentRec.Is_Fulfillment_Completed__c;
            drFulfillmentRec.Message__c = String.isNotBlank(orderDataMap.get('message')) ? orderDataMap.get('message') : drFulfillmentRec.Message__c;
            drFulfillmentRec.DR_Fulfillment_Status__c = String.isNotBlank(orderDataMap.get('fulfillmentStatus')) ? orderDataMap.get('fulfillmentStatus') : drFulfillmentRec.DR_Fulfillment_Status__c;
            drFulfillmentRec.Order_Cancelled__c = String.isNotBlank(orderDataMap.get('orderCancelled')) ? Boolean.valueOf(orderDataMap.get('orderCancelled')) : drFulfillmentRec.Order_Cancelled__c;
            fulfillmentList.add(drFulfillmentRec);
        }
        DmlManager.updateAsUser(fulfillmentList);
        drFulfillmentRecUpdated = true;
        return drFulfillmentRecUpdated;
    }

    public Boolean updateDrFulfillmentRecord( DR_Fulfillment__c fulfillmentrec, Map<String, String> dataMap) {
         Map<DR_Fulfillment__c , Map<String, String>> fulfillmentToUpdate = new Map<DR_Fulfillment__c , Map<String, String>>();
         fulfillmentToUpdate.put(fulfillmentrec, dataMap);
         return updateDrFulfillmentRecord(fulfillmentToUpdate);

    }

    /**
     * Get SF Orders which are eligible for Fulfillment Or Cancellation
     * order.accepted event must be received for these Orders
     */
    public List<Order> getOrdersWhichReceivedOrderAcceptedEvent(List<Order> sfOrders) {
        List<Order> sfOrdersWhichReceivedOrderAcceptedEvent = new List<Order>();
        Map<String, Order> sfOrderByDrOrderId = (Map<String, Order>) Collection.of(sfOrders).mapBy(Order.DR_Order_Id__c);
        List<DR_Fulfillment__c> orderFulfillmentRecs = fulfillmentSelector.getByDROrderIds(sfOrderByDrOrderId.keySet());
        if(DCM_BaseUtilities.isNotNullOrEmpty(orderFulfillmentRecs)) {
            for(DR_Fulfillment__c orderFulfillmentRec : orderFulfillmentRecs) {
                if(orderFulfillmentRec.Eligible_For_Fulfillment__c) {
                    sfOrdersWhichReceivedOrderAcceptedEvent.add(sfOrderByDrOrderId.get(orderFulfillmentRec.DR_Order_Id__c));
                }
            }
        }
        return sfOrdersWhichReceivedOrderAcceptedEvent;
    }

    /**
     * Get DR Order Fulfillment Records by DR Order Id
     */
    public Map<String, DR_Fulfillment__c> getOrderFulfillmentRecsByDrOrderId(Set<String> drOrderIds) {
        Map<String, DR_Fulfillment__c> orderFulfillmentRecByDrOrderId = new Map<String, DR_Fulfillment__c>();
        List<DR_Fulfillment__c> orderFulfillmentRecs = fulfillmentSelector.getByDROrderIds(drOrderIds);
        for (DR_Fulfillment__c orderFulfillmentRec : orderFulfillmentRecs) {
            orderFulfillmentRecByDrOrderId.put(orderFulfillmentRec.DR_Order_Id__c, orderFulfillmentRec);
        }
        return orderFulfillmentRecByDrOrderId;
    }

    /**
     * Create or Update DR Order Fulfillment Records
     */
    public void createdOrUpdateDrOrderFulfillmentRecs(List<DR_Fulfillment_Request_Log__c> fulfillmentRequestLogRecs, Set<String> drOrderIds) {
        List<DR_Fulfillment__c> drOrderFulfillmentRecList = new List<DR_Fulfillment__c>();
        List<String> drOrderIdsInOrderFulfillmentList = new List<String>();
        Map<String, DR_Fulfillment__c> orderFulfillmentRecByDrOrderId = getOrderFulfillmentRecsByDrOrderId(drOrderIds);
        for(DR_Fulfillment_Request_Log__c fulfillmentRequestLogRec : fulfillmentRequestLogRecs) {
            // Prevent duplicate Order Fulfillment Record Creation
            if(!drOrderIdsInOrderFulfillmentList.contains(fulfillmentRequestLogRec.DR_Order_Id__c)) {
                drOrderFulfillmentRecList.add(getDrOrderFulfillmentRecToCreateOrUpdate(fulfillmentRequestLogRec, orderFulfillmentRecByDrOrderId));
                drOrderIdsInOrderFulfillmentList.add(fulfillmentRequestLogRec.DR_Order_Id__c);
            }
        }
        DmlManager.upsertAsUser(drOrderFulfillmentRecList);
        Map<Id, String> drOrderIdByOrderFulfillmentId = (Map<Id, String>) Collection.of(drOrderFulfillmentRecList).mapBy(DR_Fulfillment__c.Id, DR_Fulfillment__c.DR_Order_Id__c);
        LOGGER.info('Created or Updated DR Order Fulfillment Records. Map of DR Order Id By DR Order Fulfillment Id: ' + drOrderIdByOrderFulfillmentId);
    }

    /**
     * Get DR Order Fulfillment Record to Create or Update
     */
    public DR_Fulfillment__c getDrOrderFulfillmentRecToCreateOrUpdate(DR_Fulfillment_Request_Log__c fulfillmentRequestLogRec, Map<String, DR_Fulfillment__c> orderFulfillmentRecByDrOrderId) {
        DR_Fulfillment__c drOrderFulfillmentRec;
        String drOrderId = fulfillmentRequestLogRec.DR_Order_Id__c;
        if(orderFulfillmentRecByDrOrderId.containsKey(drOrderId)) {
            drOrderFulfillmentRec = orderFulfillmentRecByDrOrderId.get(drOrderId);
        }
        else {
            drOrderFulfillmentRec = new DR_Fulfillment__c();
            drOrderFulfillmentRec.DR_Order_Id__c = drOrderId;
        }
        drOrderFulfillmentRec.Order_Id__c = fulfillmentRequestLogRec.OrderId__c;
        drOrderFulfillmentRec.DR_Order_State__c = fulfillmentRequestLogRec.DR_Order_State__c;
        return drOrderFulfillmentRec;
    }

    /**
     * Create DR Line Item Fulfillment Records
     */
    public void createdDrLineItemFulfillmentRecs(List<DR_Fulfillment_Request_Log__c> fulfillmentRequestLogRecs, Set<String> drOrderIds) {
        List<DR_Line_Item_Fulfillment__c> drLineItemFulfillmentRecList = new List<DR_Line_Item_Fulfillment__c>();
        Map<String, DR_Fulfillment__c> orderFulfillmentRecByDrOrderId = getOrderFulfillmentRecsByDrOrderId(drOrderIds);
        for(DR_Fulfillment_Request_Log__c fulfillmentRequestLogRec : fulfillmentRequestLogRecs) {
            drLineItemFulfillmentRecList.add(getDrLineItemFulfillmentRecToCreate(fulfillmentRequestLogRec, orderFulfillmentRecByDrOrderId));
        }
        DmlManager.insertAsUser(drLineItemFulfillmentRecList);
        Set<String> drLineItemIds = (Set<String>) Collection.of(drLineItemFulfillmentRecList).setOf(DR_Line_Item_Fulfillment__c.Digital_River_OrderItem_Id__c);
        LOGGER.info('Created DR Line Item Fulfillment Records for DR Line Item Ids: ' + drLineItemIds);
    }

    /**
     * Get DR Line Item Fulfillment Record to Create
     */
    public DR_Line_Item_Fulfillment__c getDrLineItemFulfillmentRecToCreate(DR_Fulfillment_Request_Log__c fulfillmentRequestLogRec, Map<String, DR_Fulfillment__c> orderFulfillmentRecByDrOrderId) {
        DR_Line_Item_Fulfillment__c drLineItemFulfillmentRec = new DR_Line_Item_Fulfillment__c (
            DR_Order_Fulfillment__c = orderFulfillmentRecByDrOrderId.get(fulfillmentRequestLogRec.DR_Order_Id__c).Id,
            Digital_River_OrderItem_Id__c = fulfillmentRequestLogRec.DR_OrderItem_Id__c,
            SF_OrderItem_Id__c = fulfillmentRequestLogRec.OrderItem_Id__c,
            Fulfill_Quantity__c = fulfillmentRequestLogRec.Fulfill_Quantity__c,
            Cancel_Quantity__c = fulfillmentRequestLogRec.Cancel_Quantity__c,
            DR_Fulfillment_Request_Log__c = fulfillmentRequestLogRec.Id
        );
        return drLineItemFulfillmentRec;
    }

    /**
     * Send Fulfillment Request to Digital River
     */
    public void sendFulfillmentRequestToDR(DRB2B_FulfillmentResult fulfillmentResult) {
        try {
            // Build Fulfillment Request
            String fulfillmentRequestJson = getFulfillmentRequestToSubmitToDR(fulfillmentResult);
            if(String.isNotBlank(fulfillmentRequestJson)) {
                // Submit Fulfillment Request
                submitFulfillmentRequestToDR(fulfillmentResult, fulfillmentRequestJson);
            }
            else {
                //fulfillmentResult.statusCode = DRB2B_Constants.Base.ERROR_RESPONSE_CODE;
                fulfillmentResult.message = 'Failed building the Fulfillment Request';
                LOGGER.error(fulfillmentResult.orderFulfillmentRec.Id, fulfillmentResult.message);
            }
        }
        catch(Exception e) {
            //fulfillmentResult.statusCode = DRB2B_Constants.Base.ERROR_RESPONSE_CODE;
            fulfillmentResult.message = 'Failed while sending Fulfillment request to DR:' + e.getMessage();
            LOGGER.error(fulfillmentResult.orderFulfillmentRec.Id, e);
        }
        finally {
            LOGGER.flush();
        }
    }

    /**
     * Construct Fulfillment Request to send to DR
     */
    public String getFulfillmentRequestToSubmitToDR(DRB2B_FulfillmentResult fulfillmentResult) {
        DRB2B_CreateFulfillmentRequestModel fulfillmentRequestModel = new DRB2B_CreateFulfillmentRequestModel();
        fulfillmentRequestModel.orderId = fulfillmentResult.orderFulfillmentRec.DR_Order_Id__c;

        // Add Line Item Fulfillment Request
        List<DRB2B_CreateFulfillmentRequestModel.Items> fulfillmentLineItemList = new List<DRB2B_CreateFulfillmentRequestModel.Items>();
        for(DR_Line_Item_Fulfillment__c lineItemFulfillmentRec : fulfillmentResult.lineItemFulfillmentRecs) {
            DRB2B_CreateFulfillmentRequestModel.Items fulfillmentLineItem = new DRB2B_CreateFulfillmentRequestModel.Items();
            fulfillmentLineItem.itemId = lineItemFulfillmentRec.Digital_River_OrderItem_Id__c;
            fulfillmentLineItem.quantity = Integer.valueOf(lineItemFulfillmentRec.Fulfill_Quantity__c);
            fulfillmentLineItem.cancelQuantity = Integer.valueOf(lineItemFulfillmentRec.Cancel_Quantity__c);
            fulfillmentLineItemList.add(fulfillmentLineItem);
        }
        fulfillmentRequestModel.items = fulfillmentLineItemList;

        // Serialize the Fulfillment request
        String fulfillmentRequestJson = DRB2B_CreateFulfillmentRequestModel.serialize(fulfillmentRequestModel);
        LOGGER.info('Fulfillment Request to be submitted to DR: ' + fulfillmentRequestJson);
        return fulfillmentRequestJson;
    }

    /**
     * Submit the Fulfillment Request to DR
     */
    public void submitFulfillmentRequestToDR(DRB2B_FulfillmentResult fulfillmentResult, String fulfillmentRequestJson) {
        DCM_HttpClient.Request request = requestService.getFulfillmentRequest(fulfillmentRequestJson);
        DCM_HttpClient.Response response = request.fetch();
        //fulfillmentResult.statusCode = response.getStatusCode();
        if (response.getStatusCode() == DRB2B_Constants.Base.FULFILLMENT_SUCCESS_RESPONSE_CODE) {
            handleSuccessFulfillmentSubmission(response, fulfillmentResult);
        }
        else if(response.getStatusCode() == DRB2B_Constants.Base.CONFLICT_RESPONSE_CODE) {
            handleConflictFulfillmentSubmission(request, response, fulfillmentResult);
            updateLineItemFulfillmentRecsForFailedFulFulfillment(fulfillmentResult);
        }
        else {
            handleFailureFulfillmentSubmission(request, response, fulfillmentResult);
            updateLineItemFulfillmentRecsForFailedFulFulfillment(fulfillmentResult);
        }
    }

    public void handleSuccessFulfillmentSubmission(DCM_HttpClient.Response response, DRB2B_FulfillmentResult fulfillmentResult) {
        /*DRB2B_CreateFulfillmentResponseModel fulfillmentResponseObj = (DRB2B_CreateFulfillmentResponseModel) DRB2B_CreateFulfillmentResponseModel.parse(response.getBody());
        fulfillmentResult.fulfillmentResponseModel = fulfillmentResponseObj;*/
        fulfillmentResult.isSuccess = true;
        fulfillmentResult.message = 'Line Level Fulfillment request(s) are successfully processed by DR';

        // Update DR Line Item Fulfillment Records
        List<DR_Line_Item_Fulfillment__c> lineItemFulfillmentRecs = fulfillmentResult.lineItemFulfillmentRecs;
        // TODO: Should we capture DR Fulfillment request unique id?
        for(DR_Line_Item_Fulfillment__c lineItemFulfillmentRec : lineItemFulfillmentRecs) {
            lineItemFulfillmentRec.Message__c = 'Request processed successfully by DR';
            lineItemFulfillmentRec.Fulfillment_OrderItem_Status__c = DRB2B_Constants.Fulfillment.LINE_ITEM_COMPLETE_STATUS;
        }
    }

    // TODO: Need to check how to handle this. Need to check how errors come back when one of the line items has an issue and others don't
    // Tried different error combinations and it looks like we always get only on error item in the response even if more than one has an error
    // "quantity_too_large" too large will also send 409. This needs to be treated as error whereas 
    // submitting fulfillment for already submitted one will also send 409 with code "item_fulfilled" which should be treated as success
    public void handleConflictFulfillmentSubmission(DCM_HttpClient.Request request, DCM_HttpClient.Response response, DRB2B_FulfillmentResult fulfillmentResult) {
        DRB2B_ErrorResponse errorResponseObj = DRB2B_ErrorResponse.parse(response.getBody());
        String errorCodeFromResponse = errorResponseObj.errors[0].code;
        if(DRB2B_Constants.Fulfillment.FULFILLMENT_SUCCESS_CODES.contains(errorCodeFromResponse)) {
            fulfillmentResult.isSuccess = true;
            LOGGER.warn(fulfillmentResult.orderFulfillmentRec.Id, request.getOrigin(), response.getHttpResponse());
        }
        else {
            LOGGER.error(fulfillmentResult.orderFulfillmentRec.Id, request.getOrigin(), response.getHttpResponse());
        }
        fulfillmentResult.message = errorResponseObj.errors[0].message;
        fulfillmentResult.errorResponse = errorResponseObj;
    }

    public void handleFailureFulfillmentSubmission(DCM_HttpClient.Request request, DCM_HttpClient.Response response, DRB2B_FulfillmentResult fulfillmentResult) {
        DRB2B_ErrorResponse errorResponseObj = DRB2B_ErrorResponse.parse(response.getBody());
        if(DCM_BaseUtilities.isNotNullOrEmpty(errorResponseObj)) {
            LOGGER.error(fulfillmentResult.orderFulfillmentRec.Id, request.getOrigin(), response.getHttpResponse());
            fulfillmentResult.message = errorResponseObj.errors[0].message;
            fulfillmentResult.errorResponse = errorResponseObj;
        }
    }

    public void updateLineItemFulfillmentRecsForFailedFulFulfillment(DRB2B_FulfillmentResult fulfillmentResult) {
        DRB2B_ErrorResponse errorResponseObj = fulfillmentResult.errorResponse;
        String errorCode = errorResponseObj.errors[0].code;
        String errorMessage = errorResponseObj.errors[0].message;
        for(DR_Line_Item_Fulfillment__c lineItemFulfillmentRec : fulfillmentResult.lineItemFulfillmentRecs) {
            if(fulfillmentResult.isSuccess && DRB2B_Constants.Fulfillment.FULFILLMENT_ORDER_SUCCESS_CODES.contains(errorCode)) {
                lineItemFulfillmentRec.Message__c = errorResponseObj.errors[0].message;
                lineItemFulfillmentRec.Fulfillment_OrderItem_Status__c = DRB2B_Constants.Fulfillment.LINE_ITEM_COMPLETE_STATUS;
            }
            else if(fulfillmentResult.isSuccess && DRB2B_Constants.Fulfillment.FULFILLMENT_ORDER_ITEM_SUCCESS_CODES.contains(errorCode)) {
                if(errorMessage.contains(lineItemFulfillmentRec.Digital_River_OrderItem_Id__c)) {
                    lineItemFulfillmentRec.Message__c = fulfillmentResult.message;
                    lineItemFulfillmentRec.Fulfillment_OrderItem_Status__c = DRB2B_Constants.Fulfillment.LINE_ITEM_COMPLETE_STATUS;
                }
                else {
                    lineItemFulfillmentRec.Message__c = 'Failed as One of the Line Items in this request is already fulfilled/cancelled.' + fulfillmentResult.message;
                    lineItemFulfillmentRec.Fulfillment_OrderItem_Status__c = DRB2B_Constants.Fulfillment.LINE_ITEM_REPROCESS_STATUS;
                }
            }
            else {
                lineItemFulfillmentRec.Message__c = 'Issue with one or more of the line items in the Fulfillment/Cancellation Request. ' + fulfillmentResult.message;
                lineItemFulfillmentRec.Retry_Attempts_Made__c = lineItemFulfillmentRec.Retry_Attempts_Made__c + 1;
                lineItemFulfillmentRec.Fulfillment_OrderItem_Status__c = (lineItemFulfillmentRec.Retry_Attempts_Made__c > Integer.valueOf(configurationSelector.getFulfillmentRetryLimit())) 
                                ? DRB2B_Constants.Fulfillment.LINE_ITEM_FAILED_STATUS 
                                : DRB2B_Constants.Fulfillment.LINE_ITEM_REPROCESS_STATUS;
            }
        }
    }

    public List<String> getCompletelyFulfilledOrCancelledOrders(List<DR_Fulfillment__c> orderFulfillmentRecs) {
        List<String> completelyFulfilledOrCancelledOrderIds = new List<String>();

        // Get Map of Salesforce OrderId by DR Order Fulfillment Record Id
        Map<Id, String> sfOrderIdByOrderFulfillmentId = (Map<Id, String>) Collection.of(orderFulfillmentRecs).mapBy(DR_Fulfillment__c.Id, DR_Fulfillment__c.Order_Id__c);

        // Get All Order Items for this Salesforce Order
        List<Id> sfOrderIds = new List<Id>( (List<Id>) sfOrderIdByOrderFulfillmentId.values());
        List<OrderItem> orderItems = orderItemSelector.getByOrderIdsAndOrderItemType(sfOrderIds, 'Order Product');

        // Group Salesforce Order Items by Order
        Map<Id, List<OrderItem>> orderItemsByOrderId = (Map<Id, List<OrderItem>>)
                Collection.of(orderItems).groupBy(OrderItem.OrderId);

        // Get Orders which are completely fulfilled or cancelled
        for(Id orderId : orderItemsByOrderId.keySet()) {
            Boolean isOrderFulfilledOrCancelled = true;
            List<OrderItem> orderItemRecs = orderItemsByOrderId.get(orderId);
            for(OrderItem orderItem : orderItemRecs) {
                if(orderItem.DR_Open_Quantity__c > 0) {
                    isOrderFulfilledOrCancelled = false;
                    break;
                }
            }
            if(isOrderFulfilledOrCancelled) {
                completelyFulfilledOrCancelledOrderIds.add(String.valueOf(orderId));
            }
        }

        return completelyFulfilledOrCancelledOrderIds;
    }

}