src/main/default/objects/DR_Fulfillment__c/DR_Fulfillment__c.object-meta.xml
<CustomObject>
    <description>Store information regarding fulfillment</description>
    <label>Digital River Fulfillment</label>
    <nameField>
        <displayFormat>Fulfillment-{000000}</displayFormat>
        <label>DR Fulfillment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital River Fulfillments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/DR_Fulfillment__c/fields/DR_Fulfillment_Status__c.field-meta.xml
<CustomField>
    <fullName>DR_Fulfillment_Status__c</fullName>
    <description>Open - Fulfillment request has to be sent for Order Item(s)
Reprocess - Previous Attempt to send Fulfillment Request to DR failed. Will be reprocessed in next run
Completed - Fulfillment process is completed for this Order.
Failed - Failed Processing this Order after multiple attempts.</description>
    <label>Digital River Fulfillment Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Reprocess</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/DR_Fulfillment__c/fields/DR_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_Order_Id__c</fullName>
    <description>Digital River Order ID</description>
    <externalId>true</externalId>
    <label>Digital River Order Id</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Fulfillment__c/fields/Eligible_For_Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>Eligible_For_Fulfillment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is fulfillment record eligible for fulfillment</description>
    <label>Eligible For Fulfillment</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/DR_Fulfillment__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Information about the Success or Failure of Posting fulfillment to DR</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/DR_Fulfillment__c/fields/Num_Of_Line_Item_Records_To_Process__c.field-meta.xml
<CustomField>
    <fullName>Num_Of_Line_Item_Records_To_Process__c</fullName>
    <description>Count of Child Line Item Fulfillment Records available for Fulfillment or Cancellation i.e., Fulfillment Order Item Status is Open or Reprocess</description>
    <inlineHelpText>Count of Child Line Item Fulfillment Records available for Fulfillment or Cancellation i.e., Fulfillment Order Item Status is Open or Reprocess</inlineHelpText>
    <label>Number Of Line Item Records To Process</label>
    <summaryFilterItems>
        <field>DR_Line_Item_Fulfillment__c.Fulfillment_OrderItem_Status__c</field>
        <operation>contains</operation>
        <value>Open, Reprocess</value>
    </summaryFilterItems>
    <summaryForeignKey>DR_Line_Item_Fulfillment__c.DR_Order_Fulfillment__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/objects/DR_Fulfillment__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <description>Salesforce order Id</description>
    <label>Order Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Fulfillment__c/fields/Retry_Attempts_Made__c.field-meta.xml
<CustomField>
    <fullName>Retry_Attempts_Made__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of Retry Attempts made for sending Fulfillment</description>
    <inlineHelpText>Number of Retry Attempts made for sending Fulfillment</inlineHelpText>
    <label>Retry Attempts Made</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/DR_Line_Item_Fulfillment__c/DR_Line_Item_Fulfillment__c.object-meta.xml
<CustomObject>
    <label>Digital River Line Item Fulfillment</label>
    <nameField>
        <displayFormat>FLI-{000000}</displayFormat>
        <label>DR Line Item Fulfillment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital River Line Item Fulfillments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/DR_Line_Item_Fulfillment__c/fields/Cancel_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Quantity__c</fullName>
    <description>Specifies Order Item Quantity to Cancel</description>
    <inlineHelpText>Specifies Order Item Quantity to Cancel</inlineHelpText>
    <label>Cancel Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/DR_Line_Item_Fulfillment__c/fields/Digital_River_OrderItem_Id__c.field-meta.xml
<CustomField>
    <fullName>Digital_River_OrderItem_Id__c</fullName>
    <description>The Digital River order item identifier</description>
    <inlineHelpText>The Digital River order item identifier</inlineHelpText>
    <label>Digital River OrderItem Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Line_Item_Fulfillment__c/fields/DR_Order_Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>DR_Order_Fulfillment__c</fullName>
    <description>Order Level Fulfillment Record</description>
    <inlineHelpText>Order Level Fulfillment Record</inlineHelpText>
    <label>Digital River Order Fulfillment</label>
    <referenceTo>DR_Fulfillment__c</referenceTo>
    <relationshipLabel>Digital River Line Item Fulfillments</relationshipLabel>
    <relationshipName>DR_Line_Item_Fulfillments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/DR_Line_Item_Fulfillment__c/fields/Fulfill_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Fulfill_Quantity__c</fullName>
    <description>Specifies Order Item Quantity to Fulfill</description>
    <inlineHelpText>Specifies Order Item Quantity to Fulfill</inlineHelpText>
    <label>Fulfill Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/DR_Line_Item_Fulfillment__c/fields/Fulfillment_OrderItem_Status__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_OrderItem_Status__c</fullName>
    <description>Open - Line Item Fulfillment request has to be sent to DR
        Reprocess - Previous Attempt to send Fulfillment Request to DR failed. Will be reprocessed in next run.
        Completed - Line Item fulfillment/cancellation request processed successfully
        Failed - Failed Processing this Line Item Fulfillment record after multiple attempts.</description>
    <inlineHelpText>Order Item Fulfillment Notification Status</inlineHelpText>
    <label>Fulfillment OrderItem Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Reprocess</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/DR_Line_Item_Fulfillment__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Used to Stored Information about Order Line Item fulfillment</description>
    <inlineHelpText>Used to Stored Information about Order Line Item fulfillment</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/DR_Line_Item_Fulfillment__c/fields/Retry_Attempts_Made__c.field-meta.xml
<CustomField>
    <fullName>Retry_Attempts_Made__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Retry Attempts Made</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/DR_Line_Item_Fulfillment__c/fields/SF_OrderItem_Id__c.field-meta.xml
<CustomField>
    <fullName>SF_OrderItem_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SF Order Item Id</description>
    <inlineHelpText>SF Order Item Id</inlineHelpText>
    <label>SF OrderItem</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Digital River Line Item Fulfillments</relationshipLabel>
    <relationshipName>Digital_River_Line_Item_Fulfillments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/InvoiceCreditMemo/objects/Order/fields/DR_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_Order_Id__c</fullName>
    <description>DR order Id</description>
    <externalId>true</externalId>
    <label>Digital River Order Id</label>
    <length>128</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/OrderItem/fields/DR_Cancelled_Quantity__c.field-meta.xml
<CustomField>
    <fullName>DR_Cancelled_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Cancelled Line Item Quantity</description>
    <inlineHelpText>Cancelled Line Item Quantity</inlineHelpText>
    <label>DR Cancelled Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/OrderItem/fields/DR_Fulfilled_Quantity__c.field-meta.xml
<CustomField>
    <fullName>DR_Fulfilled_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Fulfilled Line Item Quantity</description>
    <inlineHelpText>Fulfilled Line Item Quantity</inlineHelpText>
    <label>DR Fulfilled Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/OrderItem/fields/DR_Order_Item_State__c.field-meta.xml
<CustomField>
    <fullName>DR_Order_Item_State__c</fullName>
    <description>Order item State at DR end</description>
    <inlineHelpText>Order item State at DR end</inlineHelpText>
    <label>Digital River Order Item State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>created</fullName>
            </value>
            <value>
                <fullName>fulfilled</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>partially_fulfilled</fullName>
            </value>
            <value>
                <fullName>partially_cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/fulfillment/classes/DRB2B_OrderFulfillmentBatchJob.cls
global with sharing class DRB2B_OrderFulfillmentBatchJob implements Database.Batchable<SObject>, Database.AllowsCallouts, Database.Stateful {
    private static final DCM_Logger LOGGER = DCM_Logger.getInstance(DRB2B_Constants.Module.BATCH_FULFILLMENT);

    public List<DRB2B_FulfillmentResult> fulfillmentResultList = new List<DRB2B_FulfillmentResult>();

    @TestVisible
    private DRB2B_FulfillmentService fulfillmentService = new DRB2B_FulfillmentService();

    @TestVisible
    private DRB2B_OrderSelector orderSelector = new DRB2B_OrderSelector();

    @TestVisible
    private DRB2B_OrderItemSelector orderItemSelector = new DRB2B_OrderItemSelector();

    @TestVisible
    private DRB2B_ConnectorConfigurationSelector configurationSelector = new DRB2B_ConnectorConfigurationSelector();

    global Database.QueryLocator start(Database.BatchableContext bc) {
        String jobId = bc.getJobId();
        if(B2BUtils.isBatchExecuting(bc.getJobId(),  'DRB2B_OrderFulfillmentBatchJob')){
            return  Database.getQueryLocator([SELECT Id, State, IsActive  from user  where id =:UserInfo.getUserId() and IsActive = false]);
        }
        LOGGER.info('Order Fulfillment Batch Job Id: ' + jobId);
        Integer queryLimit = Integer.valueOf(configurationSelector.getOrderFulfillmentJobQueryLimit());
        List<String> orderFulfillmentStatuses = new List<String>{ DRB2B_Constants.Fulfillment.ORDER_OPEN_STATUS, DRB2B_Constants.Fulfillment.ORDER_REPROCESS_STATUS };
        List<String> lineItemFulfillmentStatuses = new List<String>{ DRB2B_Constants.Fulfillment.LINE_ITEM_OPEN_STATUS, DRB2B_Constants.Fulfillment.LINE_ITEM_REPROCESS_STATUS };
        LOGGER.flush();
        return Database.getQueryLocator([
            SELECT Id, Order_Id__c, DR_Order_Id__c, Retry_Attempts_Made__c,
                (SELECT Id, SF_OrderItem_Id__c, Digital_River_OrderItem_Id__c, Fulfill_Quantity__c, Cancel_Quantity__c, Retry_Attempts_Made__c, CreatedDate
                    FROM DR_Line_Item_Fulfillments__r
                    WHERE Fulfillment_OrderItem_Status__c in :lineItemFulfillmentStatuses)
            FROM DR_Fulfillment__c
            WHERE DR_Fulfillment_Status__c IN :orderFulfillmentStatuses and Eligible_For_Fulfillment__c = true and Num_Of_Line_Item_Records_To_Process__c > 0
            WITH SECURITY_ENFORCED
            ORDER BY CreatedDate LIMIT :queryLimit
        ]);
    }

    global void execute(Database.BatchableContext bc, List<DR_Fulfillment__c> orderFulfillmentRecs) {
        LOGGER.debug('Order Fulfillment Records to process: ' + orderFulfillmentRecs);
        List<String> completelyFulfilledOrCancelledOrderIds = new List<String>();
        try {
            Integer batchFulfillmentsTimePeriod = String.isBlank(configurationSelector.getDRBatchFulfillmentsTimePeriod())
                    ? 0 : Integer.valueOf(configurationSelector.getDRBatchFulfillmentsTimePeriod());

            // Get a list of Completely Fulfilled/Cancelled SF Order Ids
            if(DCM_BaseUtilities.isNotNullOrEmpty(orderFulfillmentRecs)) {
                completelyFulfilledOrCancelledOrderIds = fulfillmentService.getCompletelyFulfilledOrCancelledOrders(orderFulfillmentRecs);
                logger.debug('Completely Fulfilled/Cancelled SF Order Ids: ' + completelyFulfilledOrCancelledOrderIds);
            }

            // Loop through all Order Fulfillment Records and get the Line Item Fulfillment Records for each
            for (DR_Fulfillment__c orderFulfillmentRec : orderFulfillmentRecs) {
                DRB2B_FulfillmentResult fulfillmentResult;
                List<DR_Line_Item_Fulfillment__c> lineItemFulfillmentRecs = orderFulfillmentRec.DR_Line_Item_Fulfillments__r;
                if(DCM_BaseUtilities.isNotNullOrEmpty(lineItemFulfillmentRecs)) {
                    // Check if all the Line Items are completely fulfilled/cancelled
                    if(completelyFulfilledOrCancelledOrderIds.contains(orderFulfillmentRec.Order_Id__c)) {
                        LOGGER.info('All the LineItems are either Fulfilled/Cancelled. Skipping Batching of Fulfillments/Cancellations check');
                    }
                    else {
                        // Check if Batching of Fulfillments/Cancellations is required
                        Boolean batchFulfillmentOrCancellationSupported = Boolean.valueOf(configurationSelector.getDRBatchFulfillments());
                        if(batchFulfillmentOrCancellationSupported) {
                            LOGGER.debug('Batching of Fulfillments/Cancellations will happen every ' + batchFulfillmentsTimePeriod + ' minutes.');
                            // Sort DR LineItem Fulfillment Records by CreatedDate
                            List<DR_Line_Item_Fulfillment__c> sortedLineItemFulfillmentRecs = (List<DR_Line_Item_Fulfillment__c>)
                                    Collection.of(lineItemFulfillmentRecs).orderBy(DR_Line_Item_Fulfillment__c.CreatedDate,
                                            Ordering.ASCENDING).get();

                            // Get Earliest Created DR LineItem Fulfillment Record
                            DR_Line_Item_Fulfillment__c earliestCreatedLineItemFulfillmentRec = sortedLineItemFulfillmentRecs.get(0);
                            LOGGER.info(orderFulfillmentRec.Id, 'Earliest DR Line Item Fulfillment Record in Open/Reprocess status: ' + earliestCreatedLineItemFulfillmentRec);

                            // Check if this exceeds the time configured for Batching Fulfillments/Cancellations
                            Long earliestLineItemCreatedTimeInMillisecs = earliestCreatedLineItemFulfillmentRec.createdDate.getTime();
                            Long currentSystemTimeInMillisecs = DateTime.now().getTime();
                            Long timeDiffInMinutes = (currentSystemTimeInMillisecs - earliestLineItemCreatedTimeInMillisecs)/60000;
                            LOGGER.info(orderFulfillmentRec.Id, 'Time difference between CurrentTime and Earliest Created LineItem Fulfillment record: ' + timeDiffInMinutes);
                            if(timeDiffInMinutes < batchFulfillmentsTimePeriod) {
                                LOGGER.warn('Configured Batch Fulfillments/Cancellations wait time is not exceeded. Skipping Fulfillment/Cancellation request');
                                continue;
                            }
                        }
                        else {
                            LOGGER.warn('Batching of Fulfillments/Cancellations is not requested');
                        }
                    }
                    // Submit Fulfillment/Cancellation request
                    fulfillmentResult = new DRB2B_FulfillmentResult(orderFulfillmentRec, lineItemFulfillmentRecs);
                    LOGGER.info('Line Item Fulfillment Records to process: ' + lineItemFulfillmentRecs);
                    // TODO: Update Order Fulfillment status to IN PROCESS to indicate that Line Item Records were processed before??
                    fulfillmentService.sendFulfillmentRequestToDR(fulfillmentResult);
                }
                this.fulfillmentResultList.add(fulfillmentResult);
            }
            LOGGER.info('Fulfillment Result List: ' + this.fulfillmentResultList);
        }
        catch(Exception e) { // TODO: Handle Exceptions properly
            LOGGER.error(e);
        }
        finally {
            LOGGER.flush();
        }
    }

    global void finish(Database.BatchableContext bc) {
        LOGGER.info('Fulfillment Result List in finish method: ' + this.fulfillmentResultList);
        List<DR_Fulfillment__c> orderFulfillmentRecs = new List<DR_Fulfillment__c>();
        List<DR_Line_Item_Fulfillment__c> allLineItemFulfillmentRecs = new List<DR_Line_Item_Fulfillment__c>();
        List<DR_Line_Item_Fulfillment__c> successfulLineItemFulfillmentRecs = new List<DR_Line_Item_Fulfillment__c>();
        try {
            // Get all Fulfillment Results
            for(DRB2B_FulfillmentResult fulfillmentResult : this.fulfillmentResultList) {
                if(DCM_BaseUtilities.isNotNullOrEmpty(fulfillmentResult.lineItemFulfillmentRecs)) {
                    if(fulfillmentResult.isSuccess) {
                        successfulLineItemFulfillmentRecs.addAll(
                            (List<DR_Line_Item_Fulfillment__c>)
                                Collection.of(fulfillmentResult.lineItemFulfillmentRecs)
                                    .filter(DR_Line_Item_Fulfillment__c.Fulfillment_OrderItem_Status__c).equals(DRB2B_Constants.Fulfillment.LINE_ITEM_COMPLETE_STATUS)
                                    .get()
                        );
                    }
                    allLineItemFulfillmentRecs.addAll(fulfillmentResult.lineItemFulfillmentRecs);
                }
                else {
                    fulfillmentResult.orderFulfillmentRec.Message__c = fulfillmentResult.message;
                }
                orderFulfillmentRecs.add(fulfillmentResult.orderFulfillmentRec);
            }

            // Update Line Item Fulfillment Records
            if(DCM_BaseUtilities.isNotNullOrEmpty(allLineItemFulfillmentRecs)) {
                DmlManager.updateAsUser(allLineItemFulfillmentRecs);
                LOGGER.info('Line Item Fulfillment records Updated.');
            }

            // Update Order Items
            if(DCM_BaseUtilities.isNotNullOrEmpty(successfulLineItemFulfillmentRecs)) {
                updateOrderItems(successfulLineItemFulfillmentRecs);
            }

            // Update DR Order Fulfillment Records
            if(DCM_BaseUtilities.isNotNullOrEmpty(orderFulfillmentRecs)) {
                updateOrderFulfillmentRecords(orderFulfillmentRecs);
            }
        }
        catch(Exception e) { // TODO: Handle Exceptions properly
            LOGGER.error(e);
        }
        finally {
            LOGGER.flush();
        }
    }

    public void updateOrderItems(List<DR_Line_Item_Fulfillment__c> successfulLineItemFulfillmentRecs) {
        // Group by SF Order Item Id as there can be multiple Line Item Fulfillment records for the same Order Item
        Map<Id, List<DR_Line_Item_Fulfillment__c>> successfulLineItemFulfillmentRecsBySfOrderItemId = (Map<Id, List<DR_Line_Item_Fulfillment__c>>) 
                Collection.of(successfulLineItemFulfillmentRecs).groupBy(DR_Line_Item_Fulfillment__c.SF_OrderItem_Id__c);
        List<OrderItem> orderItemRecs = orderItemSelector.getDRFieldsByOrderItemIds(successfulLineItemFulfillmentRecsBySfOrderItemId.keySet());
        LOGGER.info('Order Items to Update: ' + (Set<Id>) Collection.of(orderItemRecs).setOf(OrderItem.Id));
        for(OrderItem orderItemRec : orderItemRecs) {
            List<DR_Line_Item_Fulfillment__c> lineItemFulfillmentRecs = successfulLineItemFulfillmentRecsBySfOrderItemId.get(orderItemRec.Id);
            Decimal totalFulfilledQuantity = Collection.of(lineItemFulfillmentRecs).sum(DR_Line_Item_Fulfillment__c.Fulfill_Quantity__c);
            Decimal totalCancelledQuantity = Collection.of(lineItemFulfillmentRecs).sum(DR_Line_Item_Fulfillment__c.Cancel_Quantity__c);
            orderItemRec.DR_Fulfilled_Quantity__c = orderItemRec.DR_Fulfilled_Quantity__c + totalFulfilledQuantity;
            orderItemRec.DR_Cancelled_Quantity__c = orderItemRec.DR_Cancelled_Quantity__c + totalCancelledQuantity;
            if(orderItemRec.DR_Fulfilled_Quantity__c > 0) {
                if(orderItemRec.DR_Fulfilled_Quantity__c == orderItemRec.Quantity) {
                    orderItemRec.DR_Order_Item_State__c = DRB2B_Constants.Fulfillment.LINE_ITEM_FULFILLED_STATUS;
                }
                else {
                    orderItemRec.DR_Order_Item_State__c = DRB2B_Constants.Fulfillment.LINE_ITEM_PARTIALLY_FULFILLED_STATUS;
                }
            }
            else if(orderItemRec.DR_Cancelled_Quantity__c == orderItemRec.Quantity) {
                orderItemRec.DR_Order_Item_State__c = DRB2B_Constants.Fulfillment.LINE_ITEM_CANCELLED_STATUS;
            }
            else if(orderItemRec.DR_Cancelled_Quantity__c > 0) {
                orderItemRec.DR_Order_Item_State__c = DRB2B_Constants.Fulfillment.LINE_ITEM_PARTIALLY_CANCELLED_STATUS;
            }
        }
        DmlManager.updateAsUser(orderItemRecs);
        LOGGER.info('Order Item records Updated.');
    }

    public void updateOrderFulfillmentRecords(List<DR_Fulfillment__c> orderFulfillmentRecs) {
        Map<Id, String> orderFulfillmentStatusByOrderId = new Map<Id, String>();
        //LOGGER.info('orderFulfillmentRecs --> ' + orderFulfillmentRecs);
        // Get all Order Items based on SF Order Id
        List<String> drOrderIds = (List<String>) Collection.of(orderFulfillmentRecs).listOf(DR_Fulfillment__c.DR_Order_Id__c);
        //LOGGER.info('drOrderIds --> ' + drOrderIds);
        List<Order> orders = orderSelector.getByDrOrderIds(drOrderIds);
        Map<String, Id> sfOrderIdByDrOrderId = (Map<String, Id>) Collection.of(orders).mapBy(Order.DR_Order_Id__c, Order.Id);
        List<OrderItem> orderItems = orderItemSelector.getByOrderIdsAndOrderItemType(sfOrderIdByDrOrderId.values(), 'Order Product');
        //LOGGER.info('orderItems --> ' + orderItems);

        // Group Order Items by SF Order Id
        Map<Id, List<OrderItem>> orderItemsBySfOrderId = (Map<Id, List<OrderItem>>) 
                    Collection.of(orderItems).groupBy(OrderItem.OrderId);
        //LOGGER.info('orderItemsBySfOrderId --> ' + orderItemsBySfOrderId);

        // Loop through all order items and check if there are more items to fulfill or cancel
        for(Id orderId : orderItemsBySfOrderId.keySet()) {
            for(OrderItem orderItem : orderItemsBySfOrderId.get(orderId)) {
                if((orderItem.DR_Fulfilled_Quantity__c + orderItem.DR_Cancelled_Quantity__c) < orderItem.Quantity) {
                    orderFulfillmentStatusByOrderId.put(orderId, DRB2B_Constants.Fulfillment.ORDER_OPEN_STATUS);
                    break;
                }
                else {
                    orderFulfillmentStatusByOrderId.put(orderId, DRB2B_Constants.Fulfillment.ORDER_COMPLETE_STATUS);
                }
            }
        }

        for(DR_Fulfillment__c orderFulfillmentRec : orderFulfillmentRecs) {
            // Check if a SF Order exists for DR Order Id
            if(DCM_BaseUtilities.isNotNullOrEmpty(sfOrderIdByDrOrderId.get(orderFulfillmentRec.DR_Order_Id__c))) {
                orderFulfillmentRec.Order_Id__c = sfOrderIdByDrOrderId.get(orderFulfillmentRec.DR_Order_Id__c);
                orderFulfillmentRec.DR_Fulfillment_Status__c = orderFulfillmentStatusByOrderId.get(orderFulfillmentRec.Order_Id__c);
                if(orderFulfillmentRec.DR_Fulfillment_Status__c.equalsIgnoreCase(DRB2B_Constants.Fulfillment.ORDER_COMPLETE_STATUS)) {
                    orderFulfillmentRec.Message__c = 'Fulfillment process completed for this Order';
                }
            }
            else {
                orderFulfillmentRec.Message__c = 'SF Order with this DR Order Id does not exist';
                orderFulfillmentRec.Retry_Attempts_Made__c = orderFulfillmentRec.Retry_Attempts_Made__c + 1;
                orderFulfillmentRec.DR_Fulfillment_Status__c = (orderFulfillmentRec.Retry_Attempts_Made__c > Integer.valueOf(configurationSelector.getFulfillmentRetryLimit())) 
                                ? DRB2B_Constants.Fulfillment.ORDER_FAILED_STATUS 
                                : DRB2B_Constants.Fulfillment.ORDER_REPROCESS_STATUS;
            }
        }

        LOGGER.info('orderFulfillmentRecs before update --> ' + orderFulfillmentRecs);
        DmlManager.updateAsUser(orderFulfillmentRecs);
        LOGGER.info('Order Fulfillment records Updated.');
    }

}