src/main/default/objects/DR_Connector_Configuration__mdt/DR_Connector_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>DR Connector Configuration</label>
    <pluralLabel>DR Connector Configurations</pluralLabel>
</CustomObject>

src/main/default/objects/WebCart/fields/DR_Checkout_Type__c.field-meta.xml
<CustomField>
    <fullName>DR_Checkout_Type__c</fullName>
    <description>The type of products stored in the Cart: Non-Digital, Digital</description>
    <inlineHelpText>The type of products stored in the Cart: Non-Digital, Digital</inlineHelpText>
    <label>DR Checkout Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Non-Digital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/Sync Checkout/classes/DRB2B_SyncTaxTest.cls
@isTest
public class DRB2B_SyncTaxTest {
    @testSetup
    static void setup() {
        System.runAs(DRB2B_TestEnvironment.portalAccountOwner) {
        Account account = new Account(Name = 'TestAccount');
        insert account;
        WebStore webStore = new WebStore(Name = 'TestWebStore', DefaultLanguage = 'en_US');
        insert webStore;
        WebCart cart = new WebCart(Name = 'Cart', WebStoreId = webStore.Id, AccountId = account.Id,BillingCountry='US');
        if(DRB2B_Utility.isCountryStateEnabled() == true){
            cart.BillingCountry= 'United States';
        }
        insert cart;
        CartDeliveryGroup cartDeliveryGroup = new CartDeliveryGroup(CartId = cart.Id, Name = 'Default Delivery',DeliverToCountry='US');
        if(DRB2B_Utility.isCountryStateEnabled() == true){
            cartDeliveryGroup.DeliverToCountry= 'United States';
        }
        
        insert cartDeliveryGroup;
        
        CartItem cartItem = new CartItem(
            CartId = cart.Id,
            Sku = 'SKU_Test1',
            Quantity = 3.0,
            Type = 'Product',
            Name = 'TestProduct',
            CartDeliveryGroupId = cartDeliveryGroup.Id
        );
        insert cartItem;
        }
    }
    
    @isTest
    static void testCartTaxForCartItemSuccessfullyInserted() {
        // Because test methods don't support Web service callouts, we create a mock response based on a static resource.
        // To create the static resource from the Developer Console, select File | New | Static Resource
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('GetTaxesResource');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        Test.startTest();
        // Associate the callout with a mock response.
        Test.setMock(HttpCalloutMock.class, mock);
        
        // digitalriverv3__DR_Connector_Configuration__mdt mdtId = [SELECT id, digitalriverv3__Key__c FROM digitalriverv3__DR_Connector_Configuration__mdt LIMIT 1];
        //mdtId.digitalriverv3__Key__c='Item-level';
        //update mdtId;
        // Test: execute the integration for the test cart ID.
        Id webCartId = [SELECT Id FROM WebCart WHERE Name = 'Cart' LIMIT 1].Id;
        Id cartItemId = [SELECT Id FROM CartItem WHERE CartId = :webCartId LIMIT 1].Id;
        List<Id> webCarts = new List<Id>{ webCartId };
            
        DRB2B_SyncTax.syncTax(webCarts);
        // Verify: the integration executed successfully
        // and the new CartTax record is inserted.
        List<CartTax> cartTaxesForCartItem = [SELECT Id FROM CartTax WHERE CartItemId = :cartItemId];
        System.assertEquals(0, cartTaxesForCartItem.size());
        Test.stopTest();
    }
    
    @isTest
    static void testWhenExternalServiceCallFailsAFailedStatusIsReturnedAndACartValidationOutputEntryIsNotCreated() {
        // Because test methods don't support Web service callouts, we create a mock response based on a static resource.
        // To create the static resource from the Developer Console, select File | New | Static Resource
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('GetInventoryResource');
        // The web service call returns an error code.
        mock.setStatusCode(404);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        Test.startTest();
        // Associate the callout with a mock response.
        Test.setMock(HttpCalloutMock.class, mock);
        
        // Test: execute the integration for the test cart ID and integration info.
        WebCart webCart = [SELECT Id FROM WebCart WHERE Name = 'Cart' LIMIT 1];
        List<Id> webCarts = new List<Id>{ webCart.Id };
            
        String expectedErrorMessage = 'There was a problem with the request. Error: 404';
        executeAndEnsureFailure(expectedErrorMessage, webCarts, false);
        
        Test.stopTest();
    }
    
    @isTest
    static void testProductsWithNoSkuHasError() {
        Test.startTest();
        
        WebCart webCart = [SELECT Id FROM WebCart WHERE Name = 'Cart' LIMIT 1];
        List<Id> webCarts = new List<Id>{ webCart.Id };
        List<CartDeliveryGroup> cartDeliveryGroups = [
            SELECT Id
            FROM CartDeliveryGroup
            WHERE CartId = :webCart.Id
            LIMIT 1
        ];
        
        // Insert a cart item without a SKU
        CartItem cartItemWithNoSku = new CartItem(
            CartId = webCart.Id,
            Quantity = 1.0,
            Type = 'Product',
            Name = 'TestProductNoSku',
            CartDeliveryGroupId = cartDeliveryGroups.get(0).Id
        );
        insert cartItemWithNoSku;
        
        String expectedErrorMessage = 'The SKUs for all products in your cart must be defined.';
        //executeAndEnsureFailure(expectedErrorMessage, webCarts, true);
        System.assert(Collection.of(new List<String>()).size() != null);
        Test.stopTest();
        
        // Remove the invalid cart item
        delete cartItemWithNoSku;
    }
    @isTest
    static void hasSKUError(){
        WebCart webCartId = [SELECT Id,DR_Checkout_Type__c FROM WebCart WHERE Name = 'Cart' LIMIT 1];
        cartItem cartItemId = [SELECT Id, Sku FROM CartItem WHERE CartId = :webCartId.id LIMIT 1];
        cartItemId.Sku='';
        UPDATE cartItemId;
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('GetTaxesResource');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        Test.startTest();
        // Associate the callout with a mock response.
        Test.setMock(HttpCalloutMock.class, mock);
        List<Id> webCarts = new List<Id>{ webCartId.Id };
            DRB2B_SyncTax.syncTax(webCarts);  
        Test.stopTest();
    }
    @isTest
    static void hasChargeProduct(){
        
        WebCart webCartId = [SELECT Id,DR_Checkout_Type__c FROM WebCart WHERE Name = 'Cart' LIMIT 1];
        webCartId.DR_Checkout_Type__c = 'Non-Digital';
        UPDATE webCartId;
        cartItem cartItemId = [SELECT Id, Type FROM CartItem WHERE CartId = :webCartId.id LIMIT 1];
        cartItemId.Type='Charge';
        UPDATE cartItemId;
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('GetTaxesResource');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        Test.startTest();
        // Associate the callout with a mock response.
        Test.setMock(HttpCalloutMock.class, mock);

        List<Id> webCarts = new List<Id>{ webCartId.id };
            
            DRB2B_SyncTax.syncTax(webCarts);
        
        // and the new CartTax record is inserted.
        List<CartTax> cartTaxesForCartItem = [SELECT Id FROM CartTax WHERE CartItemId = :cartItemId.id];
        System.assertEquals(0, cartTaxesForCartItem.size());
        Test.stopTest();
    }
    
    @isTest
    static void hasItemCheckout(){
       
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('GetTaxesResource');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        Test.startTest();
        // Associate the callout with a mock response.
        Test.setMock(HttpCalloutMock.class, mock);

        WebCart webCartId = [SELECT Id,DR_Checkout_Type__c FROM WebCart WHERE Name = 'Cart' LIMIT 1];
        cartItem cartItemId = [SELECT Id, Type FROM CartItem WHERE CartId = :webCartId.id LIMIT 1];
        List<Id> webCarts = new List<Id>{ webCartId.id };
            System.debug('item level value '+DR_Connector_Configuration__mdt.getInstance('DR_Ship_From_Address_Configuration'));
            DRB2B_SyncTax.syncTax(webCarts);
        // Verify: the integration executed successfully
        // and the new CartTax record is inserted.
        List<CartTax> cartTaxesForCartItem = [SELECT Id FROM CartTax WHERE CartItemId = :cartItemId.id];
        System.assertEquals(0, cartTaxesForCartItem.size());
        Test.stopTest();
    }
    
    // Executes taxes check and ensures an error is correctly triggered
    static void executeAndEnsureFailure(String expectedErrorMessage, List<Id> webCarts, Boolean userError) {
        try {
            DRB2B_SyncTax.syncTax(webCarts);
            
            // An exception should have been thrown before getting to this point:
            // System.assert(false);
        } catch (CalloutException e) {
            System.assertEquals(expectedErrorMessage, e.getMessage());
        }
        
        // A new CartValidationOutput record with level 'Error' was created.
        List<CartValidationOutput> cartValidationOutputs = [
            SELECT Id, Message
            FROM CartValidationOutput
            WHERE Level = 'Error'
        ];
        if (userError) {
            System.assertEquals(1, cartValidationOutputs.size());
            System.assertEquals(expectedErrorMessage, cartValidationOutputs.get(0).Message);
        } else {
            System.assertEquals(2, cartValidationOutputs.size());
        }
    }
    
    @isTest
    static void TaxCalculationTest(){
       	// Assign DR Shopper Permission Set to User
       /* DRB2B_TestEnvironment.assignPermissionSet(
            DRB2B_TestEnvironment.shopperUser,
            DRB2B_Constants.PermissionSet.SHOPPER
        );*/

       // System.runAs(DRB2B_TestEnvironment.shopperUser) {
            StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
            mock.setStaticResource('GetTaxesResource');
            mock.setStatusCode(200);
            mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
            Test.startTest();
            // Associate the callout with a mock response.
            Test.setMock(HttpCalloutMock.class, mock);
            
            WebCart webCartId = [SELECT Id,DR_Checkout_Type__c FROM WebCart WHERE Name = 'Cart' LIMIT 1];
            cartItem cartItemId = [SELECT Id, Type FROM CartItem WHERE CartId = :webCartId.id LIMIT 1];
            List<Id> webCarts = new List<Id>{ webCartId.id };
                System.debug('item level value '+DR_Connector_Configuration__mdt.getInstance('DR_Ship_From_Address_Configuration'));
            DRB2B_SyncTax.syncTax(webCarts);
            // Verify: the integration executed successfully
            // and the new CartTax record is inserted.
            List<CartTax> cartTaxesForCartItem = [SELECT Id FROM CartTax WHERE CartItemId = :cartItemId.id];
            System.assertEquals(0, cartTaxesForCartItem.size());
            Test.stopTest();
        //}
    }
}