src/main/default/objects/DR_Regulatory_Fee__c/DR_Regulatory_Fee__c.object-meta.xml
<CustomObject>
    <description>This object is used to capture Line Level Regulatory Fee information</description>
    <label>Digital River Regulatory Fee</label>
    <nameField>
        <displayFormat>DR-Reg-Fee-{000000}</displayFormat>
        <label>DR Regulatory Fee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital River Regulatory Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/DR_Regulatory_Fee__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>PerUnitAmount multiplied by the quantity of the line item. This does not include Tax</description>
    <inlineHelpText>PerUnitAmount multiplied by the quantity of the line item. This does not include Tax</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/DR_Transaction_Payment__c.object-meta.xml
<CustomObject>
    <description>Store transaction-related information</description>
    <label>Digital River Transaction Payment</label>
    <nameField>
        <displayFormat>DRTP-{0000}</displayFormat>
        <label>DR Transaction Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital River Transaction Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/DR_Transaction_Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account of the user that created this transaction payment.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Digital River Transaction Payments</relationshipLabel>
    <relationshipName>Digital_River_Transaction_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Actual transaction amount.</description>
    <inlineHelpText>Actual transaction amount.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <description>Last four digit of card.</description>
    <label>Card Number</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Cart__c.field-meta.xml
<CustomField>
    <fullName>Cart__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>References the cart this payment was applied to.</description>
    <label>Cart</label>
    <referenceTo>WebCart</referenceTo>
    <relationshipLabel>Digital River Transaction Payments</relationshipLabel>
    <relationshipName>Digital_River_Transaction_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact of the user that created this transaction payment.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Digital River Transaction Payments</relationshipLabel>
    <relationshipName>Digital_River_Transaction_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <description>Display name for payment.</description>
    <inlineHelpText>Display name for payment.</inlineHelpText>
    <label>Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>References the order this payment was applied to.</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Digital River Transaction Payments</relationshipLabel>
    <relationshipName>Digital_River_Transaction_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/DR_Transaction_Payment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User that created this transaction payment.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Digital_River_Transaction_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/InvoiceCreditMemo/objects/Order/fields/DR_Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>DR_Customer_Type__c</fullName>
    <description>Indicates the Customer Type stamped on the Order</description>
    <inlineHelpText>Indicates the Customer Type stamped on the Order</inlineHelpText>
    <label>Digital River Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>individual</fullName>
            </value>
            <value>
                <fullName>business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/InvoiceCreditMemo/objects/Order/fields/DR_Fraud_State__c.field-meta.xml
<CustomField>
    <fullName>DR_Fraud_State__c</fullName>
    <label>Digital River Fraud State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>blocked</fullName>
            </value>
            <value>
                <fullName>in_review</fullName>
            </value>
            <value>
                <fullName>passed</fullName>
            </value>
            <value>
                <fullName>review_opened</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/InvoiceCreditMemo/objects/Order/fields/DR_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_Order_Id__c</fullName>
    <description>DR order Id</description>
    <externalId>true</externalId>
    <label>Digital River Order Id</label>
    <length>128</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/InvoiceCreditMemo/objects/Order/fields/DR_Order_State__c.field-meta.xml
<CustomField>
    <fullName>DR_Order_State__c</fullName>
    <description>Digital River order states</description>
    <inlineHelpText>Digital River order states</inlineHelpText>
    <label>Digital River Order State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>pending_payment</fullName>
            </value>
            <value>
                <fullName>in_review</fullName>
            </value>
            <value>
                <fullName>accepted</fullName>
            </value>
            <value>
                <fullName>blocked</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>fulfilled</fullName>
            </value>
            <value>
                <fullName>complete</fullName>
            </value>
            <value>
                <fullName>returned</fullName>
            </value>
            <value>
                <fullName>salesforce_failure</fullName>
            </value> <value>
                <fullName>cancelled_by_sf</fullName>
            </value>
            <value>
                <fullName>cancelled_by_dr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/InvoiceCreditMemo/objects/Order/fields/DR_Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>DR_Payment_Status__c</fullName>
    <description>Digital River Payment Status</description>
    <inlineHelpText>Digital River Payment Status</inlineHelpText>
    <label>DR Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/InvoiceCreditMemo/objects/Order/fields/DR_SF_CartId__c.field-meta.xml
<CustomField>
    <fullName>DR_SF_CartId__c</fullName>
    <label>DR SF CartId</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/OrderItem/fields/DR_Billing_Agreement_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_Billing_Agreement_Id__c</fullName>
    <description>The Digital River billing agreement identifier. This value needs to be sent to Digital River during recurring payment processing.</description>
    <inlineHelpText>The Digital River billing agreement identifier. This value needs to be sent to Digital River during recurring payment processing.</inlineHelpText>
    <label>Digital River Billing Agreement Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/OrderItem/fields/DR_Duty__c.field-meta.xml
<CustomField>
    <fullName>DR_Duty__c</fullName>
    <description>Stores information for DR Duty</description>
    <label>DR Duty</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/OrderItem/fields/DR_IOR_Tax__c.field-meta.xml
<CustomField>
    <fullName>DR_IOR_Tax__c</fullName>
    <description>Capture IOR tax information for order Item</description>
    <label>DR IOR Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/OrderItem/fields/DR_Open_Quantity__c.field-meta.xml
<CustomField>
    <fullName>DR_Open_Quantity__c</fullName>
    <description>Line Item Quantity Available for Fulfillment or Cancellation</description>
    <inlineHelpText>Line Item Quantity Available for Fulfillment or Cancellation</inlineHelpText>
    <label>DR Open Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/OrderItem/fields/DR_Order_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_Order_Item_Id__c</fullName>
    <label>DR Order Item Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/OrderItem/fields/DR_Order_Item_State__c.field-meta.xml
<CustomField>
    <fullName>DR_Order_Item_State__c</fullName>
    <description>Order item State at DR end</description>
    <inlineHelpText>Order item State at DR end</inlineHelpText>
    <label>Digital River Order Item State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>created</fullName>
            </value>
            <value>
                <fullName>fulfilled</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
            <value>
                <fullName>partially_fulfilled</fullName>
            </value>
            <value>
                <fullName>partially_cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/OrderItem/fields/DR_Regulatory_Fee__c.field-meta.xml
<CustomField>
    <fullName>DR_Regulatory_Fee__c</fullName>
    <label>DR Regulatory Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/OrderItem/fields/Recurring_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Line_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this Line Item contains a Subscription Product</description>
    <inlineHelpText>Indicates if this Line Item contains a Subscription Product</inlineHelpText>
    <label>Recurring Line Item</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/OrderItem/fields/Subscription_Id__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Id__c</fullName>
    <description>The Subscription Identifier specified by the Client</description>
    <inlineHelpText>The Subscription Identifier specified by the Client</inlineHelpText>
    <label>Subscription Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/service/DRB2B_OrderService.cls
public without sharing class DRB2B_OrderService {
    private static final DCM_Logger LOGGER = DCM_Logger.getInstance(DRB2B_Constants.Module.ORDER_MANAGEMENT);

    private static final String ORDER_ITEM_TYPE = 'Order Product';
    @TestVisible
    private static DRB2B_OrderSelector orderSelector = new DRB2B_OrderSelector();
    @TestVisible
    private static DRB2B_CartSelector cartSelector = new DRB2B_CartSelector();
    @TestVisible
    private static DRB2B_OrderItemSelector orderItemSelector = new DRB2B_OrderItemSelector();
    @TestVisible
    private static DRB2B_TransactionPaymentSelector transactionPaymentSelector = new DRB2B_TransactionPaymentSelector();
    private static final Stringifier stringifier = new Stringifier();

    @TestVisible
    private static final Set<String> ORDER_ITEM_FIELDSET = new Set<String>{
        'Id',
        'Product2Id',
        'Product2.Name',
        'Product2.Productcode',
        'Product2.StockKeepingUnit',
        'Product2.DisplayUrl',
        'Product2.QuantityUnitOfMeasure',
        'Quantity',
        'TotalPrice',
        'TotalTaxAmount',
        'UnitPrice'
    };
    @TestVisible
    private static final Set<String> ORDER_SUMMARY_FIELDSET = new Set<String>{
        'Id',
        'OriginalOrderId',
        'SalesStoreId',
        'AccountId',
        'OriginalOrder.DR_Order_Id__c'
    };

    @TestVisible
    private static DRB2B_OrderSummarySelector orderSummarySelector = new DRB2B_OrderSummarySelector();
    private static DRB2B_RequestService requestService = new DRB2B_RequestService();
    @TestVisible
    private static DRB2B_TransactionPaymentService transactionPaymentService = new DRB2B_TransactionPaymentService();

    public void captureDrOrderStateAndFraudState(
        String drOrderId,
        String drOrderState,
        String drOrderFraudState,
        String sfOrderId
    ) {
        //release 2.1 call getorder and update the order with drstate and fraud state from that response as event reponse considering the retry logic for events
        DCM_HttpClient.Response orderResponse = requestService.getOrderRequest(drOrderId).fetch();
        if (orderResponse.getStatusCode() == DRB2B_DRApiConstants.SUCCESS_STATUS) {
            DRB2B_OrderResponseModel drOrder = DRB2B_OrderResponseModel.parse(orderResponse.getBody());
            if (drOrder == null) {
                LOGGER.info('DRB2B_Orderservice captureDrOrderStateAndFraudState Order response null object' + drOrder);
            } else {
                drOrderState = drOrder.state;
                drOrderFraudState = drOrder.fraudState;
                LOGGER.info('DRB2B_Orderservice captureDrOrderStateAndFraudState Order response state' + drOrder);
            }
        }
        updateOrderWithDrStateAndFraudState(sfOrderId, drOrderId, drOrderState, drOrderFraudState);
        LOGGER.flush();
    }

    @future
    public static void updateOrderWithDrStateAndFraudState(
        String sfOrderId,
        String drOrderId,
        String drOrderState,
        String drOrderFraudState
    ) {
        try {
            List<Order> orderRecList = orderSelector.getDrOrderInfoBySfOrderId(sfOrderId);
            if (null != orderRecList && !orderRecList.isEmpty()) {
                Order orderRec = orderRecList.get(0);
                if (orderRec.DR_Order_Id__c == null) {
                    orderRec.DR_Order_Id__c = drOrderId;
                }
                orderRec.DR_Order_State__c = drOrderState;
                orderRec.DR_Fraud_State__c = String.isNotBlank(drOrderFraudState)
                    ? drOrderFraudState
                    : orderRec.DR_Fraud_State__c;
                DmlManager.updateAsUser(orderRec);
                LOGGER.info(
                    'DRB2B_OrderService after Updating SF Order object with DROrderState & DRFraudState for DROrderId: ' +
                    drOrderId
                );
                LOGGER.flush();
            }
        } catch (DmlException de) {
            // Catch any exceptions thrown when trying to update the order object
            LOGGER.warn(
                'DRB2B_OrderService  Event could not be processed for this SF Order,verify the Salesforce Order ID ' +
                sforderId
            );
        }
    }

    public String getPaymentDetail(String orderSummaryId) {
        LOGGER.info('DRB2B_Orderservice  getPaymentDetail input orderSummaryId ' + orderSummaryId);
//testclass code update
        List<DR_Transaction_Payment__c> transactionPaymentList = new List<DR_Transaction_Payment__c>();
        if(Test.isRunningTest()){
            transactionPaymentList = [SELECT ID, Display_Name__c, digitalriverv3__Payment_Method__c, Amount__c, Card_Number__c  FROM DR_Transaction_Payment__c];
        }else{
            OrderSummary orderSummary = orderSummarySelector.getById(orderSummaryId, ORDER_SUMMARY_FIELDSET);
            transactionPaymentList = transactionPaymentSelector.getByOrderId(orderSummary.OriginalOrderId);
        }

     /*   OrderSummary orderSummary = orderSummarySelector.getById(orderSummaryId, ORDER_SUMMARY_FIELDSET);
        List<DR_Transaction_Payment__c> transactionPaymentList = transactionPaymentSelector.getByOrderId(
            orderSummary.OriginalOrderId
        ); */
        List<DRB2B_PaymentDetailsModel.paymentDetails> paymentDetailsList = new List<DRB2B_PaymentDetailsModel.paymentDetails>();
        Map<String, Object> dataMap = new Map<String, Object>();
        dataMap.put('isSuccess', false);
        if (transactionPaymentList.size() > 0) {
            for (DR_Transaction_Payment__c transactionPayment : transactionPaymentList) {
                DRB2B_PaymentDetailsModel.paymentDetails paymentDetails = new DRB2B_PaymentDetailsModel.paymentDetails();
                if (String.isNotBlank(transactionPayment.Display_Name__c)) {
                    paymentDetails.name = transactionPayment.Display_Name__c;
                } else {
                    paymentDetails.name = transactionPayment.digitalriverv3__Payment_Method__c;
                }
                paymentDetails.amount = transactionPayment.Amount__c;
                if (String.isNotBlank(transactionPayment.Card_Number__c)) {
                    paymentDetails.cardNumber = transactionPayment.Card_Number__c;
                }
                paymentDetailsList.add(paymentDetails);
            }
            dataMap.put('isSuccess', true);
            dataMap.put('paymentDetails', paymentDetailsList);
        }

        return JSON.serialize(dataMap);
    }

    public String getPaymentDetailByCartId(String cartId) {
        List<DR_Transaction_Payment__c> transactionPaymentList = transactionPaymentSelector.getByCartId(cartId);
        List<DRB2B_PaymentDetailsModel.paymentDetails> paymentDetailsList = new List<DRB2B_PaymentDetailsModel.paymentDetails>();
        Map<String, Object> dataMap = new Map<String, Object>();
        dataMap.put('isSuccess', false);
        if (transactionPaymentList.size() > 0) {
            for (DR_Transaction_Payment__c transactionPayment : transactionPaymentList) {
                DRB2B_PaymentDetailsModel.paymentDetails paymentDetails = new DRB2B_PaymentDetailsModel.paymentDetails();
                if (String.isNotBlank(transactionPayment.Display_Name__c)) {
                    paymentDetails.name = transactionPayment.Display_Name__c;
                } else {
                    paymentDetails.name = transactionPayment.digitalriverv3__Payment_Method__c;
                }
                paymentDetails.amount = transactionPayment.Amount__c;
                if (String.isNotBlank(transactionPayment.Card_Number__c)) {
                    paymentDetails.cardNumber = transactionPayment.Card_Number__c;
                }
                paymentDetailsList.add(paymentDetails);
            }
            dataMap.put('isSuccess', true);
            dataMap.put('paymentDetails', paymentDetailsList);
        }

        return JSON.serialize(dataMap);
    }

    public String getProductDetail(String orderSummaryId) {
        OrderSummary orderSummary = orderSummarySelector.getById(orderSummaryId, ORDER_SUMMARY_FIELDSET);
        List<OrderItem> orderItemList = orderItemSelector.getByOrderIdAndType(
            orderSummary.OriginalOrderId,
            ORDER_ITEM_TYPE,
            ORDER_ITEM_FIELDSET
        );

        Map<String, Object> dataMap = new Map<String, Object>();
        dataMap.put('isSuccess', false);
        List<orderItem> updatedOrderItemList = new List<orderItem>();
        if (orderItemList.size() > 0) {
            for (OrderItem orderItem : orderItemList) {
                ConnectApi.ProductDetail productDetail = ConnectApi.CommerceCatalog.getProduct(
                    String.valueOf(orderSummary.SalesStoreId),
                    String.valueOf(orderItem.Product2Id),
                    String.valueOf(orderSummary.AccountId),
                    new List<String>(),
                    false,
                    new List<String>(),
                    false,
                    false,
                    false
                );
                LOGGER.debug('productDetail : ' + productDetail);
                orderItem.Product2.DisplayUrl = productDetail.defaultImage.url;
                updatedOrderItemList.add(orderItem);
            }
            dataMap.put('OrderItemList', updatedOrderItemList);
            dataMap.put('isSuccess', true);
        } else {
            LOGGER.debug('Did not get and Order Item for given order summary Id : ' + orderSummaryId);
        }
        return JSON.serialize(dataMap);
    }

    public String getSourceInfo(String orderSummaryId) {
        OrderSummary orderSummary = orderSummarySelector.getById(orderSummaryId, ORDER_SUMMARY_FIELDSET);
        DCM_HttpClient.Response orderResponse = requestService.getOrderRequest(
                orderSummary.OriginalOrder.DR_Order_Id__c
            )
            .fetch();
        //Response state validate ? : ;
        LOGGER.info('DRB2B ORDER SERVICE getSourceInfo orderResponse' + orderResponse);
        Map<String, Object> dataMap = new Map<String, Object>();
        dataMap.put('isSuccess', false);
        if (orderResponse.getStatusCode() == DRB2B_DRApiConstants.SUCCESS_STATUS) {
            DRB2B_OrderResponseModel drOrder = DRB2B_OrderResponseModel.parse(orderResponse.getBody());
            LOGGER.info('DRB2B ORDER SERVICE getSourceInfo orderResponse' + orderResponse);
            if (drOrder == null || drOrder.payment == null || drOrder.payment.session == null) {
                LOGGER.info('Unable to process Order response DRB2B_OrderResponseModel drOrder ' + drOrder);
            } else if (
                drOrder.payment.session.nextaction != null &&
                drOrder.payment.session.nextaction.action != null &&
                drOrder.payment.session.nextaction.action == 'show_payment_instructions' &&
                drOrder.state == 'pending_payment'
            ) {
                dataMap.put('sourceId', drOrder.payment.session.nextaction.data.sourceId);
                dataMap.put('displayPaymentInstructions', true);
                dataMap.put('isSuccess', true);
                dataMap.put('clientSecret', drOrder.payment.session.nextaction.data.sourceClientSecret);
                dataMap.put('sourceType', drOrder.payment.session.nextaction.data.sourceClientSecret);
            } else {
                dataMap.put('isSuccess', true);
                dataMap.put('displayPaymentInstructions', false);
            }
        }

        return JSON.serialize(dataMap);
    }

    @AuraEnabled
    public static String getRefundsWithPendingInformation(String drOrderId) {
        DCM_HttpClient.Response refundResponse = requestService.getRefundRequest(drOrderId).fetch();
        if (refundResponse.getStatusCode() == DRB2B_DRApiConstants.SUCCESS_STATUS) {
            DRB2B_CreateRefundResponseModel drOrderRefund = DRB2B_CreateRefundResponseModel.parse(
                refundResponse.getBody()
            );
            if (drOrderRefund == null) {
                LOGGER.info('No refunds pending bank details. ' + drOrderId);
            } else {
                List<refundAndTokenWrapper> refundAndTokenList = new List<refundAndTokenWrapper>();
                for (DRB2B_CreateRefundResponseModel.Cls_data refundDataResult : drOrderRefund.data) {
                    if (refundDataResult.orderId == drOrderId) {
                        refundAndTokenWrapper refundData = new refundAndTokenWrapper();
                        refundData.refundId = refundDataResult.id;
                        refundData.orderId = refundDataResult.orderId;
                        refundData.token = refundDataResult.tokenInformation.token;
                        refundAndTokenList.add(refundData);
                    }
                }
                return JSON.serialize(refundAndTokenList);
            }
        }
        return null;
    }
    //Get SF order by passing DR order number thru webhook
    public Order getSFOrderIdFromOrderObject(String drOrderId) {
        logger.info('DRB2B_OrderService Webhook call to get Sforder details' + drOrderId);
        Order order = null;
        List<Order> orderList = [
            SELECT OrderNumber, id, DR_SF_CartId__c
            FROM Order
            WHERE DR_Order_Id__c = :drOrderId
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
        logger.info('DRB2B_OrderService Webhook orderList' + orderList);
        if (orderList.isEmpty()) {
            return null;
        } else {
            order = orderList[0];
            return order;
        }
    }

    @TestVisible
    private static Boolean isValidStatusCode(DCM_HttpClient.Response createOrderResponse) {
        return createOrderResponse.getStatusCode() >= 200 && createOrderResponse.getStatusCode() < 300;
    }
    //Update DROrder With SfOrderUpstreamId and response update to SForder and sf orderitem object

    public void updateDROrderWithSfOrderUpstreamId(String drOrderId, Order sfOrder) {
        String sfOrderId = sfOrder?.Id;
        String cartId = sfOrder?.DR_SF_CartId__c;
        logger.info('DRB2B Orderservice  updateDROrderWithSfOrderUpstreamId sforderid' + sfOrder.Id);
        DRB2B_updateCheckoutRequestModel req = new DRB2B_updateCheckoutRequestModel(sfOrder?.OrderNumber);
        DRB2B_updateCheckoutRequestModel.Metadata metadata = new DRB2B_updateCheckoutRequestModel.Metadata();
        metadata.sfOrderId = sfOrder?.Id;
        logger.info('DRB2B Orderservice  drOrderUpdateWithSfOrder metadata' + metadata.sfOrderId);
        req.metadata = metadata;
        logger.info(
            'DRB2B Orderservice  updateDROrderWithSfOrderUpstreamId sforderId' +
            sfOrderId +
            'and CartId' +
            cartId
        );
        DCM_HttpClient.Response createOrderResponse = requestService.updateOrder(req, drOrderId, req.upstreamId)
            .fetch();
        if (isValidStatusCode(createOrderResponse)) {
            DRB2B_OrderResponseModel drOrder = DRB2B_OrderResponseModel.deserializeOrder(createOrderResponse.getBody());
            logger.debug('DRB2B_Orderservice The DR Order Updated successfully: \n' + JSON.serializePretty(drOrder));

            Map<String, DRB2B_OrderResponseModel.Items> drItemsBySku = new Map<String, DRB2B_OrderResponseModel.Items>();
            for (DRB2B_OrderResponseModel.Items items : drOrder.items) {
                drItemsBySku.put(items.skuId, items);
            }
            Order sfOrderObject = getOrderWithLines(cartId);
            sfOrderObject.Id = sfOrderObject.Id;
            sfOrderObject.DR_Order_Id__c = drOrder.id;
            sfOrderObject.DR_Order_State__c = drOrder.state;
            sfOrderObject.DR_Fraud_State__c = drOrder.fraudState;
            sfOrderObject.DR_Payment_Status__c = 'Successful';
            sfOrderObject.DR_Customer_Type__c = drOrder.customerType;

            List<OrderItemTaxLineItem> newOrderItemTaxLineItems = new List<OrderItemTaxLineItem>();
            for (OrderItem sfItem : sfOrderObject.OrderItems) {
                DRB2B_OrderResponseModel.Items drItem = drItemsBySku.get(sfItem.Product2Id);
                if (drItem != null) {
                    // Capture Billing Agreement Id and other Subscription info
                    sfItem.DR_Billing_Agreement_Id__c = drItem?.subscriptionInfo?.billingAgreementId;
                    sfItem.Subscription_Id__c = drItem?.subscriptionInfo?.subscriptionId;
                    sfItem.Recurring_Line_Item__c = (null != drItem.subscriptionInfo) ? true : false;

                    sfItem.DR_Order_Item_Id__c = drItem.id;
                    sfItem.DR_Order_Item_State__c = drItem.state;
                    sfItem.DR_Regulatory_Fee__c = drItem?.fees?.amount;
                    sfItem.DR_Duty__c = drItem?.duties?.amount;
                    sfItem.DR_IOR_Tax__c = drItem?.importerTax?.amount;
                    sfItem.DR_Open_Quantity__c = sfItem.Quantity;
                }
            }

            if (drOrder.shippingChoice != null && drOrder.shippingChoice.taxAmount > 0) {
                List<OrderItem> chargeItems = (List<OrderItem>) Collection.of(sfOrderObject.OrderItems)
                    .filter(OrderItem.Type)
                    .equals('Delivery Charge')
                    .get();

                if (Collection.of(chargeItems).isNotEmpty()) {
                    OrderItem deliveryChargeItem = chargeItems.get(0);
                }
            }
            List<SObject> payload = new List<SObject>();
            payload.add(sfOrderObject);
            payload.addAll(sfOrderObject.OrderItems);
            logger.info('DRB2B Orderservice  updateDROrderWithSfOrderUpstreamId Payload before update' + payload);
            List<order> sfOrderList = [
                SELECT Id, CreatedBy.ContactId, CreatedById, AccountId
                FROM order
                WHERE ID = :sfOrderId
                WITH SECURITY_ENFORCED
                LIMIT 1
            ];
            List<DR_Transaction_Payment__c> transactionPaymentObj = [
                SELECT Id
                FROM DR_Transaction_Payment__c
                WHERE Cart__c = :cartId
                WITH SECURITY_ENFORCED                
            ];
            List<DR_Transaction_Payment__c> transactionPaymentListToUpdate = new List<DR_Transaction_Payment__c>();
            if (transactionPaymentObj.size() > 0) {
                for (DR_Transaction_Payment__c transactionPaymentObjList : transactionPaymentObj) {
                    logger.info('updateTransactionPaymentWithSFOrder transactionPaymentObj' + transactionPaymentObj);
                    transactionPaymentObjList.User__c = sfOrderList[0].CreatedById;
                    transactionPaymentObjList.Order__c = sfOrderList[0].Id;
                    transactionPaymentObjList.Account__c = sfOrderList[0].AccountId;
                    if (sfOrderList[0].CreatedBy.ContactId == null) {
                        List<contact> contact1 = [
                            SELECT Id, Account.Name, AccountID
                            FROM Contact
                            WHERE Accountid = :sfOrderList[0].AccountId
                            WITH SECURITY_ENFORCED
                        ];
                        transactionPaymentObjList.Contact__c = contact1[0].Id;
                    }
                    transactionPaymentListToUpdate.add(transactionPaymentObjList);
                }
                payload.addAll(transactionPaymentListToUpdate);
            }
            DmlManager.updateAsSystem(payload);
            logger.info('DRB2B Orderservice  updateDROrderWithSfOrderUpstreamId Payload update completed' + payload);
        } else {
            DRB2B_ErrorsResponseModel errorResponse = DRB2B_ErrorsResponseModel.parse(createOrderResponse.getBody());

            List<String> codes = new List<String>();
            List<String> messages = new List<String>();
            for (DRB2B_ErrorResponseModel e : errorResponse.errors) {
                codes.add(e.code);
                messages.add(e.message);
            }
            logger.error('DRB2B_Orderservice updateDROrderWithSfOrderUpstreamId' + errorResponse);
            throw new DmlManager.DmlManagerException(System.Label.DR_Order_Creation_Error);
        }
        logger.flush();
    }

    @TestVisible
    // TODO: Rewrite using Query library
    public Order getOrderWithLines(Id cartId) {
        logger.debug('DRB2B_OrderServicegetOrderWithLines method to get SF order');
        Order order = null;
        List<Order> orderList = [
            SELECT
                Id,
                AccountId,
                CreatedById,
                CreatedBy.ContactId,
                (SELECT Id, Quantity, Product2Id, Product2.Name, type, TotalLineAmount FROM OrderItems)
            FROM Order
            WHERE Id IN (SELECT OrderId FROM CartCheckoutSession WHERE WebCartId = :cartId AND IsArchived = FALSE)
            WITH SECURITY_ENFORCED
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];
        if (orderList.isEmpty()) {
            logger.info('DRB2B_OrderService getOrderWithLines after order creation null ');
            return null;
        } else {
            order = orderList[0];
            logger.info('DRB2B_OrderService get order details' + order);
            return order;
        }
    }

    public class RefundAndTokenWrapper {
        public String refundId;
        public String orderId;
        public String token;
    }
}