src/main/default/objects/DR_Regulatory_Fee__c/DR_Regulatory_Fee__c.object-meta.xml
<CustomObject>
    <description>This object is used to capture Line Level Regulatory Fee information</description>
    <label>Digital River Regulatory Fee</label>
    <nameField>
        <displayFormat>DR-Reg-Fee-{000000}</displayFormat>
        <label>DR Regulatory Fee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital River Regulatory Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/DR_Regulatory_Fee__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>PerUnitAmount multiplied by the quantity of the line item. This does not include Tax</description>
    <inlineHelpText>PerUnitAmount multiplied by the quantity of the line item. This does not include Tax</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/DR_Regulatory_Fee__c/fields/Cart_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>Cart_Item_Id__c</fullName>
    <description>SF Cart Item Id to which Regulatory Fee Record is associated</description>
    <inlineHelpText>SF Cart Item Id to which Regulatory Fee Record is associated</inlineHelpText>
    <label>Cart Item Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Regulatory_Fee__c/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <description>The type of Fee. Valid values are battery, weee, copyright, e_waste and packaging</description>
    <inlineHelpText>The type of Fee. Valid values are battery, weee, copyright, e_waste and packaging</inlineHelpText>
    <label>Fee Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/model/DRB2B_RegulatoryFeeModal.cls
public with sharing class DRB2B_RegulatoryFeeModal implements Collection.Wrapper {
    public DRB2B_RegulatoryFeeModal() {
    }

    public DRB2B_RegulatoryFeeModal(DR_Regulatory_Fee__c fee) {
        this.regulatoryFee = fee;
    }

    public DR_Regulatory_Fee__c regulatoryFee;

    public void wrap(Object item) {
        this.regulatoryFee = (DR_Regulatory_Fee__c) item;
        this.id = this.regulatoryFee.id;
        this.name = this.regulatoryFee.Name;
        this.amount = this.regulatoryFee.Amount__c;
        this.feeType = this.regulatoryFee.Fee_Type__c;
        this.cartItemId = this.regulatoryFee.Cart_Item_Id__c;
        if (this.cartItemId != null) {
            DRB2B_CartItemSelector itemSelector = new DRB2B_CartItemSelector();
            this.productName = itemSelector.getById(this.cartItemId, new Set<String>{ 'Name' }).Name; //TODO: make this bulkified
        }
    }

    @AuraEnabled
    public String id { get; set; }

    @AuraEnabled
    public Decimal amount { get; set; }

    @AuraEnabled
    public String name { get; set; }

    @AuraEnabled
    public String feeType { get; set; }

    @AuraEnabled
    public Id cartItemId { get; set; }

    @AuraEnabled
    public String productName { get; set; }

    public class DRB2B_RegulatoryFeeModalFactory implements Collection.WrapperFactory {
        public Object wrap(Object item) {
            return new DRB2B_RegulatoryFeeModal((DR_Regulatory_Fee__c) item);
        }
    }
}