src/main/default/objects/DR_ECCN_Lookup__c/DR_ECCN_Lookup__c.object-meta.xml
<CustomObject>
    <label>Digital River ECCN Lookup</label>
    <nameField>
        <label>DR Classification Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Digital River ECCN Lookups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Product2/fields/DR_ECCN__c.field-meta.xml
<CustomField>
    <fullName>DR_ECCN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DR ECCN *</label>
    <referenceTo>DR_ECCN_Lookup__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Product2/fields/DR_HS_Code__c.field-meta.xml
<CustomField>
    <fullName>DR_HS_Code__c</fullName>
    <label>DR HS Code</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Product2/fields/DR_Managed_Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>DR_Managed_Fulfillment__c</fullName>
    <description>Signifies the product is physically fulfilled by Digital River</description>
    <inlineHelpText>Signifies the product is physically fulfilled by Digital River</inlineHelpText>
    <label>DR Managed Fulfillment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DRGlobalFulfillment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Product2/fields/DR_Manufacturer_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_Manufacturer_Id__c</fullName>
    <label>DR Manufacturer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Product2/fields/DR_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>DR_Part_Number__c</fullName>
    <description>The manufacturer’s part number</description>
    <label>DR Part Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Product2/fields/DR_Product_Country_Origin__c.field-meta.xml
<CustomField>
    <fullName>DR_Product_Country_Origin__c</fullName>
    <label>DR Product Country Origin *</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AX</fullName>
                <label>Åland Islands</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>DZ</fullName>
                <label>Algeria</label>
            </value>
            <value>
                <fullName>AS</fullName>
                <label>American Samoa</label>
            </value>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua And Barbuda</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BS</fullName>
                <label>Bahamas</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BZ</fullName>
                <label>Belize</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BT</fullName>
                <label>Bhutan</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia, Plurinational State Of</label>
            </value>
            <value>
                <fullName>BQ</fullName>
                <label>Bonaire, Sint Eustatius And Saba</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia And Herzegovina</label>
            </value>
            <value>
                <fullName>BW</fullName>
                <label>Botswana</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Product2/fields/DR_Product_Weight__c.field-meta.xml
<CustomField>
    <fullName>DR_Product_Weight__c</fullName>
    <description>The weight of the product measured in the unit specified by DR Unit of weight.</description>
    <inlineHelpText>The weight of the product measured in the unit specified by DR Unit of weight.</inlineHelpText>
    <label>DR Product Weight</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Product2/fields/DR_SKU_Group__c.field-meta.xml
<CustomField>
    <fullName>DR_SKU_Group__c</fullName>
    <label>DR SKU Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Product2/fields/DR_TAXGROUP__c.field-meta.xml
<CustomField>
    <fullName>DR_TAXGROUP__c</fullName>
    <label>DR TAXGROUP *</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Downloadable Goods (Non-Software)</fullName>
            </value>
            <value>
                <fullName>Food, Beverage &amp; Household</fullName>
            </value>
            <value>
                <fullName>Physical Goods</fullName>
            </value>
            <value>
                <fullName>Services &amp; Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Software (Downloadable &amp; Physical)</fullName>
            </value>
            <value>
                <fullName>Warranties</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Product2/fields/DR_TAXTYPE__c.field-meta.xml
<CustomField>
    <fullName>DR_TAXTYPE__c</fullName>
    <label>DR TAXTYPE *</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DR_TAXGROUP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>DR_TAXTYPES</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Product2/fields/DR_Unit_of_Weight__c.field-meta.xml
<CustomField>
    <fullName>DR_Unit_of_Weight__c</fullName>
    <description>Unit of measurement applied to DR</description>
    <inlineHelpText>Unit of measurement applied to DR</inlineHelpText>
    <label>DR Unit of Weight</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>oz</fullName>
            </value>
            <value>
                <fullName>lb</fullName>
            </value>
            <value>
                <fullName>g</fullName>
            </value>
            <value>
                <fullName>Kg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/globalValueSets/DR_TAXTYPES.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Digital Image</fullName>
    </customValue>
    <customValue>
        <fullName>Virtual Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Music</fullName>
    </customValue>
    <customValue>
        <fullName>Electronic Newspapers (Includes Subscriptions)</fullName>
    </customValue>
    <customValue>
        <fullName>Electronic Magazines (Includes Subscriptions)</fullName>
    </customValue>
    <customValue>
        <fullName>Educational / Vocational Texts</fullName>
    </customValue>
    <customValue>
        <fullName>eBooks</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Prescription Vitamins</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Prescription Drugs</fullName>
    </customValue>
    <customValue>
        <fullName>Miscellaneous Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Food - General</fullName>
    </customValue>
    <customValue>
        <fullName>Automatic Blood Pressure Monitors</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Stove</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Dehumidifier</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Air Conditioner</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Ceiling Fan</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Light Bulbs</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Freezer</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Refrigerator</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Washer</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Dryer</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Star - Dishwasher</fullName>
    </customValue>
    <customValue>
        <fullName>Computer Supplies - Subscription</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile Devices</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Electronics (Photographic Filming or Video Equipment)</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Electronics (T.V. Monitor Display) - Size (&gt;4&quot;&lt;15&quot;)</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Electronics (T.V. Monitor Display) - Size (= or &gt;35&quot;)</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Electronics (T.V. Monitor Display) - Size (= or &gt;15&quot;&lt;35&quot;)</fullName>
    </customValue>
    <customValue>
        <fullName>Video Game Consoles and Accessories</fullName>
    </customValue>
    <masterLabel>DR TAXTYPES</masterLabel>
</GlobalValueSet>

src/main/default/classes/DRB2B_UpsertSkuModelService.cls
public with sharing class DRB2B_UpsertSkuModelService {
    
    private static final Set<String> PRODUCT_FIELDS_NAMES = new Set<String>{
        'Id',
        'Name',
        'DR_TAXTYPE__c',
        'DR_TAXGROUP__c',
        'StockKeepingUnit',
        'DR_ECCN__r.Name',
        'DR_Product_Country_Origin__c',
        'DR_HS_Code__c',
        'DR_Part_Number__c', 
        'DR_Product_Weight__c',
        'DR_Unit_of_Weight__c',
        'DR_Managed_Fulfillment__c',
        'DR_Manufacturer_Id__c',
        'DR_SKU_Group__c'
    };

    public final String WEIGHT_UNIT = 'oz';

    @TestVisible
    private static DRB2B_ProductSelector productSelector = new DRB2B_ProductSelector();

    public DRB2B_ProductSyncUpsertSkuRequest getUpsertProductRequestModel(Id productId, String taxCode) {
        Product2 product = productSelector.getById(
            productId,
            PRODUCT_FIELDS_NAMES
        );

        DRB2B_ProductSyncUpsertSkuRequest model = new DRB2B_ProductSyncUpsertSkuRequest();
        DRB2B_ProductSyncUpsertSkuRequest.Metadata productMataObj = new DRB2B_ProductSyncUpsertSkuRequest.Metadata();
        productMataObj.taxType = product.DR_TAXTYPE__c;
        productMataObj.taxGroup = product.DR_TAXGROUP__c;
        productMataObj.sku = product.StockKeepingUnit;

        model.eccn =  product.DR_ECCN__r.Name;
        model.name = product.Name;
        model.countryOfOrigin = product.DR_Product_Country_Origin__c;
        model.fulfill =false;
        model.hsCode  = product.DR_HS_Code__c;
        model.partNumber = product.DR_Part_Number__c;
        model.metadata = productMataObj;  
        model.skuGroupId = product.DR_SKU_Group__c;
        
        if(product.DR_Product_Weight__c != null){
            model.weight = product.DR_Product_Weight__c;
            if(product.DR_Unit_of_Weight__c != null){
                model.weightUnit = product.DR_Unit_of_Weight__c;
            }else{
                model.weightUnit = WEIGHT_UNIT;
            }
        }
        if(product.DR_Managed_Fulfillment__c != null){
            model.managedFulfillment = product.DR_Managed_Fulfillment__c;
        }
        if(product.DR_Manufacturer_Id__c != null){
            model.manufacturerId = product.DR_Manufacturer_Id__c;
        }
        if(String.isNotBlank(taxCode))
        {
            model.taxCode = taxCode;
        }
        return model; 
    }
}