src/main/default/objects/DR_Invoice_Credit_Memo__c/DR_Invoice_Credit_Memo__c.object-meta.xml
<CustomObject>
    <description>This object stores DR Invoice and Credit Memo File information</description>
    <label>DR Invoice And Credit Memo</label>
    <nameField>
        <displayFormat>DR-Inv-CrMemo-{000000}</displayFormat>
        <label>DR Invoice Credit Memo Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DR Invoice And Credit Memos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/DR_Invoice_Credit_Memo__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <description>Stores DR order.invoice.created or order.credit_memo.created Event Id</description>
    <inlineHelpText>Stores DR order.invoice.created or order.credit_memo.created Event Id</inlineHelpText>
    <label>Event Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Invoice_Credit_Memo__c/fields/File_Id__c.field-meta.xml
<CustomField>
    <fullName>File_Id__c</fullName>
    <description>Stores DR Invoice or Credit Memo File Id.</description>
    <inlineHelpText>Stores DR Invoice or Credit Memo File Id</inlineHelpText>
    <label>File Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/DR_Invoice_Credit_Memo__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <description>Stores DR File Type</description>
    <inlineHelpText>Stores DR File Type</inlineHelpText>
    <label>File Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Credit Memo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/DR_Invoice_Credit_Memo__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Order for which the DR Invoice or Credit Memo was generated</description>
    <inlineHelpText>Order for which the DR Invoice or Credit Memo was generated</inlineHelpText>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>DR Invoice And Credit Memos</relationshipLabel>
    <relationshipName>DR_Invoice_And_Credit_Memos</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/InvoiceCreditMemo/classes/DRB2B_InvoiceAndCreditMemoSelector.cls
public without sharing class DRB2B_InvoiceAndCreditMemoSelector {

    public List<DR_Invoice_Credit_Memo__c> getBySfOrderId(String sfOrderId) {
        return (List<DR_Invoice_Credit_Memo__c>) new DCM_Query(DR_Invoice_Credit_Memo__c.sObjectType)
            .selectField(DR_Invoice_Credit_Memo__c.Id)
            .selectField(DR_Invoice_Credit_Memo__c.Event_Id__c)
            .selectField(DR_Invoice_Credit_Memo__c.File_Id__c)
            .selectField(DR_Invoice_Credit_Memo__c.File_Type__c)
            .selectField(DR_Invoice_Credit_Memo__c.OrderId__c)
            .addConditionEq('OrderId__c', sfOrderId)
            .run();
    }
}